import type { BasicLanguageCode } from '../language-registry';

export type PremiumAssistantUiMessages = {
  title:string; description:string; back:string; start:string; stop:string; transcript:string; transcriptHint:string;
  confirm:string; cancel:string; listening:string; processing:string; waiting:string; answer:string; replay:string;
  stopPlayback:string; microphoneError:string; transcriptionError:string; networkError:string; aiError:string;
  playbackError:string; textFallback:string; emptyTranscript:string;
};

export const premiumAssistantUiMessages: Record<BasicLanguageCode, PremiumAssistantUiMessages> = {
  ro:{title:'Vorbește cu AGM',description:'Asistent conversațional Premium. Verifică textul înainte de trimitere.',back:'Înapoi la Premium',start:'Pornește microfonul',stop:'Oprește microfonul',transcript:'Transcriere',transcriptHint:'Poți corecta textul înainte de confirmare.',confirm:'Confirmă și întreabă AGM',cancel:'Anulează',listening:'Ascult. Vorbește acum.',processing:'Transcriu vocea.',waiting:'AGM pregătește răspunsul.',answer:'Răspuns AGM',replay:'Redă răspunsul',stopPlayback:'Oprește redarea',microphoneError:'Microfonul nu este disponibil sau permisiunea a fost refuzată.',transcriptionError:'Vocea nu a putut fi transcrisă.',networkError:'Conexiunea nu este disponibilă.',aiError:'AGM nu poate răspunde momentan.',playbackError:'Răspunsul rămâne vizibil, dar redarea vocală nu este disponibilă.',textFallback:'Poți scrie întrebarea direct.',emptyTranscript:'Introduceți sau dictați o întrebare.'},
  de:{title:'Mit AGM sprechen',description:'Premium-Konversationsassistent. Prüfen Sie den Text vor dem Senden.',back:'Zurück zu Premium',start:'Mikrofon starten',stop:'Mikrofon stoppen',transcript:'Transkript',transcriptHint:'Sie können den Text vor der Bestätigung korrigieren.',confirm:'Bestätigen und AGM fragen',cancel:'Abbrechen',listening:'Ich höre zu. Sprechen Sie jetzt.',processing:'Sprache wird transkribiert.',waiting:'AGM bereitet die Antwort vor.',answer:'AGM-Antwort',replay:'Antwort wiedergeben',stopPlayback:'Wiedergabe stoppen',microphoneError:'Mikrofon nicht verfügbar oder Berechtigung verweigert.',transcriptionError:'Sprache konnte nicht transkribiert werden.',networkError:'Keine Netzwerkverbindung.',aiError:'AGM kann derzeit nicht antworten.',playbackError:'Die Antwort bleibt sichtbar, aber die Sprachausgabe ist nicht verfügbar.',textFallback:'Sie können die Frage direkt eingeben.',emptyTranscript:'Geben oder diktieren Sie eine Frage.'},
  en:{title:'Talk to AGM',description:'Premium conversational assistant. Review the text before sending.',back:'Back to Premium',start:'Start microphone',stop:'Stop microphone',transcript:'Transcript',transcriptHint:'You can correct the text before confirmation.',confirm:'Confirm and ask AGM',cancel:'Cancel',listening:'Listening. Speak now.',processing:'Transcribing speech.',waiting:'AGM is preparing the answer.',answer:'AGM response',replay:'Play response',stopPlayback:'Stop playback',microphoneError:'The microphone is unavailable or permission was denied.',transcriptionError:'Speech could not be transcribed.',networkError:'The network is unavailable.',aiError:'AGM cannot respond right now.',playbackError:'The response remains visible, but voice playback is unavailable.',textFallback:'You can type the question directly.',emptyTranscript:'Type or dictate a question.'},
  fr:{title:'Parler à AGM',description:'Assistant conversationnel Premium. Vérifiez le texte avant l’envoi.',back:'Retour à Premium',start:'Démarrer le microphone',stop:'Arrêter le microphone',transcript:'Transcription',transcriptHint:'Vous pouvez corriger le texte avant confirmation.',confirm:'Confirmer et interroger AGM',cancel:'Annuler',listening:'Je vous écoute. Parlez maintenant.',processing:'Transcription de la voix.',waiting:'AGM prépare la réponse.',answer:'Réponse AGM',replay:'Lire la réponse',stopPlayback:'Arrêter la lecture',microphoneError:'Microphone indisponible ou autorisation refusée.',transcriptionError:'La voix n’a pas pu être transcrite.',networkError:'Le réseau est indisponible.',aiError:'AGM ne peut pas répondre actuellement.',playbackError:'La réponse reste visible, mais la lecture vocale est indisponible.',textFallback:'Vous pouvez saisir directement la question.',emptyTranscript:'Saisissez ou dictez une question.'},
  nl:{title:'Praat met AGM',description:'Premium gespreksassistent. Controleer de tekst vóór verzending.',back:'Terug naar Premium',start:'Microfoon starten',stop:'Microfoon stoppen',transcript:'Transcript',transcriptHint:'U kunt de tekst vóór bevestiging corrigeren.',confirm:'Bevestig en vraag AGM',cancel:'Annuleren',listening:'Ik luister. Spreek nu.',processing:'Spraak wordt getranscribeerd.',waiting:'AGM bereidt het antwoord voor.',answer:'AGM-antwoord',replay:'Antwoord afspelen',stopPlayback:'Afspelen stoppen',microphoneError:'Microfoon niet beschikbaar of toestemming geweigerd.',transcriptionError:'Spraak kon niet worden getranscribeerd.',networkError:'Netwerk niet beschikbaar.',aiError:'AGM kan nu niet antwoorden.',playbackError:'Het antwoord blijft zichtbaar, maar spraakweergave is niet beschikbaar.',textFallback:'U kunt de vraag rechtstreeks typen.',emptyTranscript:'Typ of dicteer een vraag.'},
  ru:{title:'Поговорить с AGM',description:'Премиум-разговорный помощник. Проверьте текст перед отправкой.',back:'Назад к Premium',start:'Включить микрофон',stop:'Остановить микрофон',transcript:'Расшифровка',transcriptHint:'Перед подтверждением текст можно исправить.',confirm:'Подтвердить и спросить AGM',cancel:'Отмена',listening:'Слушаю. Говорите.',processing:'Речь преобразуется в текст.',waiting:'AGM готовит ответ.',answer:'Ответ AGM',replay:'Озвучить ответ',stopPlayback:'Остановить озвучивание',microphoneError:'Микрофон недоступен или доступ запрещён.',transcriptionError:'Не удалось распознать речь.',networkError:'Сеть недоступна.',aiError:'AGM сейчас не может ответить.',playbackError:'Ответ остаётся видимым, но озвучивание недоступно.',textFallback:'Вопрос можно ввести текстом.',emptyTranscript:'Введите или продиктуйте вопрос.'},
  pl:{title:'Porozmawiaj z AGM',description:'Konwersacyjny asystent Premium. Sprawdź tekst przed wysłaniem.',back:'Wróć do Premium',start:'Włącz mikrofon',stop:'Zatrzymaj mikrofon',transcript:'Transkrypcja',transcriptHint:'Możesz poprawić tekst przed potwierdzeniem.',confirm:'Potwierdź i zapytaj AGM',cancel:'Anuluj',listening:'Słucham. Mów teraz.',processing:'Trwa transkrypcja mowy.',waiting:'AGM przygotowuje odpowiedź.',answer:'Odpowiedź AGM',replay:'Odtwórz odpowiedź',stopPlayback:'Zatrzymaj odtwarzanie',microphoneError:'Mikrofon jest niedostępny lub odmówiono uprawnienia.',transcriptionError:'Nie udało się przepisać mowy.',networkError:'Sieć jest niedostępna.',aiError:'AGM nie może teraz odpowiedzieć.',playbackError:'Odpowiedź pozostaje widoczna, ale odtwarzanie głosu jest niedostępne.',textFallback:'Możesz wpisać pytanie bezpośrednio.',emptyTranscript:'Wpisz lub podyktuj pytanie.'},
  tr:{title:'AGM ile konuş',description:'Premium konuşma asistanı. Göndermeden önce metni kontrol edin.',back:'Premium’a dön',start:'Mikrofonu başlat',stop:'Mikrofonu durdur',transcript:'Döküm',transcriptHint:'Onaylamadan önce metni düzeltebilirsiniz.',confirm:'Onayla ve AGM’ye sor',cancel:'İptal',listening:'Dinliyorum. Şimdi konuşun.',processing:'Konuşma yazıya çevriliyor.',waiting:'AGM yanıtı hazırlıyor.',answer:'AGM yanıtı',replay:'Yanıtı seslendir',stopPlayback:'Seslendirmeyi durdur',microphoneError:'Mikrofon kullanılamıyor veya izin reddedildi.',transcriptionError:'Konuşma yazıya çevrilemedi.',networkError:'Ağ kullanılamıyor.',aiError:'AGM şu anda yanıt veremiyor.',playbackError:'Yanıt görünür kalır, ancak sesli oynatma kullanılamıyor.',textFallback:'Soruyu doğrudan yazabilirsiniz.',emptyTranscript:'Bir soru yazın veya söyleyin.'},
  sq:{title:'Flisni me AGM',description:'Asistent bisedor Premium. Kontrolloni tekstin para dërgimit.',back:'Kthehu te Premium',start:'Nis mikrofonin',stop:'Ndalo mikrofonin',transcript:'Transkripti',transcriptHint:'Mund ta korrigjoni tekstin para konfirmimit.',confirm:'Konfirmo dhe pyet AGM',cancel:'Anulo',listening:'Po dëgjoj. Flisni tani.',processing:'Zëri po transkriptohet.',waiting:'AGM po përgatit përgjigjen.',answer:'Përgjigjja AGM',replay:'Luaj përgjigjen',stopPlayback:'Ndalo luajtjen',microphoneError:'Mikrofoni nuk është i disponueshëm ose leja u refuzua.',transcriptionError:'Zëri nuk mund të transkriptohej.',networkError:'Rrjeti nuk është i disponueshëm.',aiError:'AGM nuk mund të përgjigjet tani.',playbackError:'Përgjigjja mbetet e dukshme, por luajtja zanore nuk është e disponueshme.',textFallback:'Mund ta shkruani pyetjen drejtpërdrejt.',emptyTranscript:'Shkruani ose diktoni një pyetje.'},
};
