import { BadRequestException,Controller,Get,Headers,Post,Query,RawBodyRequest,Req,UnauthorizedException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';import type { Request } from 'express';import { CommunicationService } from './communication.service';import type { InboundCommunication } from './communication.contract';import { parseGmailPush,parseWhatsAppWebhook,verifyHmacSha256 } from './webhook.parsers';
import { GmailCommunicationProvider } from './providers/gmail.provider';
@Controller('webhooks/communications')
export class CommunicationWebhookController{
 constructor(private readonly service:CommunicationService,private readonly config:ConfigService,private readonly gmail:GmailCommunicationProvider){}
 @Get('whatsapp')verifyWhatsApp(@Query('hub.mode')mode:string,@Query('hub.verify_token')token:string,@Query('hub.challenge')challenge:string){if(mode!=='subscribe'||!challenge||token!==this.config.get<string>('WHATSAPP_WEBHOOK_VERIFY_TOKEN'))throw new UnauthorizedException();return challenge;}
 @Post('whatsapp')async whatsapp(@Req()request:RawBodyRequest<Request>,@Headers('x-hub-signature-256')signature?:string){const secret=this.config.get<string>('WHATSAPP_APP_SECRET');const companyId=this.config.get<string>('COMMUNICATION_COMPANY_ID');if(!secret||!companyId)throw new UnauthorizedException();if(!request.rawBody||!verifyHmacSha256(request.rawBody,signature,secret))throw new UnauthorizedException();const parsed=parseWhatsAppWebhook(request.body);for(const message of parsed.inbound)await this.service.ingest(message,companyId);for(const status of parsed.statuses)await this.service.updateStatus({...status,provider:'whatsapp-cloud',channel:'whatsapp'},companyId);return{received:true,inbound:parsed.inbound.length,statuses:parsed.statuses.length};}
 @Post('email')async email(@Req()request:RawBodyRequest<Request>,@Headers('x-agm-signature-256')signature?:string){const secret=this.config.get<string>('EMAIL_INBOUND_WEBHOOK_SECRET');const companyId=this.config.get<string>('COMMUNICATION_COMPANY_ID');if(!secret||!companyId)throw new UnauthorizedException();if(!request.rawBody||!verifyHmacSha256(request.rawBody,signature,secret))throw new UnauthorizedException();const body=request.body as InboundCommunication;if(body.provider!=='gmail'||body.channel!=='email')throw new BadRequestException();return{received:true,message:await this.service.ingest(body,companyId)};}
 @Post('gmail-push')async gmailPush(@Req()request:Request,@Query('token')queryToken?:string,@Headers('x-agm-pubsub-token')headerToken?:string){const expected=this.config.get<string>('GMAIL_PUBSUB_VERIFICATION_TOKEN');const token=headerToken??queryToken;if(!expected||!token||token!==expected)throw new UnauthorizedException();const companyId=this.config.get<string>('COMMUNICATION_COMPANY_ID');if(!companyId)throw new UnauthorizedException();const notification=parseGmailPush(request.body);const eventId=String((request.body as any)?.message?.messageId??notification.historyId);const messages=await this.gmail.readHistory(notification.historyId,eventId);for(const message of messages)await this.service.ingest(message,companyId);return{received:true,historyId:notification.historyId,inbound:messages.length};}
}
