import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { premiumRouteForView, premiumViewFromRoute } from '../src/premium-routes';

assert.equal(premiumRouteForView('carMover'), '/car-mover');
assert.equal(premiumViewFromRoute('/car-mover'), 'carMover');
const premiumApp=readFileSync(resolve(import.meta.dirname,'../src/premium-app.ts'),'utf8');
const main=readFileSync(resolve(import.meta.dirname,'../src/main.ts'),'utf8');
assert.match(premiumApp,/car-mover|carMover/i);
assert.match(main,/bindCarMoverRuntime/);
assert.match(main,/<a href="\/car-mover" data-module="carMover" class="home-action home-action-voice"/);
assert.match(main,/data-global-action="\$\{opensCarMover \? 'car-mover' : 'microphone'\}"/);
assert.match(main,/if \(action === 'car-mover'\)/);
assert.match(main,/isPremiumNavigationAllowed\('carMover'\)/);
assert.match(main,/await restorePremiumAccessForNavigation\(\)/);
assert.match(main,/async function restorePremiumAccessForNavigation\(\)[\s\S]*authenticatedApiFetch\('\/auth\/entitlements'/);
assert.doesNotMatch(main,/async function restorePremiumAccessForNavigation\(\)[\s\S]{0,200}if \(!premiumViewFromRoute/);
const runtime=readFileSync(resolve(import.meta.dirname,'../src/car-mover/car-mover.runtime.ts'),'utf8');
assert.match(runtime,/carMoverClient\.create/);
assert.match(runtime,/carMoverClient\.transition/);
assert.match(runtime,/carMoverClient\.file/);
assert.match(runtime,/carMoverClient\.protocol/);
assert.match(runtime,/protocolForState/);
assert.match(runtime,/crypto\.subtle\.digest\('SHA-256'/);
assert.match(runtime,/auditReferences/);
assert.match(runtime,/evidenceReferences/);
assert.match(runtime,/carMoverClient\.finance/);
assert.match(runtime,/carMoverClient\.invoice/);
assert.match(runtime,/carMoverClient\.sendMessage/);
assert.match(runtime,/carMoverClient\.analyzeOffers/);
assert.match(runtime,/Gmail \/ WhatsApp/);
const client=readFileSync(resolve(import.meta.dirname,'../src/car-mover/car-mover.client.ts'),'utf8');
assert.match(client,/authenticatedApiFetch/);
assert.doesNotMatch(client,/USER_ACCESS_TOKEN_KEY|Authorization:`Bearer/);
assert.doesNotMatch(client,/companyId|tenantId/);
const copy=readFileSync(resolve(import.meta.dirname,'../src/car-mover/car-mover.i18n.ts'),'utf8');
assert.match(copy,/Modul operațional inclus în AGM Premium/);
assert.doesNotMatch(copy,/Car Mover separat|Separate Car Mover|Separater Car-Mover/);
console.log('Car Mover Premium route, lifecycle, accounting, Gmail/WhatsApp, offer analysis and evidence UI: PASS');
