import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { basicLanguageCodes } from '../src/language-registry';
import { renderPremiumAssistantView } from '../src/premium-voice-shell/premium-assistant.view';
import { premiumAssistantUiMessages } from '../src/premium-voice-shell/premium-assistant-ui.i18n';

for(const language of basicLanguageCodes){
  const messages=premiumAssistantUiMessages[language];
  assert.ok(Object.values(messages).every((value)=>value.trim().length>0));
  const html=renderPremiumAssistantView(language,(value)=>value.replaceAll('&','&amp;').replaceAll('<','&lt;'));
  assert.ok(html.includes(`data-language="${language}"`));
  assert.ok(html.includes('data-assistant-transcript'));
  assert.ok(html.includes('data-assistant-confirm'));
  assert.ok(html.includes('data-assistant-response'));
  assert.ok(html.includes('data-assistant-history'));
  assert.ok(html.includes('data-assistant-open-settings'));
  assert.ok(html.includes('data-assistant-latency'));
  assert.ok(html.includes('data-assistant-retry'));
  assert.ok(html.includes('premium-assistant-mic'));
  assert.ok(html.includes(messages.title));
}
const css=readFileSync(new URL('../src/styles.css',import.meta.url),'utf8');
assert.match(css,/\.premium-assistant-view \.premium-module\s*\{\s*grid-template-columns:\s*minmax\(0, 1fr\)/);
assert.match(css,/\.premium-assistant-view \[hidden\]\s*\{\s*display:\s*none !important/);
assert.match(css,/\[data-assistant-history\] li\[data-role="assistant"\]/);
assert.match(css,/--agm-ai-assistant-visual:\s*url\('\/images\/agm-ai-assistant-microphone-v1\.png'\)/);
assert.match(css,/\.premium-assistant-view \.premium-module[\s\S]*background:\s*var\(--agm-ai-glass\)/);
assert.match(css,/\.premium-assistant-view \.premium-assistant-mic/);
const runtime=readFileSync(new URL('../src/premium-voice-shell/premium-assistant.runtime.ts',import.meta.url),'utf8');
assert.match(runtime,/agm\.premium\.assistant\.history\.v1/);
assert.match(runtime,/while\(history\.length>20\)history\.shift\(\)/);
assert.match(runtime,/history:history\.slice\(-4\)/, 'Premium request context must stay bounded for mobile latency');
assert.match(runtime,/sessionStorage\.setItem/);
assert.match(runtime,/async function interruptAndListen\(\)\{const lease=await preemptCurrentTurn\('microphone-restart'\);if\(!isLeaseCurrent\(lease\)\)return;void conversationLoop\(lease\.token\);\}/);
assert.match(runtime,/\['LISTENING','SPEECH_DETECTED','TRANSCRIBING','UNDERSTANDING','PREPARING','SPEAKING'\]\.includes\(session\.state\(\)\)/);
assert.match(runtime,/transcript\.addEventListener\('input',\(\)=>void interruptForNewQuestion\(\)\)/, 'Typing a new question must interrupt the old request or playback');
assert.match(runtime,/session\.markEngineResponse\(result\.timing\)/, 'Premium latency telemetry must separate server and network response time');
assert.match(runtime,/Promise\.allSettled\(\[stopCapture\(\),stopSpeaking\(\)\]\)/, 'A new turn must stop capture and playback atomically');
assert.match(runtime,/activeRequest\?\.abort\(\)/, 'A new turn must abort the prior provider request');
assert.match(runtime,/event\.turnId!==activeTurnId/, 'Stale native playback events must not update the current turn');
assert.match(runtime,/globalCancellationBarrier/, 'Turn cancellation must be serialized across runtime rebinds');
assert.match(runtime,/recordStaleEvent\(turnId,'model-response'\)/, 'A delayed model response must be recorded and suppressed');
assert.match(runtime,/cancelRecognitionPromise/, 'Browser STT cancellation must settle the abandoned recognition promise');
assert.match(runtime,/audioQueueFlushed/, 'Barge-in evidence must include an audio queue flush receipt');
assert.match(runtime,/window\.addEventListener\('offline'/, 'Premium must explain mobile connectivity loss');
assert.match(runtime,/NativeAudio\.openAppSettings\(\)/, 'Denied Android microphone permission must offer app settings');
assert.match(runtime,/timedOut=true;controller\.abort\(\)/, 'Timeout must be distinguished from user interruption');
assert.match(runtime,/retryText=confirmedText/, 'Failed requests must support explicit manual retry');
assert.doesNotMatch(runtime,/if\(timedOut\).*processTranscript/, 'Timeout must never trigger automatic duplicate retry');
assert.match(runtime,/kind:'stt-terminal-error'/, 'A native no-match error must be observable in telemetry');
assert.match(runtime,/session\.off\(\);toggle\.setAttribute\('aria-pressed','false'\);status\.textContent=errorText;\s*return;/, 'A native no-match error must stop hands-free instead of blinking in an automatic retry loop');
assert.doesNotMatch(runtime,/transcriptionError;await new Promise\(resolve=>setTimeout\(resolve,700\)\)/, 'STT errors must not relaunch recognition automatically');
const nativeAudio=readFileSync(new URL('../android/app/src/main/java/com/agm/cockpit/AgmAudioPlugin.java',import.meta.url),'utf8');
assert.match(nativeAudio,/public void stopSpeaking[\s\S]*stopSpeakingImmediately\(\)/, 'Interrupted Android playback must use the immediate native queue flush path');
assert.match(nativeAudio,/onBeginningOfSpeech\(\)[\s\S]*stopSpeakingImmediately\(\)/, 'Native speech detection must defensively stop stale playback');
assert.match(nativeAudio,/oldAudioStopLatencyMs/, 'Native barge-in must expose the measured audio-stop latency');
assert.match(nativeAudio,/AGM_ENDPOINT_TIMEOUT_MS = 1600L/, 'Android endpointing must preserve a natural pause after recognized text');
assert.match(nativeAudio,/hasRecognizedPartialText && speechStartedAt > 0/, 'Raw Android VAD/noise must not rearm the AGM endpoint timer');
assert.match(nativeAudio,/hasRecognizedPartialText = true;[\s\S]*armEndpointTimer\(\)/, 'AGM endpointing must require real partial recognition text');
const beginningOfSpeech=nativeAudio.match(/onBeginningOfSpeech\(\)[\s\S]*?onEndOfSpeech\(\)/)?.[0]??'';
assert.doesNotMatch(beginningOfSpeech,/armEndpointTimer\(\)/, 'False Android onBeginningOfSpeech callbacks must not close recognition');
console.log('Premium assistant Android-first UI render/i18n 12/12 PASS');
