import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { premiumRouteForView, premiumViewFromRoute } from '../src/premium-routes';

assert.equal(premiumRouteForView('carMover'), '/car-mover');
assert.equal(premiumViewFromRoute('/car-mover'), 'carMover');
const premiumApp=readFileSync(resolve(import.meta.dirname,'../src/premium-app.ts'),'utf8');
const main=readFileSync(resolve(import.meta.dirname,'../src/main.ts'),'utf8');
assert.match(premiumApp,/car-mover|carMover/i);
assert.match(main,/bindCarMoverRuntime/);
const runtime=readFileSync(resolve(import.meta.dirname,'../src/car-mover/car-mover.runtime.ts'),'utf8');
assert.match(runtime,/carMoverClient\.create/);
assert.match(runtime,/carMoverClient\.transition/);
assert.match(runtime,/carMoverClient\.file/);
assert.match(runtime,/carMoverClient\.protocol/);
assert.match(runtime,/protocolForState/);
assert.match(runtime,/crypto\.subtle\.digest\('SHA-256'/);
assert.match(runtime,/auditReferences/);
assert.match(runtime,/evidenceReferences/);
assert.doesNotMatch(runtime,/Onlogist|MOCCA|WhatsApp|Gmail|invoice|payment/i);
const client=readFileSync(resolve(import.meta.dirname,'../src/car-mover/car-mover.client.ts'),'utf8');
assert.match(client,/USER_ACCESS_TOKEN_KEY/);
assert.match(client,/Authorization:`Bearer/);
assert.doesNotMatch(client,/companyId|tenantId/);
console.log('Car Mover Premium route, lifecycle, takeover/handover and evidence UI: PASS');
