import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { basicLanguageCodes } from '../src/language-registry';
import { createOperationalCase, transitionOperationalCase } from '../src/premium-situation-router/operational-case.machine';
import { fieldBatchCopy } from '../src/premium-situation-router/field-batch.i18n';
import { enqueueFieldBatchTransition, flushFieldBatch, pendingFieldBatch } from '../src/premium-situation-router/field-batch.sync';
import { authorizedSituationRegistry } from '../src/premium-situation-router/situation.registry';
import type { FieldBatchSituationId } from '../src/premium-situation-router/situation-router.types';

const ids:FieldBatchSituationId[]=['trip-context','vehicle-safety','load-securing','tachograph-time','adr-compliance','route-compatibility','night-weather','driver-fitness','ready-gate'];
assert.equal(ids.length,9);for(const id of ids){assert.equal(authorizedSituationRegistry[id].hub,'BEFORE_DEPARTURE');assert.deepEqual(authorizedSituationRegistry[id].steps,['qualify','verify','remediate','verdict']);}
for(const language of basicLanguageCodes){const copy=fieldBatchCopy[language];assert.deepEqual(Object.keys(copy.situations),ids);for(const id of ids){assert.ok(copy.situations[id].title.trim());assert.ok(copy.situations[id].focus.trim());}for(const key of ['batch','choose','check','evidence','remediation','confirm','syncPending','recovery'] as const)assert.ok(copy[key].trim(),`${language}.${key}`);}
for(const id of ids){let value=createOperationalCase(`case-${id}`,id,'ro');value=transitionOperationalCase(value,{type:'SET_DATA',values:{answers:{condition:'confirmed',evidence:'confirmed',remediation:'confirmed'},humanConfirmed:true,verdict:'READY_CONFIRMED'}});value=transitionOperationalCase(value,{type:'SET_DISPOSITION',disposition:'RESOLVED'});assert.equal(value.state,'RESOLVED');assert.equal(value.data.verdict,'READY_CONFIRMED');}
let blocked=createOperationalCase('blocked','vehicle-safety','ro');blocked=transitionOperationalCase(blocked,{type:'SET_DATA',values:{severity:'blocking',verdict:'BLOCKED'}});blocked=transitionOperationalCase(blocked,{type:'BLOCK'});assert.equal(blocked.state,'BLOCKED');
let follow=createOperationalCase('follow','night-weather','ro');follow=transitionOperationalCase(follow,{type:'SET_DISPOSITION',disposition:'FOLLOW_UP_REQUIRED'});assert.equal(follow.state,'FOLLOW_UP_REQUIRED');let escalated=createOperationalCase('escalated','adr-compliance','ro');escalated=transitionOperationalCase(escalated,{type:'SET_DISPOSITION',disposition:'ESCALATED'});assert.equal(escalated.state,'ESCALATED');
const values=new Map<string,string>();const storage={getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>void values.set(key,value),removeItem:(key:string)=>void values.delete(key)};
let offline=createOperationalCase('offline','route-compatibility','sq');offline=transitionOperationalCase(offline,{type:'SET_DATA',values:{answers:{condition:'confirmed'},syncStatus:'SYNC_PENDING'}});await enqueueFieldBatchTransition(storage as Storage,offline,false);offline=transitionOperationalCase(offline,{type:'SET_DATA',values:{answers:{condition:'confirmed',evidence:'confirmed'},syncStatus:'SYNC_PENDING'}});await enqueueFieldBatchTransition(storage as Storage,offline,false);assert.deepEqual((await pendingFieldBatch(storage as Storage)).map(event=>event.payload.caseRevision),[1,2]);
let calls=0;const server={async sync(items:any[]){calls++;return{results:items.map(({event}:any)=>({eventId:event.eventId,status:'acknowledged',serverVersion:event.aggregateVersion})),projections:[]};},async read(){return{serverVersion:0,events:[],projection:null};}};assert.equal((await flushFieldBatch({storage:storage as Storage,server})).status,'synchronized');assert.equal((await pendingFieldBatch(storage as Storage)).length,0);assert.equal((await flushFieldBatch({storage:storage as Storage,server})).status,'idle');assert.equal(calls,1);
const source=readFileSync(new URL('../src/premium-situation-router/field-batch.component.ts',import.meta.url),'utf8');assert.doesNotMatch(source,/MARK_SENT|RECORD_RECEIPT/);assert.doesNotMatch(source,/incident|breakdown|fatigue/);assert.match(source,/IDS\.indexOf\(this\.active\)\+1\}\/9/);
console.log('Field Test Batch 01: situations 9/9, state outcomes, i18n 9/9, offline/outbox/reconnect/dedup and no auto-send PASS');
