import assert from 'node:assert/strict';
import { CapabilityBroker } from '../src/premium-capabilities/capability.broker';
import { ActionConfirmationStore } from '../src/premium-capabilities/action-confirmation';
import { capabilityLanguages, capabilityText } from '../src/premium-capabilities/capability.i18n';
import { slice1Enabled } from '../src/premium-capabilities/capability.registry';
import { createActionPreview, previewChanged } from '../src/premium-capabilities/action-preview';
const scope={productId:'agm-cockpit' as const,moduleId:'premium-copilot',tenantId:'tenant-a',subjectId:'user-a',premiumEntitled:true,conversationId:'c1',requestedAt:'2026-08-12T10:00:00.000Z'};
const broker=new CapabilityBroker();
assert.equal((await broker.prepare({...scope,requestId:'unknown',capabilityId:'CAMERA',parameters:{}})).status,'DENIED');
assert.equal((await broker.prepare({...scope,premiumEntitled:false,requestId:'no-entitlement',capabilityId:'OPEN_DIALER',parameters:{phoneNumber:'+49123456'}})).status,'DENIED');
assert.equal((await broker.prepare({...scope,requestId:'missing-phone',capabilityId:'OPEN_DIALER',parameters:{}})).status,'NEEDS_INPUT');
const dial=await broker.prepare({...scope,requestId:'dial-1',capabilityId:'OPEN_DIALER',parameters:{phoneNumber:'+49 123 456',displayName:'Mihai'}});assert.equal(dial.status,'PREVIEW_READY');if(dial.status!=='PREVIEW_READY')throw 0;
assert.equal((await broker.prepare({...scope,requestId:'dial-1',capabilityId:'OPEN_DIALER',parameters:{phoneNumber:'+49 123 456'}})).status,'DENIED');
const store=new ActionConfirmationStore();store.setPreview(dial.preview);
assert.equal(store.confirm({confirmationId:'wrong',previewVersion:1,contentHash:dial.preview.contentHash,method:'VOICE'}).status,'DENIED');
const confirmed=store.confirm({confirmationId:dial.preview.confirmationId,previewVersion:dial.preview.previewVersion,contentHash:dial.preview.contentHash,method:'VOICE'});assert.equal(confirmed.status,'CONFIRMED');
assert.ok(store.consume(dial.preview));assert.equal(store.consume(dial.preview),undefined);
assert.equal((await broker.prepare({...scope,requestId:'maps-missing',capabilityId:'OPEN_MAPS',parameters:{}})).status,'NEEDS_INPUT');
assert.equal((await broker.prepare({...scope,requestId:'maps-unverified',capabilityId:'OPEN_MAPS',parameters:{destination:'Example service',grounded:false}})).status,'DENIED');
assert.equal((await broker.prepare({...scope,requestId:'maps-1',capabilityId:'OPEN_MAPS',parameters:{destination:'Heilbronn',grounded:true}})).status,'PREVIEW_READY');
assert.ok(broker.auditSnapshot().every(e=>!JSON.stringify(e).includes('+49 123 456')));
assert.equal(capabilityLanguages.length,9);for(const language of capabilityLanguages)for(const key of ['title','dial','maps','confirm','cancel','opened','failed','unavailable','needPhone','needDestination','denied','expired'] as const)assert.ok(capabilityText(language,key,{name:'M',value:'V'}).trim());
assert.equal(slice1Enabled({getItem:()=>null}),true);assert.equal(slice1Enabled({getItem:()=> 'false'}),false);
const changed=await createActionPreview({...scope,requestId:'dial-1-revised',capabilityId:'OPEN_DIALER',parameters:{phoneNumber:'+49 999 999',displayName:'Mihai'}},dial.preview.previewVersion+1);assert.equal(previewChanged(dial.preview,changed),true);assert.notEqual(dial.preview.contentHash,changed.contentHash);assert.equal(changed.previewVersion,2);
const expiredStore=new ActionConfirmationStore();expiredStore.setPreview({...dial.preview,expiresAt:'2026-08-12T09:59:59.000Z'});assert.equal(expiredStore.confirm({confirmationId:dial.preview.confirmationId,previewVersion:1,contentHash:dial.preview.contentHash,method:'TOUCH'},new Date('2026-08-12T10:00:00.000Z')).status,'DENIED');
console.log('AGMA Wave 2A Slice 1 contract tests PASS');
