import assert from'node:assert/strict';import{ConversationalPublicWebUse,type PublicWebFact}from'../src/external-capabilities/conversational-public-web-use';
const c=new ConversationalPublicWebUse(),official='https://www.bahn.de/hilfe/telefon',imprint='https://www.deutschebahn.com/de/impressum-6898126';
const phone=await c.answer('Găsește-mi telefonul Deutsche Bahn',async()=>[{entity:'Deutsche Bahn',kind:'PHONE',value:'+49 30 2970',url:official,official:true}]);assert.equal(phone.status,'GROUNDED');assert.match(phone.answer,/\+49 30 2970/);assert.equal(phone.receiptIds.length,1);
const addressHours=await c.answer('Găsește adresa și programul Deutsche Bahn',async()=>[{entity:'Deutsche Bahn',kind:'ADDRESS',value:'Potsdamer Platz 2, 10785 Berlin',url:imprint,official:true},{entity:'Deutsche Bahn',kind:'HOURS',value:'Mo-Su 08:00-20:00 pentru suportul indicat',url:'https://www.bahn.de/faq/pk/service',official:true}]);assert.equal(addressHours.status,'GROUNDED');assert.equal(addressHours.sources.length,2);
const ambiguous=await c.answer('Telefonul firmei Atlas',async()=>[{entity:'Atlas A',kind:'PHONE',value:'1',url:'https://a.example',official:false},{entity:'Atlas B',kind:'PHONE',value:'2',url:'https://b.example',official:false}]);assert.equal(ambiguous.status,'CLARIFICATION_REQUIRED');
const conflicting=await c.answer('Telefon Deutsche Bahn',async()=>[{entity:'Deutsche Bahn',kind:'PHONE',value:'030 2970',url:official,official:true},{entity:'Deutsche Bahn',kind:'PHONE',value:'030 0000',url:'https://directory.example/db',official:false}]);assert.equal(conflicting.status,'CONFLICT');assert.match(conflicting.answer,/valori diferite/);
const login=await c.answer('Caută în cont',async()=>[{entity:'X',kind:'ADDRESS',value:'x',url:'https://example.com/login',official:true}]);assert.equal(login.status,'STOP_AUTH_REQUIRED');
const write=await c.answer('Rezervă serviciul găsit',async()=>[]);assert.equal(write.status,'WRITE_PREVIEW');assert.ok(write.preview);assert.equal(write.receiptIds.length,0);
assert.doesNotMatch(JSON.stringify({phone,addressHours,ambiguous,conflicting}),/xoxb-|bearer|credential|api[_-]?key/i);console.log('AGM COPILOT CONVERSATIONAL AUTONOMOUS PUBLIC WEB USE - PASS');
