import assert from'node:assert/strict';import{mkdir,writeFile}from'node:fs/promises';import path from'node:path';import{ExternalCapabilityPermissionRegistry,type ExternalPermissionRequest}from'../src/external-capabilities/external-capability.policy';import{ExternalCapabilityExecutor,type ControlledExternalAdapter}from'../src/external-capabilities/external-capability.executor';
const key=process.env.OPENAI_API_KEY;if(!key)throw new Error('OPENAI_API_KEY_NOT_CONFIGURED');const registry=new ExternalCapabilityPermissionRegistry(),executor=new ExternalCapabilityExecutor(registry,15_000,1);const base:ExternalPermissionRequest={requestId:crypto.randomUUID(),capabilityId:'OPENAI_MODELS_READ',provider:'OPENAI',domain:'api.openai.com',action:'LIST_MODELS',access:'READ',scope:'models.metadata',entitlement:'premium.voice-assistant',actorId:'wave3b-owner-pilot',tenantId:'tenant:owner',expectedTenantId:'tenant:owner',requestedAt:new Date().toISOString()};
const realAdapter:ControlledExternalAdapter={invoke:async(_request,signal)=>{const response=await fetch('https://api.openai.com/v1/models',{method:'GET',headers:{Authorization:`Bearer ${key}`},signal,cache:'no-store'});if(!response.ok)throw new Error(`OPENAI_MODELS_READ_FAILED:${response.status}`);const body=await response.json() as{object?:string;data?:Array<{id?:string;object?:string;created?:number;owned_by?:string}>};return{object:body.object,modelCount:body.data?.length??0,providerRecordTypes:[...new Set((body.data??[]).map(item=>item.object).filter(Boolean))]};}};
const results=[];const real=await executor.execute(base,realAdapter);assert.equal(real.status,'SUCCESS');assert.ok((real.data as{modelCount:number}).modelCount>0);results.push({id:'real-provider-authorized-read',status:'PASS',provider:'OPENAI',result:real.data,receipt:real.receipt});
for(const [id,request,reason]of[['unauthorized-read',{...base,requestId:crypto.randomUUID(),capabilityId:'UNREGISTERED_READ'},'CAPABILITY_NOT_REGISTERED'],['provider-not-allowlisted',{...base,requestId:crypto.randomUUID(),provider:'OTHER',domain:'other.example'},'PROVIDER_DOMAIN_OR_ACTION_NOT_ALLOWLISTED'],['wrong-tenant',{...base,requestId:crypto.randomUUID(),tenantId:'tenant:other'},'TENANT_ISOLATION_VIOLATION']]as const){const decision=registry.evaluate(request);assert.equal(decision.status,'DENIED');assert.equal(decision.reason,reason);results.push({id,status:'PASS',receipt:decision.receipt});}
registry.revoke('OPENAI_MODELS_READ');const revoked=registry.evaluate({...base,requestId:crypto.randomUUID()});assert.equal(revoked.reason,'PERMISSION_REVOKED_OR_DISABLED');results.push({id:'revocation-immediate',status:'PASS',receipt:revoked.receipt});registry.restore('OPENAI_MODELS_READ');
const timeoutExecutor=new ExternalCapabilityExecutor(registry,10,1),timeout=await timeoutExecutor.execute({...base,requestId:crypto.randomUUID()},{invoke:async()=>new Promise(()=>{})});assert.equal(timeout.status,'TIMEOUT');assert.equal(timeout.receipt.reason,'SAFE_FALLBACK_STATUS_UNKNOWN');results.push({id:'provider-timeout-safe-fallback',status:'PASS',receipt:timeout.receipt});
const serialized=JSON.stringify(results);assert.doesNotMatch(serialized,new RegExp(key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.doesNotMatch(serialized,/bearer\s+|api[_-]?key|access[_-]?token/i);assert.ok(results.every(item=>item.receipt?.receiptId&&item.receipt?.actorId&&item.receipt?.tenantId&&item.receipt?.provider&&item.receipt?.occurredAt));
const runId=new Date().toISOString().replace(/[:.]/g,'-'),out=path.resolve(process.cwd(),'..','..','evidence','agma-wave3b','provider',runId);await mkdir(out,{recursive:true});const report={schemaVersion:1,runId,status:'PASS',provider:'OPENAI',capabilityId:'OPENAI_MODELS_READ',access:'READ',endpoint:'https://api.openai.com/v1/models',production:'UNCHANGED',secretExposure:'ZERO',results,finishedAt:new Date().toISOString()};await writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log('AGMA Wave 3B real OpenAI READ provider pilot PASS');console.log(path.join(out,'report.json'));
