import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{externalCapabilityRegistry}from'../src/external-capabilities/external-capability.registry';import{ExternalCapabilityPermissionRegistry,sanitizeExternalValue,type ExternalPermissionRequest}from'../src/external-capabilities/external-capability.policy';import{ExternalCapabilityExecutor}from'../src/external-capabilities/external-capability.executor';
assert.ok(externalCapabilityRegistry.size>=4);for(const requiredId of['OPENAI_MODELS_READ','GMAIL_MESSAGE_STATUS_READ','GMAIL_COMPOSE_HANDOFF','WHATSAPP_HANDOFF'] as const)assert.ok(externalCapabilityRegistry.has(requiredId));for(const item of externalCapabilityRegistry.values()){assert.ok(item.id&&item.provider&&item.access&&item.scopes.length&&item.requiredEntitlement&&item.state&&item.allowedActions.length&&item.allowedDomains.length&&item.auditRule);assert.equal(item.access==='WRITE',item.confirmationRequired)}
const registry=new ExternalCapabilityPermissionRegistry(),base:ExternalPermissionRequest={requestId:'read-1',capabilityId:'GMAIL_MESSAGE_STATUS_READ',provider:'GMAIL',domain:'gmail.googleapis.com',action:'READ_STATUS',access:'READ',scope:'message.status',entitlement:'premium.voice-assistant',actorId:'user-a',tenantId:'tenant-a',expectedTenantId:'tenant-a',requestedAt:new Date().toISOString()};
const receipts=[];const check=(decision:ReturnType<typeof registry.evaluate>,status:'ALLOWED'|'DENIED',reason?:string)=>{assert.equal(decision.status,status);if(reason)assert.equal(decision.reason,reason);assert.ok(decision.receipt.receiptId&&decision.receipt.occurredAt);receipts.push(decision.receipt)};
check(registry.evaluate(base),'ALLOWED');check(registry.evaluate({...base,requestId:'unknown',capabilityId:'UNREGISTERED'}),'DENIED','CAPABILITY_NOT_REGISTERED');
const write={...base,requestId:'write-1',capabilityId:'GMAIL_COMPOSE_HANDOFF',domain:'local.android.intent',action:'OPEN_COMPOSER',access:'WRITE' as const,scope:'compose.email'};check(registry.evaluate(write),'DENIED','EXPLICIT_CONFIRMATION_REQUIRED');check(registry.evaluate({...write,confirmation:{explicit:true,requestId:'write-1',capabilityId:'GMAIL_COMPOSE_HANDOFF'}}),'ALLOWED');
registry.revoke('GMAIL_MESSAGE_STATUS_READ');check(registry.evaluate({...base,requestId:'revoked'}),'DENIED','PERMISSION_REVOKED_OR_DISABLED');registry.restore('GMAIL_MESSAGE_STATUS_READ');
check(registry.evaluate({...base,requestId:'provider',provider:'EVIL',domain:'evil.test'}),'DENIED','PROVIDER_DOMAIN_OR_ACTION_NOT_ALLOWLISTED');check(registry.evaluate({...base,requestId:'tenant',tenantId:'tenant-b'}),'DENIED','TENANT_ISOLATION_VIOLATION');
const sanitized=sanitizeExternalValue({answer:'Bearer abc.def.ghi',accessToken:'secret-token',nested:{password:'hunter2'},safe:'STATUS_UNKNOWN'});assert.doesNotMatch(JSON.stringify(sanitized),/abc\.def|secret-token|hunter2/);assert.match(JSON.stringify(sanitized),/STATUS_UNKNOWN/);
const executor=new ExternalCapabilityExecutor(registry,10,1);const success=await executor.execute({...base,requestId:'execute-read'}, {invoke:async()=>({status:'PROVIDER_ACCEPTED',token:'secret-provider-token'})});assert.equal(success.status,'SUCCESS');assert.doesNotMatch(JSON.stringify(success),/secret-provider-token/);receipts.push(success.receipt);
let attempts=0;const timeout=await executor.execute({...base,requestId:'timeout'}, {invoke:async()=>{attempts++;return new Promise(()=>{})}});assert.equal(timeout.status,'TIMEOUT');assert.equal(timeout.receipt.reason,'SAFE_FALLBACK_STATUS_UNKNOWN');assert.equal(timeout.receipt.attempts,2);assert.equal(attempts,2);receipts.push(timeout.receipt);
assert.equal(receipts.length,9);assert.ok(receipts.every(receipt=>receipt.actorId&&receipt.tenantId&&receipt.capabilityId&&receipt.provider&&receipt.access&&receipt.result&&receipt.occurredAt));assert.doesNotMatch(JSON.stringify(receipts),/secret|token|credential/i);
const manifest=readFileSync(new URL('../android/app/src/main/AndroidManifest.xml',import.meta.url),'utf8');for(const forbidden of['ACCESS_COARSE_LOCATION','READ_CONTACTS','ACCESS_BACKGROUND_LOCATION','READ_CALL_LOG','READ_SMS','BIND_NOTIFICATION_LISTENER_SERVICE','READ_EXTERNAL_STORAGE'])assert.equal(manifest.includes(forbidden),false);
console.log('AGMA Wave 3A external capability permission foundation tests PASS');


