import type { BasicLanguageCode } from '../language-registry';

const en = {
  title:'AGM Car Mover', subtitle:'Move vehicles on their own wheels', newJob:'New manual job', jobs:'Jobs', vehicleClass:'Vehicle class', vehicleType:'Vehicle type', make:'Make', model:'Model', vin:'VIN (optional)', registration:'Registration (optional)', pickup:'Pickup', destination:'Destination', create:'Create job', refresh:'Refresh', select:'Select', loading:'Loading…', empty:'No Car Mover jobs yet.', jobFile:'Job File', timeline:'Timeline', state:'State', transition:'Next state', apply:'Apply transition', driver:'Driver ID', error:'The operation could not be completed.', saved:'Job created.', isolation:'Separate Car Mover operational space', passenger:'Passenger car', commercial:'Light commercial', van:'Van', truck:'Truck', tractor:'Tractor unit', other:'Other drivable vehicle', back:'Back to Premium', required:'Complete all required fields.', readOnly:'Read-only operational projection', audit:'Audit references', evidence:'Evidence references'
} as const;
type Key=keyof typeof en;
const dictionaries:Record<BasicLanguageCode,Record<Key,string>>={
 en,
 ro:{title:'AGM Car Mover',subtitle:'Mutarea vehiculelor pe roți',newJob:'Job manual nou',jobs:'Joburi',vehicleClass:'Clasa vehiculului',vehicleType:'Tip vehicul',make:'Marcă',model:'Model',vin:'VIN (opțional)',registration:'Înmatriculare (opțional)',pickup:'Preluare',destination:'Destinație',create:'Creează job',refresh:'Actualizează',select:'Selectează',loading:'Se încarcă…',empty:'Nu există încă joburi Car Mover.',jobFile:'Dosar Job',timeline:'Cronologie',state:'Stare',transition:'Starea următoare',apply:'Aplică tranziția',driver:'ID șofer',error:'Operațiunea nu a putut fi finalizată.',saved:'Job creat.',isolation:'Spațiu operațional Car Mover separat',passenger:'Autoturism',commercial:'Utilitară ușoară',van:'Van',truck:'Camion',tractor:'Cap tractor',other:'Alt vehicul deplasabil',back:'Înapoi la Premium',required:'Completați toate câmpurile obligatorii.',readOnly:'Proiecție operațională read-only',audit:'Referințe audit',evidence:'Referințe dovezi'},
 de:{title:'AGM Car Mover',subtitle:'Fahrzeuge auf eigenen Rädern bewegen',newJob:'Neuer manueller Auftrag',jobs:'Aufträge',vehicleClass:'Fahrzeugklasse',vehicleType:'Fahrzeugtyp',make:'Marke',model:'Modell',vin:'FIN (optional)',registration:'Kennzeichen (optional)',pickup:'Abholung',destination:'Ziel',create:'Auftrag erstellen',refresh:'Aktualisieren',select:'Auswählen',loading:'Wird geladen…',empty:'Noch keine Car-Mover-Aufträge.',jobFile:'Auftragsakte',timeline:'Zeitleiste',state:'Status',transition:'Nächster Status',apply:'Übergang anwenden',driver:'Fahrer-ID',error:'Der Vorgang konnte nicht abgeschlossen werden.',saved:'Auftrag erstellt.',isolation:'Separater Car-Mover-Arbeitsbereich',passenger:'Pkw',commercial:'Leichtes Nutzfahrzeug',van:'Van',truck:'Lkw',tractor:'Sattelzugmaschine',other:'Anderes fahrbares Fahrzeug',back:'Zurück zu Premium',required:'Alle Pflichtfelder ausfüllen.',readOnly:'Schreibgeschützte Betriebsansicht',audit:'Audit-Referenzen',evidence:'Nachweisreferenzen'},
 fr:{...en,title:'AGM Car Mover',subtitle:'Déplacement de véhicules sur leurs propres roues',newJob:'Nouvelle mission manuelle',jobs:'Missions',vehicleClass:'Classe du véhicule',vehicleType:'Type de véhicule',make:'Marque',model:'Modèle',pickup:'Enlèvement',destination:'Destination',create:'Créer la mission',refresh:'Actualiser',select:'Sélectionner',loading:'Chargement…',empty:'Aucune mission Car Mover.',jobFile:'Dossier mission',timeline:'Chronologie',state:'État',apply:'Appliquer la transition',error:'L’opération n’a pas pu être terminée.',saved:'Mission créée.',passenger:'Voiture',commercial:'Utilitaire léger',truck:'Camion',tractor:'Tracteur routier',other:'Autre véhicule roulant',back:'Retour à Premium',required:'Remplissez tous les champs obligatoires.'},
 nl:{...en,title:'AGM Car Mover',subtitle:'Voertuigen op eigen wielen verplaatsen',newJob:'Nieuwe handmatige opdracht',jobs:'Opdrachten',vehicleClass:'Voertuigklasse',vehicleType:'Voertuigtype',make:'Merk',pickup:'Ophalen',destination:'Bestemming',create:'Opdracht maken',refresh:'Vernieuwen',select:'Selecteren',loading:'Laden…',empty:'Nog geen Car Mover-opdrachten.',jobFile:'Opdrachtdossier',timeline:'Tijdlijn',state:'Status',apply:'Overgang toepassen',error:'De bewerking kon niet worden voltooid.',saved:'Opdracht gemaakt.',passenger:'Personenauto',commercial:'Licht bedrijfsvoertuig',truck:'Vrachtwagen',tractor:'Trekker',other:'Ander rijdbaar voertuig',back:'Terug naar Premium',required:'Vul alle verplichte velden in.'},
 ru:{...en,title:'AGM Car Mover',subtitle:'Перемещение транспортных средств своим ходом',newJob:'Новое ручное задание',jobs:'Задания',vehicleClass:'Класс ТС',vehicleType:'Тип ТС',make:'Марка',model:'Модель',pickup:'Место получения',destination:'Пункт назначения',create:'Создать задание',refresh:'Обновить',select:'Выбрать',loading:'Загрузка…',empty:'Заданий Car Mover пока нет.',jobFile:'Досье задания',timeline:'Хронология',state:'Статус',apply:'Применить переход',error:'Не удалось завершить операцию.',saved:'Задание создано.',passenger:'Легковой автомобиль',commercial:'Лёгкий коммерческий',van:'Фургон',truck:'Грузовик',tractor:'Тягач',other:'Другое самоходное ТС',back:'Назад в Premium',required:'Заполните все обязательные поля.'},
 pl:{...en,title:'AGM Car Mover',subtitle:'Przemieszczanie pojazdów na własnych kołach',newJob:'Nowe zlecenie ręczne',jobs:'Zlecenia',vehicleClass:'Klasa pojazdu',vehicleType:'Typ pojazdu',make:'Marka',model:'Model',pickup:'Odbiór',destination:'Cel',create:'Utwórz zlecenie',refresh:'Odśwież',select:'Wybierz',loading:'Ładowanie…',empty:'Brak zleceń Car Mover.',jobFile:'Akta zlecenia',timeline:'Oś czasu',state:'Stan',apply:'Zastosuj przejście',error:'Nie udało się zakończyć operacji.',saved:'Zlecenie utworzone.',passenger:'Samochód osobowy',commercial:'Lekki pojazd użytkowy',van:'Van',truck:'Ciężarówka',tractor:'Ciągnik siodłowy',other:'Inny pojazd jezdny',back:'Powrót do Premium',required:'Uzupełnij wszystkie wymagane pola.'},
 tr:{...en,title:'AGM Car Mover',subtitle:'Araçları kendi tekerlekleri üzerinde taşıma',newJob:'Yeni manuel iş',jobs:'İşler',vehicleClass:'Araç sınıfı',vehicleType:'Araç tipi',make:'Marka',model:'Model',pickup:'Teslim alma',destination:'Varış',create:'İş oluştur',refresh:'Yenile',select:'Seç',loading:'Yükleniyor…',empty:'Henüz Car Mover işi yok.',jobFile:'İş dosyası',timeline:'Zaman çizelgesi',state:'Durum',apply:'Geçişi uygula',error:'İşlem tamamlanamadı.',saved:'İş oluşturuldu.',passenger:'Binek otomobil',commercial:'Hafif ticari',van:'Van',truck:'Kamyon',tractor:'Çekici',other:'Diğer sürülebilir araç',back:'Premium’a dön',required:'Tüm zorunlu alanları doldurun.'},
 sq:{...en,title:'AGM Car Mover',subtitle:'Lëvizja e mjeteve mbi rrotat e tyre',newJob:'Punë e re manuale',jobs:'Punët',vehicleClass:'Klasa e mjetit',vehicleType:'Lloji i mjetit',make:'Marka',model:'Modeli',pickup:'Marrja',destination:'Destinacioni',create:'Krijo punën',refresh:'Rifresko',select:'Zgjidh',loading:'Duke ngarkuar…',empty:'Nuk ka ende punë Car Mover.',jobFile:'Dosja e punës',timeline:'Kronologjia',state:'Gjendja',apply:'Zbato kalimin',error:'Veprimi nuk mund të përfundohej.',saved:'Puna u krijua.',passenger:'Vetura',commercial:'Mjet i lehtë komercial',van:'Furgon',truck:'Kamion',tractor:'Kokë tërheqëse',other:'Mjet tjetër i drejtueshëm',back:'Kthehu te Premium',required:'Plotësoni të gjitha fushat e detyrueshme.'}
};
export function carMoverText(language:BasicLanguageCode,key:Key){return dictionaries[language][key];}
export const carMoverI18nKeys=Object.keys(en) as Key[];

