import type { BasicLanguageCode } from '../language-registry';
const text={
 ro:{title:'Confirmă acțiunea',dial:'Deschid dialerul pentru {name} — {value}',maps:'Deschid navigația către {value}',confirm:'Confirmă',cancel:'Anulează',opened:'Aplicația Android a fost deschisă. Acțiunea finală rămâne sub controlul tău.',failed:'Acțiunea nu a putut fi deschisă.',unavailable:'Nu există o aplicație disponibilă pentru această acțiune.',needPhone:'Spune sau introdu numărul de telefon.',needDestination:'Spune sau introdu destinația.',denied:'Acțiunea a fost refuzată în siguranță.',expired:'Preview-ul a expirat. Pregătește acțiunea din nou.'},
 de:{title:'Aktion bestätigen',dial:'Wählfeld für {name} öffnen — {value}',maps:'Navigation nach {value} öffnen',confirm:'Bestätigen',cancel:'Abbrechen',opened:'Die Android-App wurde geöffnet. Die endgültige Aktion bleibt unter Ihrer Kontrolle.',failed:'Die Aktion konnte nicht geöffnet werden.',unavailable:'Für diese Aktion ist keine App verfügbar.',needPhone:'Bitte Telefonnummer nennen oder eingeben.',needDestination:'Bitte Ziel nennen oder eingeben.',denied:'Die Aktion wurde sicher abgelehnt.',expired:'Die Vorschau ist abgelaufen. Bereiten Sie die Aktion erneut vor.'},
 en:{title:'Confirm action',dial:'Open the dialer for {name} — {value}',maps:'Open navigation to {value}',confirm:'Confirm',cancel:'Cancel',opened:'The Android app was opened. The final action remains under your control.',failed:'The action could not be opened.',unavailable:'No app is available for this action.',needPhone:'Say or enter the phone number.',needDestination:'Say or enter the destination.',denied:'The action was safely denied.',expired:'The preview expired. Prepare the action again.'},
 fr:{title:'Confirmer l’action',dial:'Ouvrir le composeur pour {name} — {value}',maps:'Ouvrir la navigation vers {value}',confirm:'Confirmer',cancel:'Annuler',opened:'L’application Android a été ouverte. L’action finale reste sous votre contrôle.',failed:'Impossible d’ouvrir l’action.',unavailable:'Aucune application n’est disponible pour cette action.',needPhone:'Indiquez ou saisissez le numéro de téléphone.',needDestination:'Indiquez ou saisissez la destination.',denied:'L’action a été refusée en toute sécurité.',expired:'L’aperçu a expiré. Préparez à nouveau l’action.'},
 nl:{title:'Actie bevestigen',dial:'Kiezer openen voor {name} — {value}',maps:'Navigatie openen naar {value}',confirm:'Bevestigen',cancel:'Annuleren',opened:'De Android-app is geopend. De uiteindelijke actie blijft onder uw controle.',failed:'De actie kon niet worden geopend.',unavailable:'Er is geen app beschikbaar voor deze actie.',needPhone:'Noem of voer het telefoonnummer in.',needDestination:'Noem of voer de bestemming in.',denied:'De actie is veilig geweigerd.',expired:'Het voorbeeld is verlopen. Bereid de actie opnieuw voor.'},
 ru:{title:'Подтвердите действие',dial:'Открыть набор номера для {name} — {value}',maps:'Открыть навигацию до {value}',confirm:'Подтвердить',cancel:'Отмена',opened:'Приложение Android открыто. Окончательное действие остаётся под вашим контролем.',failed:'Не удалось открыть действие.',unavailable:'Нет доступного приложения для этого действия.',needPhone:'Назовите или введите номер телефона.',needDestination:'Назовите или введите пункт назначения.',denied:'Действие безопасно отклонено.',expired:'Предпросмотр истёк. Подготовьте действие снова.'},
 pl:{title:'Potwierdź działanie',dial:'Otwórz dialer dla {name} — {value}',maps:'Otwórz nawigację do {value}',confirm:'Potwierdź',cancel:'Anuluj',opened:'Aplikacja Android została otwarta. Ostateczne działanie pozostaje pod Twoją kontrolą.',failed:'Nie udało się otworzyć działania.',unavailable:'Brak aplikacji dla tego działania.',needPhone:'Podaj lub wpisz numer telefonu.',needDestination:'Podaj lub wpisz cel.',denied:'Działanie zostało bezpiecznie odrzucone.',expired:'Podgląd wygasł. Przygotuj działanie ponownie.'},
 tr:{title:'İşlemi onayla',dial:'{name} için arama ekranını aç — {value}',maps:'{value} için navigasyonu aç',confirm:'Onayla',cancel:'İptal',opened:'Android uygulaması açıldı. Son işlem sizin kontrolünüzde kalır.',failed:'İşlem açılamadı.',unavailable:'Bu işlem için kullanılabilir uygulama yok.',needPhone:'Telefon numarasını söyleyin veya girin.',needDestination:'Hedefi söyleyin veya girin.',denied:'İşlem güvenli şekilde reddedildi.',expired:'Önizleme süresi doldu. İşlemi yeniden hazırlayın.'},
 sq:{title:'Konfirmo veprimin',dial:'Hap telefonuesin për {name} — {value}',maps:'Hap navigimin drejt {value}',confirm:'Konfirmo',cancel:'Anulo',opened:'Aplikacioni Android u hap. Veprimi përfundimtar mbetet nën kontrollin tuaj.',failed:'Veprimi nuk mund të hapej.',unavailable:'Nuk ka aplikacion për këtë veprim.',needPhone:'Thoni ose shkruani numrin e telefonit.',needDestination:'Thoni ose shkruani destinacionin.',denied:'Veprimi u refuzua në mënyrë të sigurt.',expired:'Pamja paraprake skadoi. Përgatiteni përsëri veprimin.'},
 it:{title:'Conferma azione',dial:'Apri il tastierino per {name} — {value}',maps:'Apri la navigazione verso {value}',confirm:'Conferma',cancel:'Annulla',opened:'L’app Android è stata aperta. L’azione finale resta sotto il tuo controllo.',failed:'Impossibile aprire l’azione.',unavailable:'Nessuna app disponibile per questa azione.',needPhone:'Pronuncia o inserisci il numero di telefono.',needDestination:'Pronuncia o inserisci la destinazione.',denied:'L’azione è stata rifiutata in sicurezza.',expired:'L’anteprima è scaduta. Prepara nuovamente l’azione.'},
 es:{title:'Confirmar acción',dial:'Abrir el marcador para {name} — {value}',maps:'Abrir navegación a {value}',confirm:'Confirmar',cancel:'Cancelar',opened:'Se ha abierto la aplicación de Android. La acción final permanece bajo tu control.',failed:'No se pudo abrir la acción.',unavailable:'No hay ninguna aplicación disponible para esta acción.',needPhone:'Di o introduce el número de teléfono.',needDestination:'Di o introduce el destino.',denied:'La acción se rechazó de forma segura.',expired:'La vista previa ha caducado. Prepara de nuevo la acción.'},
 sv:{title:'Bekräfta åtgärden',dial:'Öppna knappsatsen för {name} — {value}',maps:'Öppna navigering till {value}',confirm:'Bekräfta',cancel:'Avbryt',opened:'Android-appen öppnades. Den slutliga åtgärden är fortfarande under din kontroll.',failed:'Åtgärden kunde inte öppnas.',unavailable:'Ingen app är tillgänglig för den här åtgärden.',needPhone:'Säg eller ange telefonnumret.',needDestination:'Säg eller ange destinationen.',denied:'Åtgärden avvisades på ett säkert sätt.',expired:'Förhandsgranskningen har gått ut. Förbered åtgärden igen.'},
} as const;
export type CapabilityTextKey=keyof typeof text.en;
export const capabilityTextKeys=Object.keys(text.en) as CapabilityTextKey[];
export function capabilityText(l:BasicLanguageCode,key:CapabilityTextKey,values:Record<string,string>={}){let result:string=text[l][key];for(const[k,v]of Object.entries(values))result=result.replace(`{${k}}`,v);return result;}
export const capabilityLanguages=Object.keys(text) as BasicLanguageCode[];
