import { type AgentGovernanceRecord } from './agent-governance.contract';
import { monitoringAgentGovernanceRecords } from './monitoring-department';

export type {
  AgentGovernanceRecord,
  AgentGovernanceStatus,
} from './agent-governance.contract';

export const agentGovernanceRegistry: AgentGovernanceRecord[] = [
  ...monitoringAgentGovernanceRecords,
  {
    id: 'p9-copilot-control-plane', code: 'P9', nameKey: 'agentRegistry.codex.name', roleKey: 'agentRegistry.codex.role', responsibilitiesKey: 'agentRegistry.codex.responsibilities', ownerDepartmentId: 'ai-agents', status: 'active', lastValidationKey: 'agentRegistry.codex.validation', lastActivityKey: 'agentRegistry.codex.activity', reliabilityKey: 'agentRegistry.reliability.validated', displayName: 'P9', displayRole: 'Copilot control-plane intern', displayResponsibilities: 'Runtime read-only promovat, proiectat din evidence operațional; Kill Switch și rollback rămân disponibile.',
  },
  {
    id: 'secret-credentials-guardian', code: 'SECRET-CREDENTIALS-GUARDIAN', nameKey: 'agentRegistry.codex.name', roleKey: 'agentRegistry.codex.role', responsibilitiesKey: 'agentRegistry.codex.responsibilities', ownerDepartmentId: 'security-legal', status: 'active', lastValidationKey: 'agentRegistry.codex.validation', lastActivityKey: 'agentRegistry.codex.activity', reliabilityKey: 'agentRegistry.reliability.monitoring', displayName: 'Secret & Credentials Guardian', displayRole: 'Secret lifecycle authority', displayResponsibilities: 'Validates secret references and lifecycle metadata without exposing secret values.',
  },
  {
    id: 'version-custodian', code: 'VERSION-CUSTODIAN', nameKey: 'agentRegistry.codex.name', roleKey: 'agentRegistry.codex.role', responsibilitiesKey: 'agentRegistry.codex.responsibilities', ownerDepartmentId: 'release-operations', status: 'active', lastValidationKey: 'agentRegistry.codex.validation', lastActivityKey: 'agentRegistry.codex.activity', reliabilityKey: 'agentRegistry.reliability.validated', displayName: 'Version Custodian', displayRole: 'Release & traceability control', displayResponsibilities: 'Protects baselines and records branches, commits, checkpoints and deployments.',
  },
  {
    id: 'architecture-inspector', code: 'ARCHITECTURE-INSPECTOR', nameKey: 'agentRegistry.codex.name', roleKey: 'agentRegistry.codex.role', responsibilitiesKey: 'agentRegistry.codex.responsibilities', ownerDepartmentId: 'architecture-platform', status: 'active', lastValidationKey: 'agentRegistry.codex.validation', lastActivityKey: 'agentRegistry.codex.activity', reliabilityKey: 'agentRegistry.reliability.validated', displayName: 'Architecture Inspector', displayRole: 'Architecture & platform inspection', displayResponsibilities: 'Inspects the canonical map and reconciles documentation with implementation without executive authority.',
  },
  {
    id: 'release-operations', code: 'RELEASE-OPERATIONS', nameKey: 'agentRegistry.codex.name', roleKey: 'agentRegistry.codex.role', responsibilitiesKey: 'agentRegistry.codex.responsibilities', ownerDepartmentId: 'release-operations', status: 'active', lastValidationKey: 'agentRegistry.codex.validation', lastActivityKey: 'agentRegistry.codex.activity', reliabilityKey: 'agentRegistry.reliability.validated', displayName: 'Release & Operations', displayRole: 'Production release operations', displayResponsibilities: 'Coordinates release evidence, environment health and rollback readiness.',
  },
  {
    id: 'frontend-experience', code: 'FRONTEND-EXPERIENCE', nameKey: 'agentRegistry.codex.name', roleKey: 'agentRegistry.codex.role', responsibilitiesKey: 'agentRegistry.codex.responsibilities', ownerDepartmentId: 'frontend-experience', status: 'active', lastValidationKey: 'agentRegistry.codex.validation', lastActivityKey: 'agentRegistry.codex.activity', reliabilityKey: 'agentRegistry.reliability.validated', displayName: 'Frontend Experience', displayRole: 'Browser and Android experience', displayResponsibilities: 'Maintains the validated user interface and responsive behavior.',
  },
  {
    id: 'website-content-visual-guardian', code: 'WEBSITE-CONTENT-VISUAL-GUARDIAN', nameKey: 'agentRegistry.codex.name', roleKey: 'agentRegistry.codex.role', responsibilitiesKey: 'agentRegistry.codex.responsibilities', ownerDepartmentId: 'frontend-experience', status: 'active', lastValidationKey: 'agentRegistry.codex.validation', lastActivityKey: 'agentRegistry.codex.activity', reliabilityKey: 'agentRegistry.reliability.validated', displayName: 'Website Content & Visual Guardian', displayRole: 'Website content, visual and i18n assurance', displayResponsibilities: 'Reviews visual identity, content accuracy, language presentation, responsive behavior, branding and stale public claims; runtime and infrastructure remain outside its authority.',
  },
  {
    id: 'website-runtime-release-guardian', code: 'WEBSITE-RUNTIME-RELEASE-GUARDIAN', nameKey: 'agentRegistry.codex.name', roleKey: 'agentRegistry.codex.role', responsibilitiesKey: 'agentRegistry.codex.responsibilities', ownerDepartmentId: 'release-operations', status: 'active', lastValidationKey: 'agentRegistry.codex.validation', lastActivityKey: 'agentRegistry.codex.activity', reliabilityKey: 'agentRegistry.reliability.validated', displayName: 'Website Runtime & Release Guardian', displayRole: 'Website runtime and release assurance', displayResponsibilities: 'Monitors website build, public routes, deploy, redirects, assets, health and post-deploy regressions; editorial product claims remain outside its authority.',
  },
  {
    id: 'backend-infrastructure', code: 'BACKEND-INFRASTRUCTURE', nameKey: 'agentRegistry.codex.name', roleKey: 'agentRegistry.codex.role', responsibilitiesKey: 'agentRegistry.codex.responsibilities', ownerDepartmentId: 'backend-infrastructure', status: 'active', lastValidationKey: 'agentRegistry.codex.validation', lastActivityKey: 'agentRegistry.codex.activity', reliabilityKey: 'agentRegistry.reliability.validated', displayName: 'Backend & Infrastructure', displayRole: 'API and infrastructure', displayResponsibilities: 'Maintains API services, deployment configuration and operational dependencies.',
  },
  {
    id: 'i18n-localization', code: 'I18N-LOCALIZATION', nameKey: 'agentRegistry.codex.name', roleKey: 'agentRegistry.codex.role', responsibilitiesKey: 'agentRegistry.codex.responsibilities', ownerDepartmentId: 'ai-agents', status: 'monitoring', lastValidationKey: 'agentRegistry.codex.validation', lastActivityKey: 'agentRegistry.codex.activity', reliabilityKey: 'agentRegistry.reliability.monitoring', displayName: 'I18n / Localization', displayRole: 'Language coverage', displayResponsibilities: 'Tracks language dictionaries, speech locales and translation coverage.',
  },
  {
    id: 'documentation', code: 'DOCUMENTATION', nameKey: 'agentRegistry.codex.name', roleKey: 'agentRegistry.codex.role', responsibilitiesKey: 'agentRegistry.codex.responsibilities', ownerDepartmentId: 'documentation-knowledge', status: 'active', lastValidationKey: 'agentRegistry.codex.validation', lastActivityKey: 'agentRegistry.codex.activity', reliabilityKey: 'agentRegistry.reliability.validated', displayName: 'Documentation', displayRole: 'Project records', displayResponsibilities: 'Keeps reports, decisions and operational references current.',
  },
  {
    id: 'agent-codex',
    code: 'AGENT-CODEX',
    nameKey: 'agentRegistry.codex.name',
    roleKey: 'agentRegistry.codex.role',
    responsibilitiesKey: 'agentRegistry.codex.responsibilities',
    ownerDepartmentId: 'maintenance-quality-evolution',
    status: 'active',
    lastValidationKey: 'agentRegistry.codex.validation',
    lastActivityKey: 'agentRegistry.codex.activity',
    reliabilityKey: 'agentRegistry.reliability.validated',
  },
  {
    id: 'agent-inspector',
    code: 'AGENT-INSPECTOR',
    nameKey: 'agentRegistry.inspector.name',
    roleKey: 'agentRegistry.inspector.role',
    responsibilitiesKey: 'agentRegistry.inspector.responsibilities',
    ownerDepartmentId: 'maintenance-quality-evolution',
    status: 'active',
    lastValidationKey: 'agentRegistry.inspector.validation',
    lastActivityKey: 'agentRegistry.inspector.activity',
    reliabilityKey: 'agentRegistry.reliability.validated',
  },
  {
    id: 'infrastructure-reuse-coordinator',
    code: 'INFRA-REUSE-COORDINATOR',
    nameKey: 'agentRegistry.reuseCoordinator.name',
    roleKey: 'agentRegistry.reuseCoordinator.role',
    responsibilitiesKey: 'agentRegistry.reuseCoordinator.responsibilities',
    ownerDepartmentId: 'qa-validation',
    status: 'active',
    lastValidationKey: 'agentRegistry.reuseCoordinator.validation',
    lastActivityKey: 'agentRegistry.reuseCoordinator.activity',
    reliabilityKey: 'agentRegistry.reliability.validated',
  },
  {
    id: 'agent-mentor',
    code: 'AGENT-MENTOR',
    nameKey: 'agentRegistry.mentor.name',
    roleKey: 'agentRegistry.mentor.role',
    responsibilitiesKey: 'agentRegistry.mentor.responsibilities',
    ownerDepartmentId: 'product-roadmap',
    status: 'active',
    lastValidationKey: 'agentRegistry.mentor.validation',
    lastActivityKey: 'agentRegistry.mentor.activity',
    reliabilityKey: 'agentRegistry.reliability.validated',
  },
  {
    id: 'agent-legal',
    code: 'AGENT-LEGAL',
    nameKey: 'agentRegistry.legal.name',
    roleKey: 'agentRegistry.legal.role',
    responsibilitiesKey: 'agentRegistry.legal.responsibilities',
    ownerDepartmentId: 'security-legal',
    status: 'monitoring',
    lastValidationKey: 'agentRegistry.legal.validation',
    lastActivityKey: 'agentRegistry.legal.activity',
    reliabilityKey: 'agentRegistry.reliability.monitoring',
  },
  {
    id: 'agent-linguistic-ro-de',
    code: 'AG-011-011A',
    nameKey: 'agentRegistry.roDe.name',
    roleKey: 'agentRegistry.roDe.role',
    responsibilitiesKey: 'agentRegistry.roDe.responsibilities',
    ownerDepartmentId: 'ai-agents',
    status: 'active',
    lastValidationKey: 'agentRegistry.roDe.validation',
    lastActivityKey: 'agentRegistry.roDe.activity',
    reliabilityKey: 'agentRegistry.reliability.validated',
    displayName: 'RO ↔ DE Specialist',
    displayRole: 'Agent lingvistic operațional RO / DE',
    displayResponsibilities: 'Corectează și normalizează determinist texte RO/DE prin APP-006, cu provenance AG-011-011A.',
  },
  {
    id: 'agent-linguistic-ro-en',
    code: 'AG-011-011B',
    nameKey: 'agentRegistry.roEn.name',
    roleKey: 'agentRegistry.roEn.role',
    responsibilitiesKey: 'agentRegistry.roEn.responsibilities',
    ownerDepartmentId: 'ai-agents',
    status: 'active',
    lastValidationKey: 'agentRegistry.roEn.validation',
    lastActivityKey: 'agentRegistry.roEn.activity',
    reliabilityKey: 'agentRegistry.reliability.validated',
    displayName: 'RO ↔ EN Specialist',
    displayRole: 'Agent lingvistic operațional RO / EN',
    displayResponsibilities: 'Corectează și normalizează determinist texte RO/EN prin APP-006, cu provenance AG-011-011B.',
  },
  {
    id: 'agent-linguistic-de-en',
    code: 'AG-011-011C',
    nameKey: 'agentRegistry.deEn.name',
    roleKey: 'agentRegistry.deEn.role',
    responsibilitiesKey: 'agentRegistry.deEn.responsibilities',
    ownerDepartmentId: 'ai-agents',
    status: 'active',
    lastValidationKey: 'agentRegistry.deEn.validation',
    lastActivityKey: 'agentRegistry.deEn.activity',
    reliabilityKey: 'agentRegistry.reliability.validated',
    displayName: 'DE ↔ EN Specialist',
    displayRole: 'Agent lingvistic operațional DE / EN',
    displayResponsibilities: 'Corectează și normalizează determinist texte DE/EN prin APP-006, cu provenance AG-011-011C.',
  },
  {
    id: 'premium-linguist-it',
    code: 'AG-I18N-IT',
    nameKey: 'agentRegistry.codex.name',
    roleKey: 'agentRegistry.codex.role',
    responsibilitiesKey: 'agentRegistry.codex.responsibilities',
    ownerDepartmentId: 'ai-agents',
    status: 'active',
    lastValidationKey: 'agentRegistry.codex.validation',
    lastActivityKey: 'agentRegistry.codex.activity',
    reliabilityKey: 'agentRegistry.reliability.validated',
    displayName: 'Italian Language Agent',
    displayRole: 'Autoritate lingvistică operațională IT',
    displayResponsibilities: 'Validează exclusiv pachetul italian în APP, Premium și Car Mover; publică heartbeat din auditul determinist al celor 1.699 de resurse.',
  },
  {
    id: 'premium-linguist-es',
    code: 'AG-I18N-ES',
    nameKey: 'agentRegistry.codex.name',
    roleKey: 'agentRegistry.codex.role',
    responsibilitiesKey: 'agentRegistry.codex.responsibilities',
    ownerDepartmentId: 'ai-agents',
    status: 'active',
    lastValidationKey: 'agentRegistry.codex.validation',
    lastActivityKey: 'agentRegistry.codex.activity',
    reliabilityKey: 'agentRegistry.reliability.validated',
    displayName: 'Spanish Language Agent',
    displayRole: 'Autoritate lingvistică operațională ES',
    displayResponsibilities: 'Validează exclusiv pachetul spaniol în APP, Premium și Car Mover; publică heartbeat din auditul determinist al celor 1.699 de resurse.',
  },
  {
    id: 'premium-linguist-sv',
    code: 'AG-I18N-SV',
    nameKey: 'agentRegistry.codex.name',
    roleKey: 'agentRegistry.codex.role',
    responsibilitiesKey: 'agentRegistry.codex.responsibilities',
    ownerDepartmentId: 'ai-agents',
    status: 'active',
    lastValidationKey: 'agentRegistry.codex.validation',
    lastActivityKey: 'agentRegistry.codex.activity',
    reliabilityKey: 'agentRegistry.reliability.validated',
    displayName: 'Swedish Language Agent',
    displayRole: 'Autoritate lingvistică operațională SV',
    displayResponsibilities: 'Validează exclusiv pachetul suedez în APP, Premium și Car Mover; publică heartbeat din auditul determinist al celor 1.699 de resurse.',
  },
  {
    id: 'agent-linguistic-librarian',
    code: 'AGENT-LINGUISTIC-LIBRARIAN',
    nameKey: 'agentRegistry.librarian.name',
    roleKey: 'agentRegistry.librarian.role',
    responsibilitiesKey: 'agentRegistry.librarian.responsibilities',
    ownerDepartmentId: 'maintenance-quality-evolution',
    status: 'active',
    lastValidationKey: 'agentRegistry.librarian.validation',
    lastActivityKey: 'agentRegistry.librarian.activity',
    reliabilityKey: 'agentRegistry.reliability.validated',
  },
  {
    id: 'director-turn-operations',
    code: 'DIRECTOR-TURN-OPS',
    nameKey: 'agentRegistry.turnOps.name',
    roleKey: 'agentRegistry.turnOps.role',
    responsibilitiesKey: 'agentRegistry.turnOps.responsibilities',
    ownerDepartmentId: 'maintenance-quality-evolution',
    status: 'active',
    lastValidationKey: 'agentRegistry.turnOps.validation',
    lastActivityKey: 'agentRegistry.turnOps.activity',
    reliabilityKey: 'agentRegistry.reliability.validated',
  },
  {
    id: 'agent-agm-chronicler',
    code: 'AGENT-CHRONICLER',
    nameKey: 'agentRegistry.chronicler.name',
    roleKey: 'agentRegistry.chronicler.role',
    responsibilitiesKey: 'agentRegistry.chronicler.responsibilities',
    ownerDepartmentId: 'maintenance-quality-evolution',
    status: 'active',
    lastValidationKey: 'agentRegistry.chronicler.validation',
    lastActivityKey: 'agentRegistry.chronicler.activity',
    reliabilityKey: 'agentRegistry.reliability.monitoring',
  },
];
