export type InspectorStatus = 'ok' | 'attention' | 'error';
export type InspectorTrend = 'stable' | 'improving' | 'watch';

export type InspectorAlertHistoryItem = {
  id: string;
  status: InspectorStatus;
  createdAt: string;
  messageKey: string;
};

export type InspectorReport = {
  id: string;
  ownerId: string;
  ownerType: 'department' | 'agent' | 'module';
  status: InspectorStatus;
  lastCheckedAt: string;
  trend: InspectorTrend;
  summaryKey: string;
  issuesKey: string;
  recommendationsKey: string;
  auditKey: string;
  impactKey: string;
  priorityKey: string;
  alertHistory: InspectorAlertHistoryItem[];
};

export const inspectorReports: InspectorReport[] = [
  {
    id: 'inspector-turn-command',
    ownerId: 'turn-command',
    ownerType: 'department',
    status: 'ok',
    lastCheckedAt: '2026-07-13T20:00:00Z',
    trend: 'stable',
    summaryKey: 'inspector.report.turnCommand.summary',
    issuesKey: 'inspector.report.turnCommand.issues',
    recommendationsKey: 'inspector.report.turnCommand.recommendations',
    auditKey: 'inspector.report.turnCommand.summary',
    impactKey: 'inspector.report.turnCommand.issues',
    priorityKey: 'inspector.report.turnCommand.recommendations',
    alertHistory: [
      { id: 'turn-command-ag-018', status: 'ok', createdAt: '2026-07-13T20:00:00Z', messageKey: 'inspector.report.turnCommand.summary' },
    ],
  },
  {
    id: 'inspector-product-roadmap',
    ownerId: 'product-roadmap',
    ownerType: 'department',
    status: 'attention',
    lastCheckedAt: '2026-07-13T20:00:00Z',
    trend: 'watch',
    summaryKey: 'inspector.report.productRoadmap.summary',
    issuesKey: 'inspector.report.productRoadmap.issues',
    recommendationsKey: 'inspector.report.productRoadmap.recommendations',
    auditKey: 'inspector.report.productRoadmap.summary',
    impactKey: 'inspector.report.productRoadmap.issues',
    priorityKey: 'inspector.report.productRoadmap.recommendations',
    alertHistory: [
      { id: 'product-roadmap-ag-018', status: 'attention', createdAt: '2026-07-13T20:00:00Z', messageKey: 'inspector.report.productRoadmap.summary' },
    ],
  },
  {
    id: 'inspector-architecture-platform',
    ownerId: 'architecture-platform',
    ownerType: 'department',
    status: 'ok',
    lastCheckedAt: '2026-07-13T20:00:00Z',
    trend: 'stable',
    summaryKey: 'inspector.report.architecture.summary',
    issuesKey: 'inspector.report.architecture.issues',
    recommendationsKey: 'inspector.report.architecture.recommendations',
    auditKey: 'inspector.report.architecture.summary',
    impactKey: 'inspector.report.architecture.issues',
    priorityKey: 'inspector.report.architecture.recommendations',
    alertHistory: [
      { id: 'architecture-ag-018', status: 'ok', createdAt: '2026-07-13T20:00:00Z', messageKey: 'inspector.report.architecture.summary' },
    ],
  },
  {
    id: 'inspector-frontend-experience',
    ownerId: 'frontend-experience',
    ownerType: 'department',
    status: 'attention',
    lastCheckedAt: '2026-07-13T20:00:00Z',
    trend: 'watch',
    summaryKey: 'inspector.report.frontend.summary',
    issuesKey: 'inspector.report.frontend.issues',
    recommendationsKey: 'inspector.report.frontend.recommendations',
    auditKey: 'inspector.report.frontend.summary',
    impactKey: 'inspector.report.frontend.issues',
    priorityKey: 'inspector.report.frontend.recommendations',
    alertHistory: [
      { id: 'frontend-ag-018', status: 'attention', createdAt: '2026-07-13T20:00:00Z', messageKey: 'inspector.report.frontend.summary' },
    ],
  },
  {
    id: 'inspector-backend-infrastructure',
    ownerId: 'backend-infrastructure',
    ownerType: 'department',
    status: 'ok',
    lastCheckedAt: '2026-07-13T20:00:00Z',
    trend: 'stable',
    summaryKey: 'inspector.report.backend.summary',
    issuesKey: 'inspector.report.backend.issues',
    recommendationsKey: 'inspector.report.backend.recommendations',
    auditKey: 'inspector.report.backend.summary',
    impactKey: 'inspector.report.backend.issues',
    priorityKey: 'inspector.report.backend.recommendations',
    alertHistory: [
      { id: 'backend-ag-018', status: 'ok', createdAt: '2026-07-13T20:00:00Z', messageKey: 'inspector.report.backend.summary' },
    ],
  },
  {
    id: 'inspector-ai-agents',
    ownerId: 'ai-agents',
    ownerType: 'department',
    status: 'attention',
    lastCheckedAt: '2026-07-13T20:00:00Z',
    trend: 'watch',
    summaryKey: 'inspector.report.aiAgents.summary',
    issuesKey: 'inspector.report.aiAgents.issues',
    recommendationsKey: 'inspector.report.aiAgents.recommendations',
    auditKey: 'inspector.report.aiAgents.summary',
    impactKey: 'inspector.report.aiAgents.issues',
    priorityKey: 'inspector.report.aiAgents.recommendations',
    alertHistory: [
      { id: 'ai-agents-ag-018', status: 'attention', createdAt: '2026-07-13T20:00:00Z', messageKey: 'inspector.report.aiAgents.summary' },
    ],
  },
  {
    id: 'inspector-qa-validation',
    ownerId: 'qa-validation',
    ownerType: 'department',
    status: 'ok',
    lastCheckedAt: '2026-07-13T20:00:00Z',
    trend: 'stable',
    summaryKey: 'inspector.report.qa.summary',
    issuesKey: 'inspector.report.qa.issues',
    recommendationsKey: 'inspector.report.qa.recommendations',
    auditKey: 'inspector.report.qa.summary',
    impactKey: 'inspector.report.qa.issues',
    priorityKey: 'inspector.report.qa.recommendations',
    alertHistory: [
      { id: 'qa-ag-018', status: 'ok', createdAt: '2026-07-13T20:00:00Z', messageKey: 'inspector.report.qa.summary' },
    ],
  },
  {
    id: 'inspector-security-legal',
    ownerId: 'security-legal',
    ownerType: 'department',
    status: 'ok',
    lastCheckedAt: '2026-07-13T20:00:00Z',
    trend: 'stable',
    summaryKey: 'inspector.report.securityLegal.summary',
    issuesKey: 'inspector.report.securityLegal.issues',
    recommendationsKey: 'inspector.report.securityLegal.recommendations',
    auditKey: 'inspector.report.securityLegal.summary',
    impactKey: 'inspector.report.securityLegal.issues',
    priorityKey: 'inspector.report.securityLegal.recommendations',
    alertHistory: [
      { id: 'security-legal-ag-018', status: 'ok', createdAt: '2026-07-13T20:00:00Z', messageKey: 'inspector.report.securityLegal.summary' },
    ],
  },
  {
    id: 'inspector-release-operations',
    ownerId: 'release-operations',
    ownerType: 'department',
    status: 'attention',
    lastCheckedAt: '2026-07-13T20:00:00Z',
    trend: 'watch',
    summaryKey: 'inspector.report.releaseOps.summary',
    issuesKey: 'inspector.report.releaseOps.issues',
    recommendationsKey: 'inspector.report.releaseOps.recommendations',
    auditKey: 'inspector.report.releaseOps.summary',
    impactKey: 'inspector.report.releaseOps.issues',
    priorityKey: 'inspector.report.releaseOps.recommendations',
    alertHistory: [
      { id: 'release-ops-ag-018', status: 'attention', createdAt: '2026-07-13T20:00:00Z', messageKey: 'inspector.report.releaseOps.summary' },
    ],
  },
  {
    id: 'inspector-documentation-knowledge',
    ownerId: 'documentation-knowledge',
    ownerType: 'department',
    status: 'ok',
    lastCheckedAt: '2026-07-13T20:00:00Z',
    trend: 'stable',
    summaryKey: 'inspector.report.documentation.summary',
    issuesKey: 'inspector.report.documentation.issues',
    recommendationsKey: 'inspector.report.documentation.recommendations',
    auditKey: 'inspector.report.documentation.summary',
    impactKey: 'inspector.report.documentation.issues',
    priorityKey: 'inspector.report.documentation.recommendations',
    alertHistory: [
      { id: 'documentation-ag-018', status: 'ok', createdAt: '2026-07-13T20:00:00Z', messageKey: 'inspector.report.documentation.summary' },
    ],
  },
  {
    id: 'inspector-agent-architecture',
    ownerId: 'architecture',
    ownerType: 'agent',
    status: 'ok',
    lastCheckedAt: '2026-07-13T20:00:00Z',
    trend: 'stable',
    summaryKey: 'inspector.report.agentActive.summary',
    issuesKey: 'inspector.report.agentActive.issues',
    recommendationsKey: 'inspector.report.agentActive.recommendations',
    auditKey: 'inspector.report.agentActive.summary',
    impactKey: 'inspector.report.agentActive.issues',
    priorityKey: 'inspector.report.agentActive.recommendations',
    alertHistory: [
      { id: 'agent-architecture-ag-018', status: 'ok', createdAt: '2026-07-13T20:00:00Z', messageKey: 'inspector.report.agentActive.summary' },
    ],
  },
  {
    id: 'inspector-agent-qa',
    ownerId: 'qa-testing',
    ownerType: 'agent',
    status: 'attention',
    lastCheckedAt: '2026-07-13T20:00:00Z',
    trend: 'watch',
    summaryKey: 'inspector.report.agentAttention.summary',
    issuesKey: 'inspector.report.agentAttention.issues',
    recommendationsKey: 'inspector.report.agentAttention.recommendations',
    auditKey: 'inspector.report.agentAttention.summary',
    impactKey: 'inspector.report.agentAttention.issues',
    priorityKey: 'inspector.report.agentAttention.recommendations',
    alertHistory: [
      { id: 'agent-qa-ag-018', status: 'attention', createdAt: '2026-07-13T20:00:00Z', messageKey: 'inspector.report.agentAttention.summary' },
    ],
  },
  {
    id: 'inspector-agent-ui-ux',
    ownerId: 'ui-ux',
    ownerType: 'agent',
    status: 'ok',
    lastCheckedAt: '2026-07-13T20:00:00Z',
    trend: 'improving',
    summaryKey: 'inspector.report.agentActive.summary',
    issuesKey: 'inspector.report.agentActive.issues',
    recommendationsKey: 'inspector.report.agentActive.recommendations',
    auditKey: 'inspector.report.agentActive.summary',
    impactKey: 'inspector.report.agentActive.issues',
    priorityKey: 'inspector.report.agentActive.recommendations',
    alertHistory: [
      { id: 'agent-uiux-ag-018', status: 'ok', createdAt: '2026-07-13T20:00:00Z', messageKey: 'inspector.report.agentActive.summary' },
    ],
  },
  {
    id: 'inspector-agent-i18n',
    ownerId: 'i18n',
    ownerType: 'agent',
    status: 'ok',
    lastCheckedAt: '2026-07-13T20:00:00Z',
    trend: 'stable',
    summaryKey: 'inspector.report.agentActive.summary',
    issuesKey: 'inspector.report.agentActive.issues',
    recommendationsKey: 'inspector.report.agentActive.recommendations',
    auditKey: 'inspector.report.agentActive.summary',
    impactKey: 'inspector.report.agentActive.issues',
    priorityKey: 'inspector.report.agentActive.recommendations',
    alertHistory: [
      { id: 'agent-i18n-ag-018', status: 'ok', createdAt: '2026-07-13T20:00:00Z', messageKey: 'inspector.report.agentActive.summary' },
    ],
  },
  {
    id: 'inspector-agent-security',
    ownerId: 'security',
    ownerType: 'agent',
    status: 'ok',
    lastCheckedAt: '2026-07-13T20:00:00Z',
    trend: 'stable',
    summaryKey: 'inspector.report.agentActive.summary',
    issuesKey: 'inspector.report.agentActive.issues',
    recommendationsKey: 'inspector.report.agentActive.recommendations',
    auditKey: 'inspector.report.agentActive.summary',
    impactKey: 'inspector.report.agentActive.issues',
    priorityKey: 'inspector.report.agentActive.recommendations',
    alertHistory: [
      { id: 'agent-security-ag-018', status: 'ok', createdAt: '2026-07-13T20:00:00Z', messageKey: 'inspector.report.agentActive.summary' },
    ],
  },
  {
    id: 'inspector-agent-legal',
    ownerId: 'legal',
    ownerType: 'agent',
    status: 'attention',
    lastCheckedAt: '2026-07-13T20:00:00Z',
    trend: 'watch',
    summaryKey: 'inspector.report.agentAttention.summary',
    issuesKey: 'inspector.report.agentAttention.issues',
    recommendationsKey: 'inspector.report.agentAttention.recommendations',
    auditKey: 'inspector.report.agentAttention.summary',
    impactKey: 'inspector.report.agentAttention.issues',
    priorityKey: 'inspector.report.agentAttention.recommendations',
    alertHistory: [
      { id: 'agent-legal-ag-018', status: 'attention', createdAt: '2026-07-13T20:00:00Z', messageKey: 'inspector.report.agentAttention.summary' },
    ],
  },
  {
    id: 'inspector-agent-integration',
    ownerId: 'integration',
    ownerType: 'agent',
    status: 'ok',
    lastCheckedAt: '2026-07-13T20:00:00Z',
    trend: 'stable',
    summaryKey: 'inspector.report.agentActive.summary',
    issuesKey: 'inspector.report.agentActive.issues',
    recommendationsKey: 'inspector.report.agentActive.recommendations',
    auditKey: 'inspector.report.agentActive.summary',
    impactKey: 'inspector.report.agentActive.issues',
    priorityKey: 'inspector.report.agentActive.recommendations',
    alertHistory: [
      { id: 'agent-integration-ag-018', status: 'ok', createdAt: '2026-07-13T20:00:00Z', messageKey: 'inspector.report.agentActive.summary' },
    ],
  },
  {
    id: 'inspector-agent-documentation',
    ownerId: 'documentation',
    ownerType: 'agent',
    status: 'ok',
    lastCheckedAt: '2026-07-13T20:00:00Z',
    trend: 'stable',
    summaryKey: 'inspector.report.agentActive.summary',
    issuesKey: 'inspector.report.agentActive.issues',
    recommendationsKey: 'inspector.report.agentActive.recommendations',
    auditKey: 'inspector.report.agentActive.summary',
    impactKey: 'inspector.report.agentActive.issues',
    priorityKey: 'inspector.report.agentActive.recommendations',
    alertHistory: [
      { id: 'agent-documentation-ag-018', status: 'ok', createdAt: '2026-07-13T20:00:00Z', messageKey: 'inspector.report.agentActive.summary' },
    ],
  },
  {
    id: 'inspector-agent-ai-governance',
    ownerId: 'ai-governance',
    ownerType: 'agent',
    status: 'attention',
    lastCheckedAt: '2026-07-13T20:00:00Z',
    trend: 'watch',
    summaryKey: 'inspector.report.agentAttention.summary',
    issuesKey: 'inspector.report.agentAttention.issues',
    recommendationsKey: 'inspector.report.agentAttention.recommendations',
    auditKey: 'inspector.report.agentAttention.summary',
    impactKey: 'inspector.report.agentAttention.issues',
    priorityKey: 'inspector.report.agentAttention.recommendations',
    alertHistory: [
      { id: 'agent-ai-governance-ag-018', status: 'attention', createdAt: '2026-07-13T20:00:00Z', messageKey: 'inspector.report.agentAttention.summary' },
    ],
  },
  {
    id: 'inspector-agent-release',
    ownerId: 'release',
    ownerType: 'agent',
    status: 'attention',
    lastCheckedAt: '2026-07-13T20:00:00Z',
    trend: 'watch',
    summaryKey: 'inspector.report.agentAttention.summary',
    issuesKey: 'inspector.report.agentAttention.issues',
    recommendationsKey: 'inspector.report.agentAttention.recommendations',
    auditKey: 'inspector.report.agentAttention.summary',
    impactKey: 'inspector.report.agentAttention.issues',
    priorityKey: 'inspector.report.agentAttention.recommendations',
    alertHistory: [
      { id: 'agent-release-ag-018', status: 'attention', createdAt: '2026-07-13T20:00:00Z', messageKey: 'inspector.report.agentAttention.summary' },
    ],
  },
];

export function inspectorReportFor(ownerId: string) {
  return inspectorReports.find((report) => report.ownerId === ownerId);
}
