import { createHash, randomUUID } from 'node:crypto';

export type RiskClass = 'LOW' | 'MEDIUM' | 'HIGH' | 'REGULATED';
export type ReviewDomain = 'FUNCTIONAL' | 'SOURCE_EVIDENCE' | 'SECURITY_PRIVACY' | 'LEGAL_COMPLIANCE' | 'REGULATORY_HUMAN';
export type ReviewVerdict = 'PASS' | 'REWORK' | 'REJECT';
export type DossierStatus = 'PROPOSAL' | 'ANALYSIS' | 'DOMAIN_VALIDATION' | 'REWORK' | 'REJECTED' | 'KNOWLEDGE_GATE_READY';
export type EvidenceReference = { evidenceId: string; sourceUri: string; sourceType: 'PRIMARY' | 'SECONDARY' | 'OFFICIAL'; contentHash: string; capturedAt: string; provenance: string };
export type PolicySnapshot = { policyVersion: string; riskClass: RiskClass; requiredReviews: ReviewDomain[]; capturedAt: string; snapshotHash: string };
export type DossierRevision = { dossierId: string; tenantId: string; revision: number; proposerId: string; title: string; content: string; contentHash: string; evidence: EvidenceReference[]; evidenceHash: string; provenance: string; riskClass: RiskClass; policy: PolicySnapshot; status: DossierStatus; createdAt: string; revisionHash: string; previousRevisionHash: string | null };
export type VerdictRecord = { verdictId: string; dossierId: string; revision: number; revisionHash: string; evidenceHash: string; reviewerId: string; reviewerWorkloadId: string; domain: ReviewDomain; verdict: ReviewVerdict; reasonCode: string; occurredAt: string; verdictHash: string };
export type DossierEvent = { eventId: string; dossierId: string; tenantId: string; revision: number; status: DossierStatus; revisionHash: string; occurredAt: string };
type PolicyFile = { policyVersion: string; riskRoutes: Record<RiskClass, ReviewDomain[]>; terminalAllowed: string[]; terminalForbidden: string[] };

export class RiskRouter {
  constructor(private readonly policy: PolicyFile) {}
  classify(signals: { regulated?: boolean; legal?: boolean; security?: boolean; personalData?: boolean; secondaryOnly?: boolean }) : RiskClass {
    if (signals.regulated) return 'REGULATED';
    if (signals.legal || signals.security) return 'HIGH';
    if (signals.personalData || signals.secondaryOnly) return 'MEDIUM';
    return 'LOW';
  }
  snapshot(riskClass: RiskClass, capturedAt: string): PolicySnapshot { const raw = { policyVersion: this.policy.policyVersion, riskClass, requiredReviews: [...this.policy.riskRoutes[riskClass]], capturedAt }; return Object.freeze({ ...raw, requiredReviews: Object.freeze(raw.requiredReviews) as unknown as ReviewDomain[], snapshotHash: digest(stable(raw)) }); }
  forbidden(status: string) { return this.policy.terminalForbidden.includes(status); }
}

export class KnowledgeDossierStore {
  readonly #revisions = new Map<string, DossierRevision[]>(); readonly #verdicts = new Map<string, VerdictRecord[]>(); readonly #verdictIds = new Set<string>(); readonly #events: DossierEvent[] = [];
  constructor(private readonly router: RiskRouter) {}
  create(input: { tenantId: string; proposerId: string; title: string; content: string; evidence: EvidenceReference[]; provenance: string; riskClass: RiskClass; now: string; dossierId?: string }) {
    const dossierId = input.dossierId ?? `dossier-${randomUUID()}`; if (this.#revisions.has(dossierId)) throw new Error('DOSSIER_ID_CONFLICT');
    const revision = this.build({ ...input, dossierId, revision: 1, status: 'PROPOSAL', previousRevisionHash: null }); this.#revisions.set(dossierId, [revision]); this.emit(revision); return cloneRevision(revision);
  }
  revise(input: { dossierId: string; expectedRevision: number; proposerId: string; content: string; evidence: EvidenceReference[]; provenance: string; riskClass: RiskClass; now: string }) {
    const current = this.current(input.dossierId); if (!current) throw new Error('DOSSIER_NOT_FOUND'); if (current.revision !== input.expectedRevision) throw new Error('REVISION_CONFLICT');
    const revision = this.build({ tenantId: current.tenantId, proposerId: input.proposerId, title: current.title, content: input.content, evidence: input.evidence, provenance: input.provenance, riskClass: input.riskClass, now: input.now, dossierId: input.dossierId, revision: current.revision + 1, status: 'PROPOSAL', previousRevisionHash: current.revisionHash }); this.#revisions.get(input.dossierId)!.push(revision); this.emit(revision); return cloneRevision(revision);
  }
  transition(dossierId: string, expectedRevision: number, status: DossierStatus, now: string) { if (this.router.forbidden(status)) throw new Error('P4_TERMINAL_STATE_FORBIDDEN'); const current = this.current(dossierId); if (!current) throw new Error('DOSSIER_NOT_FOUND'); if (current.revision !== expectedRevision) throw new Error('REVISION_CONFLICT'); if (!allowedTransition(current.status, status)) throw new Error('INVALID_DOSSIER_TRANSITION'); const updated = freezeRevision({ ...current, status, createdAt: now, revisionHash: digest(stable({ ...current, status, createdAt: now, revisionHash: undefined })) }); this.#revisions.get(dossierId)!.push(updated); this.emit(updated); return cloneRevision(updated); }
  submitVerdict(input: Omit<VerdictRecord, 'verdictHash'>) { const current = this.current(input.dossierId); if (!current) throw new Error('DOSSIER_NOT_FOUND'); if (this.#verdictIds.has(input.verdictId)) throw new Error('DUPLICATE_VERDICT'); if (input.reviewerId === current.proposerId) throw new Error('SOD_PROPOSER_VALIDATOR_DENIED'); if (input.revision !== current.revision || input.revisionHash !== current.revisionHash || input.evidenceHash !== current.evidenceHash) throw new Error('STALE_VERDICT'); if (!current.policy.requiredReviews.includes(input.domain)) throw new Error('UNROUTED_REVIEW_DOMAIN'); if ((this.#verdicts.get(input.dossierId) ?? []).some((item) => item.revision === input.revision && item.domain === input.domain && item.reviewerId === input.reviewerId)) throw new Error('DUPLICATE_REVIEWER_DOMAIN'); const record = Object.freeze({ ...input, verdictHash: digest(stable(input)) }); this.#verdictIds.add(input.verdictId); const list = this.#verdicts.get(input.dossierId) ?? []; list.push(record); this.#verdicts.set(input.dossierId, list); return { ...record }; }
  aggregate(dossierId: string, expectedRevision: number, now: string) { const current = this.current(dossierId); if (!current) throw new Error('DOSSIER_NOT_FOUND'); if (current.revision !== expectedRevision) throw new Error('REVISION_CONFLICT'); const records = (this.#verdicts.get(dossierId) ?? []).filter((item) => item.revision === expectedRevision); const byDomain = new Map<ReviewDomain, VerdictRecord[]>(); records.forEach((item) => byDomain.set(item.domain, [...(byDomain.get(item.domain) ?? []), item])); const missing = current.policy.requiredReviews.filter((domain) => !byDomain.has(domain)); if (missing.length) return { status: 'REWORK' as const, reason: 'REQUIRED_REVIEW_MISSING', missing, dossier: this.transition(dossierId, expectedRevision, 'REWORK', now) }; for (const values of byDomain.values()) { const unique = new Set(values.map((item) => item.verdict)); if (unique.size > 1) return { status: 'REWORK' as const, reason: 'CONFLICTING_VERDICTS', missing: [], dossier: this.transition(dossierId, expectedRevision, 'REWORK', now) }; }
    if (records.some((item) => item.verdict === 'REJECT')) return { status: 'REJECTED' as const, reason: 'DOMAIN_REJECT', missing: [], dossier: this.transition(dossierId, expectedRevision, 'REJECTED', now) };
    if (records.some((item) => item.verdict === 'REWORK')) return { status: 'REWORK' as const, reason: 'DOMAIN_REWORK', missing: [], dossier: this.transition(dossierId, expectedRevision, 'REWORK', now) };
    return { status: 'KNOWLEDGE_GATE_READY' as const, reason: 'ALL_REQUIRED_REVIEWS_PASS', missing: [], dossier: this.transition(dossierId, expectedRevision, 'KNOWLEDGE_GATE_READY', now) };
  }
  current(dossierId: string) { const value = this.#revisions.get(dossierId)?.at(-1); return value ? cloneRevision(value) : undefined; }
  history(dossierId: string) { return (this.#revisions.get(dossierId) ?? []).map(cloneRevision); }
  verdicts(dossierId: string) { return (this.#verdicts.get(dossierId) ?? []).map((item) => ({ ...item })); }
  events() { return this.#events.map((item) => ({ ...item })); }
  snapshot() { return { revisions: [...this.#revisions.entries()].map(([id, values]) => [id, values.map(cloneRevision)] as const), verdicts: [...this.#verdicts.entries()].map(([id, values]) => [id, values.map((item) => ({ ...item }))] as const), verdictIds: [...this.#verdictIds], events: this.events(), snapshotHash: digest(stable({ revisions: [...this.#revisions.entries()], verdicts: [...this.#verdicts.entries()], events: this.#events })) }; }
  restore(snapshot: ReturnType<KnowledgeDossierStore['snapshot']>) { const expected = digest(stable({ revisions: snapshot.revisions, verdicts: snapshot.verdicts, events: snapshot.events })); if (snapshot.snapshotHash !== expected) throw new Error('DOSSIER_SNAPSHOT_INTEGRITY_FAILURE'); this.#revisions.clear(); this.#verdicts.clear(); this.#verdictIds.clear(); this.#events.length = 0; snapshot.revisions.forEach(([id, values]) => this.#revisions.set(id, values.map(freezeRevision))); snapshot.verdicts.forEach(([id, values]) => this.#verdicts.set(id, values.map((item) => Object.freeze({ ...item })))); snapshot.verdictIds.forEach((id) => this.#verdictIds.add(id)); snapshot.events.forEach((event) => this.#events.push(Object.freeze({ ...event }))); }
  private build(input: { tenantId: string; proposerId: string; title: string; content: string; evidence: EvidenceReference[]; provenance: string; riskClass: RiskClass; now: string; dossierId: string; revision: number; status: DossierStatus; previousRevisionHash: string | null }) { const evidence = input.evidence.map((item) => Object.freeze({ ...item })); const contentHash = digest(input.content); const evidenceHash = digest(stable(evidence)); const policy = this.router.snapshot(input.riskClass, input.now); const raw = { dossierId: input.dossierId, tenantId: input.tenantId, revision: input.revision, proposerId: input.proposerId, title: input.title, content: input.content, contentHash, evidence, evidenceHash, provenance: input.provenance, riskClass: input.riskClass, policy, status: input.status, createdAt: input.now, previousRevisionHash: input.previousRevisionHash }; return freezeRevision({ ...raw, revisionHash: digest(stable(raw)) }); }
  private emit(revision: DossierRevision) { this.#events.push(Object.freeze({ eventId: `dossier-event-${randomUUID()}`, dossierId: revision.dossierId, tenantId: revision.tenantId, revision: revision.revision, status: revision.status, revisionHash: revision.revisionHash, occurredAt: revision.createdAt })); }
}

function allowedTransition(from: DossierStatus, to: DossierStatus) { const allowed: Record<DossierStatus, DossierStatus[]> = { PROPOSAL: ['ANALYSIS'], ANALYSIS: ['DOMAIN_VALIDATION', 'REWORK', 'REJECTED'], DOMAIN_VALIDATION: ['REWORK', 'REJECTED', 'KNOWLEDGE_GATE_READY'], REWORK: [], REJECTED: [], KNOWLEDGE_GATE_READY: [] }; return allowed[from].includes(to); }
function freezeRevision(value: DossierRevision): DossierRevision { return Object.freeze({ ...value, evidence: Object.freeze(value.evidence.map((item) => Object.freeze({ ...item }))) as unknown as EvidenceReference[], policy: Object.freeze({ ...value.policy, requiredReviews: Object.freeze([...value.policy.requiredReviews]) as unknown as ReviewDomain[] }) }); }
function cloneRevision(value: DossierRevision): DossierRevision { return { ...value, evidence: value.evidence.map((item) => ({ ...item })), policy: { ...value.policy, requiredReviews: [...value.policy.requiredReviews] } }; }
function digest(value: string) { return createHash('sha256').update(value).digest('hex'); }
function stable(value: unknown): string { if (Array.isArray(value)) return `[${value.map(stable).join(',')}]`; if (value && typeof value === 'object') { const record = value as Record<string, unknown>; return `{${Object.keys(record).filter((key) => record[key] !== undefined).sort().map((key) => `${JSON.stringify(key)}:${stable(record[key])}`).join(',')}}`; } return JSON.stringify(value); }
