import { createHash } from 'node:crypto';
import type { P2Event } from './p2-federation';

export type TurnStatus = 'HEALTHY'|'ACTIVE'|'REVIEW'|'DEGRADED'|'BLOCKED'|'STOPPED'|'FAILED'|'STALE'|'UNKNOWN'|'UNAVAILABLE';
export type HardenedView = { key:string; tenantId:string; authorityId:string; aggregateId:string; revision:number; stateHash:string; eventId:string; status:TurnStatus; committedAt:string; projectedAt:string; lagMs:number; freshness:'WITHIN_SLO'|'DEGRADED'|'STALE'; integrity:'VERIFIED'; reflectionReceipt:string };
export type CustodianAudit = { auditId:string; action:string; result:string; occurredAt:string; affectedKeys:string[]; canonicalMutation:false; chainHash:string };
export type TurnPolicy = { sloMs:Record<'CRITICAL'|'LIFECYCLE'|'INFORMATIONAL',number>; hardStaleMs:Record<'CRITICAL'|'LIFECYCLE'|'INFORMATIONAL',number> };

export class HardenedTurnProjection {
  readonly #views=new Map<string,HardenedView>(); readonly #pending=new Map<string,Map<number,P2Event>>(); readonly #receipts=new Set<string>(); available=true;
  apply(event:P2Event, projectedAt:string, classification:'CRITICAL'|'LIFECYCLE'|'INFORMATIONAL', policy:TurnPolicy){ if(!this.available) return {applied:false,reason:'TURN_UNAVAILABLE'} as const; if(hasSecret(event.sanitizedPayload)) return {applied:false,reason:'SECRET_FIELD_DENIED'} as const; const key=`${event.tenantId}:${event.sourceAuthority}:${event.aggregateId}`; const current=this.#views.get(key); if(current&&event.aggregateRevision<=current.revision) return {applied:false,reason:'DUPLICATE_OR_OLD'} as const; const expected=(current?.revision??0)+1; if(event.aggregateRevision>expected){const q=this.#pending.get(key)??new Map();q.set(event.aggregateRevision,event);this.#pending.set(key,q);return {applied:false,reason:'SEQUENCE_GAP'} as const;} const view=this.make(event,projectedAt,classification,policy);this.#views.set(key,view);this.drain(key,projectedAt,classification,policy);return {applied:true,view:{...view}} as const; }
  corrupt(key:string){const v=this.#views.get(key);if(v)this.#views.set(key,Object.freeze({...v,stateHash:'CORRUPTED',status:'STALE',freshness:'STALE'}));}
  markUnavailable(){this.available=false;} markAvailable(){this.available=true;}
  replace(views:HardenedView[]){this.#views.clear();for(const v of views)this.#views.set(v.key,Object.freeze({...v}));}
  view(key:string){const v=this.#views.get(key);return v?{...v}:undefined;} all(){return [...this.#views.values()].map(v=>({...v}));} pending(){return [...this.#pending.values()].reduce((n,q)=>n+q.size,0);} clear(){this.#views.clear();this.#pending.clear();}
  snapshot(){const views=this.all();return {views,snapshotHash:hash(stable(views))};}
  restore(s:{views:HardenedView[];snapshotHash:string}){if(s.snapshotHash!==hash(stable(s.views)))throw new Error('TURN_SNAPSHOT_CORRUPT');this.replace(s.views);}
  private make(e:P2Event,at:string,c:'CRITICAL'|'LIFECYCLE'|'INFORMATIONAL',p:TurnPolicy){const lag=Math.max(0,Date.parse(at)-Date.parse(e.committedAt));const freshness=lag>p.hardStaleMs[c]?'STALE':lag>p.sloMs[c]?'DEGRADED':'WITHIN_SLO';const status=normalize(String(e.sanitizedPayload.status),freshness);const receipt=hash(stable({eventId:e.eventId,stateHash:e.currentStateHash,projectedAt:at}));this.#receipts.add(receipt);return Object.freeze({key:`${e.tenantId}:${e.sourceAuthority}:${e.aggregateId}`,tenantId:e.tenantId,authorityId:e.sourceAuthority,aggregateId:e.aggregateId,revision:e.aggregateRevision,stateHash:e.currentStateHash,eventId:e.eventId,status,committedAt:e.committedAt,projectedAt:at,lagMs:lag,freshness,integrity:'VERIFIED' as const,reflectionReceipt:receipt});}
  private drain(key:string,at:string,c:'CRITICAL'|'LIFECYCLE'|'INFORMATIONAL',p:TurnPolicy){const q=this.#pending.get(key);if(!q)return;let n=(this.#views.get(key)?.revision??0)+1;while(q.has(n)){const e=q.get(n)!;q.delete(n);this.#views.set(key,this.make(e,at,c,p));n++;}if(!q.size)this.#pending.delete(key);}
}

export class TurnStateCustodianOperational {
  readonly #audit:CustodianAudit[]=[]; available=true;
  constructor(private readonly projection:HardenedTurnProjection,private readonly policy:TurnPolicy){}
  inspect(canonical:readonly P2Event[],now:string){if(!this.available)return {status:'UNAVAILABLE',defects:['CUSTODIAN_UNAVAILABLE']};const expected=latest(canonical);const actual=new Map(this.projection.all().map(v=>[v.key,v]));const defects:string[]=[];for(const [key,e] of expected){const v=actual.get(key);if(!v)defects.push(`MISSING:${key}`);else if(v.revision!==e.aggregateRevision||v.stateHash!==e.currentStateHash)defects.push(`DRIFT:${key}`);else {const cls=classification(e);if(Date.parse(now)-Date.parse(e.committedAt)>this.policy.hardStaleMs[cls])defects.push(`STALE:${key}`);}}this.record('INSPECT',defects.length?'DEFECT':'PASS',now,defects.map(x=>x.split(':').slice(1).join(':')));return {status:defects.length?'DEFECT':'HEALTHY',defects};}
  rebuild(canonical:readonly P2Event[],now:string){if(!this.available)throw new Error('CUSTODIAN_UNAVAILABLE');const shadow=new HardenedTurnProjection();for(const e of canonical.slice().sort((a,b)=>a.sourceSequence-b.sourceSequence)){const r=shadow.apply(e,now,classification(e),this.policy);if(!r.applied&&r.reason!=='DUPLICATE_OR_OLD')throw new Error(`REBUILD_${r.reason}`);}const expected=latest(canonical);const views=shadow.all();if(views.length!==expected.size||views.some(v=>expected.get(v.key)?.currentStateHash!==v.stateHash))throw new Error('REBUILD_PARITY_FAILURE');this.projection.replace(views);this.record('SHADOW_REBUILD_ALIAS_SWITCH','PASS',now,views.map(v=>v.key));return {parity:true,count:views.length};}
  reconcile(canonical:readonly P2Event[],now:string){const before=this.inspect(canonical,now);const rebuilt=this.rebuild(canonical,now);return {before,rebuilt,canonicalMutation:false as const};}
  mutateCanonical(){throw new Error('CUSTODIAN_CANONICAL_MUTATION_DENIED');} accessSecret(){throw new Error('CUSTODIAN_SECRET_ACCESS_DENIED');} publishKnowledge(){throw new Error('CUSTODIAN_PUBLICATION_DENIED');}
  audits(){return this.#audit.map(a=>({...a,affectedKeys:[...a.affectedKeys]}));} crash(){this.available=false;} recover(){this.available=true;}
  private record(action:string,result:string,occurredAt:string,affectedKeys:string[]){const previous=this.#audit.at(-1)?.chainHash??null;const raw={action,result,occurredAt,affectedKeys,canonicalMutation:false as const,previous};const chainHash=hash(stable(raw));this.#audit.push(Object.freeze({auditId:`cust-${chainHash.slice(0,20)}`,action,result,occurredAt,affectedKeys:Object.freeze([...affectedKeys]) as unknown as string[],canonicalMutation:false,chainHash}));}
}

export function architectureGovernanceFirstView(views:HardenedView[]){const nodes=['Canonical Authorities','Signed Event Journal','Validation Gate','Deterministic Turn Projection','Turn','Atlas','Final Knowledge Inspector','Archivist','Publication Verifier','Turn State Custodian','Agent Pools','AGM BASIC — SEALED'];return {title:'ARCHITECTURE & GOVERNANCE STATUS',position:'IMMEDIATELY_AFTER_INCIDENTS',nodes:nodes.map(name=>{const match=views.find(v=>v.aggregateId===name);return {name,status:match?.status??'UNKNOWN',light:light(match?.status??'UNKNOWN'),drillDown:match?{authority:match.authorityId,revision:match.revision,stateHash:match.stateHash,eventId:match.eventId,lagMs:match.lagMs,receipt:match.reflectionReceipt}:null};})};}
function latest(events:readonly P2Event[]){const m=new Map<string,P2Event>();for(const e of events){const k=`${e.tenantId}:${e.sourceAuthority}:${e.aggregateId}`;if(!m.has(k)||m.get(k)!.aggregateRevision<e.aggregateRevision)m.set(k,e);}return m;}
function classification(e:P2Event){return (/STOP|FAIL|REVOK|INCIDENT|DENIED/.test(e.eventType)?'CRITICAL':/AGENT|DOSSIER|ATLAS|INSPECT|ARCHIV|KNOWLEDGE/.test(e.eventType)?'LIFECYCLE':'INFORMATIONAL') as 'CRITICAL'|'LIFECYCLE'|'INFORMATIONAL';}
function normalize(s:string,f:'WITHIN_SLO'|'DEGRADED'|'STALE'):TurnStatus{if(f==='STALE')return'STALE';if(f==='DEGRADED')return'DEGRADED';const allowed:TurnStatus[]=['HEALTHY','ACTIVE','REVIEW','DEGRADED','BLOCKED','STOPPED','FAILED','STALE'];return allowed.includes(s as TurnStatus)?s as TurnStatus:'UNKNOWN';}
function light(s:TurnStatus){return ({HEALTHY:'GREEN',ACTIVE:'BLUE_GREEN',REVIEW:'AMBER',DEGRADED:'YELLOW',BLOCKED:'ORANGE',STOPPED:'GREY',FAILED:'RED',STALE:'PURPLE_RED',UNKNOWN:'GREY',UNAVAILABLE:'RED'} as const)[s];}
function hasSecret(p:Record<string,unknown>){return Object.keys(p).some(k=>/secret|token|credential|password/i.test(k));}function hash(v:string){return createHash('sha256').update(v).digest('hex');}function stable(v:unknown):string{if(Array.isArray(v))return`[${v.map(stable).join(',')}]`;if(v&&typeof v==='object'){const r=v as Record<string,unknown>;return`{${Object.keys(r).filter(k=>r[k]!==undefined).sort().map(k=>`${JSON.stringify(k)}:${stable(r[k])}`).join(',')}}`;}return JSON.stringify(v);}
