import{createHash}from'node:crypto';import{RoleSigner}from'./p5-assurance';
export type MigrationRecord={legacyId:string;canonicalId:string;tenantId:string;capability:string;risk:'LOW'|'MEDIUM'|'HIGH'|'REGULATED';revision:number;state:string;payloadHash:string;provenanceHash:string;schemaVersion:string};
export type MigrationEvent={eventId:string;epoch:string;record:MigrationRecord;occurredAt:string;writerId:string;previousHash:string|null;eventHash:string;signatureKeyId:string;signature:string};
export type PhaseEvidence={phase:string;contract:string;verdict:string;artifactHash:string};
export class MigrationAuthority{
 readonly #events:MigrationEvent[]=[];readonly #ids=new Set<string>();readonly #quarantine:{legacyId:string;reason:string}[]=[];#writer:{id:string;epoch:string;fence:number}|undefined;#route:'LEGACY'|'V1_2'='LEGACY';#prior:'LEGACY'|'V1_2'='LEGACY';
 constructor(private readonly signer:RoleSigner){}
 acquireWriter(id:string,epoch:string,fence:number){if(this.#writer&&fence<=this.#writer.fence)throw new Error('STALE_WRITER_FENCE');this.#writer={id,epoch,fence};return{...this.#writer};}
 import(record:MigrationRecord,input:{writerId:string;epoch:string;fence:number;eventId:string;occurredAt:string}){this.assertWriter(input);if(this.#ids.has(input.eventId))return{status:'DUPLICATE',event:this.#events.find(e=>e.eventId===input.eventId)}as const;if(!record.legacyId||!record.canonicalId||!record.provenanceHash){this.#quarantine.push({legacyId:record.legacyId||'UNKNOWN',reason:'UNKNOWN_OR_MISSING_PROVENANCE'});return{status:'QUARANTINED',reason:'UNKNOWN_OR_MISSING_PROVENANCE'}as const;}if(record.schemaVersion!=='v1.2'){this.#quarantine.push({legacyId:record.legacyId,reason:'SCHEMA_MISMATCH'});return{status:'QUARANTINED',reason:'SCHEMA_MISMATCH'}as const;}const previousHash=this.#events.at(-1)?.eventHash??null;const core={eventId:input.eventId,epoch:input.epoch,record:{...record},occurredAt:input.occurredAt,writerId:input.writerId,previousHash};const eventHash=hash(stable(core));const unsigned={...core,eventHash,signatureKeyId:this.signer.keyId};const event=Object.freeze({...unsigned,record:Object.freeze({...record}),signature:this.signer.sign(unsigned)});this.#events.push(event);this.#ids.add(input.eventId);return{status:'IMPORTED',event:{...event,record:{...event.record}}}as const;}
 shadowParity(legacy:MigrationRecord[],cohort:{tenantId:string;capability:string;risk:'LOW'|'MEDIUM'|'HIGH'|'REGULATED'}){const source=legacy.filter(r=>r.tenantId===cohort.tenantId&&r.capability===cohort.capability&&r.risk===cohort.risk).sort(sortRecord);const target=this.#events.map(e=>e.record).filter(r=>r.tenantId===cohort.tenantId&&r.capability===cohort.capability&&r.risk===cohort.risk).sort(sortRecord);const parity=source.length===target.length&&source.every((r,i)=>stable(r)===stable(target[i]));return{parity,sourceCount:source.length,targetCount:target.length,sourceHash:hash(stable(source)),targetHash:hash(stable(target))};}
 cutover(parity:ReturnType<MigrationAuthority['shadowParity']>,writer:{id:string;epoch:string;fence:number}){this.assertWriter({writerId:writer.id,epoch:writer.epoch,fence:writer.fence});if(!parity.parity)throw new Error('CUTOVER_PARITY_REQUIRED');this.#prior=this.#route;this.#route='V1_2';return this.#route;}
 rollback(writer:{id:string;epoch:string;fence:number}){this.assertWriter({writerId:writer.id,epoch:writer.epoch,fence:writer.fence});this.#route=this.#prior;return this.#route;}
 route(){return this.#route;}events(){return this.#events.map(e=>({...e,record:{...e.record}}));}quarantine(){return this.#quarantine.map(q=>({...q}));}
 snapshot(){const events=this.events(),quarantine=this.quarantine(),writer=this.#writer?{...this.#writer}:null,route=this.#route,prior=this.#prior;return{events,quarantine,writer,route,prior,snapshotHash:hash(stable({events,quarantine,writer,route,prior}))};}
 restore(s:ReturnType<MigrationAuthority['snapshot']>){if(s.snapshotHash!==hash(stable({events:s.events,quarantine:s.quarantine,writer:s.writer,route:s.route,prior:s.prior})))throw new Error('MIGRATION_SNAPSHOT_CORRUPT');this.#events.length=0;this.#ids.clear();for(const e of s.events){this.#events.push(Object.freeze({...e,record:Object.freeze({...e.record})}));this.#ids.add(e.eventId);}this.#quarantine.length=0;this.#quarantine.push(...s.quarantine.map(q=>({...q})));this.#writer=s.writer?{...s.writer}:undefined;this.#route=s.route;this.#prior=s.prior;}
 private assertWriter(i:{writerId:string;epoch:string;fence:number}){if(!this.#writer||i.writerId!==this.#writer.id||i.epoch!==this.#writer.epoch||i.fence!==this.#writer.fence)throw new Error('WRITER_FENCED');}
}
export class ArchitectureChainValidator{validate(phases:PhaseEvidence[]){const expected=['P1','P2','P3','P4','P5','P6','P7'];if(phases.map(p=>p.phase).join(',')!==expected.join(','))return{valid:false,reason:'PHASE_CHAIN_INCOMPLETE'}as const;if(phases.some(p=>!p.contract||!p.artifactHash||!p.verdict.includes('PASS')))return{valid:false,reason:'PHASE_EVIDENCE_INVALID'}as const;const chainHash=hash(stable(phases));return{valid:true,reason:'END_TO_END_CHAIN_VALID',chainHash}as const;}}
export function migrationTurn(events:MigrationEvent[],route:string){return{status:route==='V1_2'?'ACTIVE':'REVIEW',migrationEpoch:events.at(-1)?.epoch??null,records:events.length,lastEventHash:events.at(-1)?.eventHash??null,secretFree:true,productionChanged:false};}export function createP8Signer(key:Buffer){return new RoleSigner('p8-migration-dummy',key);}function sortRecord(a:MigrationRecord,b:MigrationRecord){return a.canonicalId.localeCompare(b.canonicalId)||a.revision-b.revision;}function hash(v:string){return createHash('sha256').update(v).digest('hex');}function stable(v:unknown):string{if(Array.isArray(v))return`[${v.map(stable).join(',')}]`;if(v&&typeof v==='object'){const r=v as Record<string,unknown>;return`{${Object.keys(r).filter(k=>r[k]!==undefined).sort().map(k=>`${JSON.stringify(k)}:${stable(r[k])}`).join(',')}}`;}return JSON.stringify(v);}
