import { isBasicLanguageCode, type BasicLanguageCode } from '../language-registry';
import { createOperationalCase, transitionOperationalCase } from './operational-case.machine';
import { preserveOriginal, sha256 } from './required-document.evidence-store';
import { fieldBatchCopy } from './field-batch.i18n';
import { applyFieldBatchSync, enqueueFieldBatchTransition, flushFieldBatch } from './field-batch.sync';
import type { FieldBatchSituationId, OperationalCase } from './situation-router.types';

const IDS:FieldBatchSituationId[]=['trip-context','vehicle-safety','load-securing','tachograph-time','adr-compliance','route-compatibility','night-weather','driver-fitness','ready-gate'];
const KEY='agm.premium.field-batch-01.v1',ACTIVE='agm.premium.field-batch-01.active',LANG='agm.premium.language';
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
type Stored=Partial<Record<FieldBatchSituationId,OperationalCase>>;
const read=():Stored=>{try{return JSON.parse(localStorage.getItem(KEY)??'{}');}catch{return{};}};
class FieldBatchElement extends HTMLElement{
 private cases:Stored={};private active:FieldBatchSituationId='trip-context';private online=()=>void this.flush();
 connectedCallback(){document.documentElement.classList.add('field-batch-enabled');this.cases=read();const selected=localStorage.getItem(ACTIVE);if(IDS.includes(selected as FieldBatchSituationId))this.active=selected as FieldBatchSituationId;window.addEventListener('online',this.online);this.ensure();this.render();if(navigator.onLine)void this.flush();}
 disconnectedCallback(){window.removeEventListener('online',this.online);}
 private language(){const value=localStorage.getItem(LANG);return isBasicLanguageCode(value)?value:'ro';}
 private ensure(){if(!this.cases[this.active])this.cases[this.active]=createOperationalCase(crypto.randomUUID(),this.active,this.language());this.save();}
 private save(){localStorage.setItem(KEY,JSON.stringify(this.cases));localStorage.setItem(ACTIVE,this.active);}
 private commit(next:OperationalCase){this.cases[this.active]={...next,data:{...next.data,syncStatus:'SYNC_PENDING'}};this.save();this.render();void enqueueFieldBatchTransition(localStorage,this.cases[this.active]!,navigator.onLine).then(()=>navigator.onLine?this.flush():undefined).catch(()=>undefined);}
 private set(values:Record<string,unknown>){this.commit(transitionOperationalCase(this.cases[this.active]!,{type:'SET_DATA',values}));}
 private async flush(){const result=await flushFieldBatch({storage:localStorage}).catch(()=>({status:'offline' as const}));const current=this.cases[this.active];if(current){this.cases[this.active]=applyFieldBatchSync(current,result);this.save();this.render();}}
 private render(){const language=this.language(),copy=fieldBatchCopy[language],value=this.cases[this.active]!,text=copy.situations[this.active],answers=(value.data.answers??{}) as Record<string,string>;const complete=['condition','evidence','remediation'].every(key=>Boolean(answers[key]));const problem=Object.values(answers).includes('problem');const final=['RESOLVED','FOLLOW_UP_REQUIRED','ESCALATED','BLOCKED','RECOVERY_REQUIRED'].includes(value.state);
  const question=(key:string,label:string)=>`<fieldset><legend>${esc(label)}</legend><div class="field-batch-choices"><button data-answer="${key}:confirmed" class="${answers[key]==='confirmed'?'selected':''}">${esc(copy.yes)}</button><button data-answer="${key}:problem" class="secondary ${answers[key]==='problem'?'selected':''}">${esc(copy.problem)}</button><button data-answer="${key}:na" class="secondary ${answers[key]==='na'?'selected':''}">${esc(copy.notApplicable)}</button></div></fieldset>`;
  this.innerHTML=`<section class="pre-departure-card field-batch-flow" data-field-batch><header><div><p class="pre-departure-kicker">FIELD TEST BATCH 01 · ${IDS.indexOf(this.active)+1}/9</p><h2>${esc(copy.batch)}</h2></div><button data-new class="secondary">${esc(copy.reset)}</button></header><div class="field-batch-toolbar"><label>${esc(copy.choose)}<select data-situation>${IDS.map(id=>`<option value="${id}" ${id===this.active?'selected':''}>${esc(copy.situations[id].title)}</option>`).join('')}</select></label><label>Language<select data-language>${Object.keys(fieldBatchCopy).map(code=>`<option value="${code}" ${code===language?'selected':''}>${code.toUpperCase()}</option>`).join('')}</select></label></div><article class="field-batch-active"><h3>${esc(text.title)}</h3><p>${esc(text.focus)}</p>${question('condition',copy.check)}${question('evidence',copy.evidence)}${question('remediation',copy.remediation)}${problem?`<label>${esc(copy.severity)}<select data-severity><option value="warning" ${value.data.severity==='warning'?'selected':''}>${esc(copy.warning)}</option><option value="blocking" ${value.data.severity==='blocking'?'selected':''}>${esc(copy.blocking)}</option></select></label>`:''}<label>${esc(copy.notes)}<textarea data-notes>${esc(String(value.data.notes??''))}</textarea></label><label class="after-departure-file">${esc(copy.photo)}<input data-file type="file" accept="image/*" capture="environment"></label><label><input data-human type="checkbox" ${value.data.humanConfirmed?'checked disabled':''}> ${esc(copy.confirm)}</label><div class="field-batch-actions"><button data-result ${!complete||!value.data.humanConfirmed||final?'disabled':''}>${esc(copy.confirm)}</button><button data-follow class="secondary" ${final?'disabled':''}>${esc(copy.followUp)}</button><button data-escalate class="secondary" ${final?'disabled':''}>${esc(copy.escalate)}</button></div></article><footer><strong>${esc(copy.status)}: ${esc(String(value.data.verdict??value.state))}</strong>${value.data.syncStatus==='SYNC_PENDING'?`<p role="status">${esc(copy.syncPending)}</p>`:''}${value.state==='RECOVERY_REQUIRED'?`<p role="alert">${esc(copy.recovery)}</p>`:''}</footer><button data-slice-a class="secondary">${esc(copy.requiredDocument)}</button></section>`;
  this.querySelector<HTMLSelectElement>('[data-situation]')?.addEventListener('change',e=>{this.active=(e.target as HTMLSelectElement).value as FieldBatchSituationId;this.ensure();this.render();});this.querySelector<HTMLSelectElement>('[data-language]')?.addEventListener('change',e=>{localStorage.setItem(LANG,(e.target as HTMLSelectElement).value);this.render();});this.querySelectorAll<HTMLButtonElement>('[data-answer]').forEach(button=>button.addEventListener('click',()=>{const [key,status]=button.dataset.answer!.split(':');this.set({answers:{...answers,[key]:status}});}));this.querySelector<HTMLSelectElement>('[data-severity]')?.addEventListener('change',e=>this.set({severity:(e.target as HTMLSelectElement).value}));this.querySelector<HTMLTextAreaElement>('[data-notes]')?.addEventListener('change',e=>this.set({notes:(e.target as HTMLTextAreaElement).value}));this.querySelector<HTMLInputElement>('[data-human]')?.addEventListener('change',e=>this.set({humanConfirmed:(e.target as HTMLInputElement).checked,confirmedAt:new Date().toISOString()}));this.querySelector<HTMLInputElement>('[data-file]')?.addEventListener('change',async e=>{const file=(e.target as HTMLInputElement).files?.[0];if(!file)return;try{const id=await sha256(file);await preserveOriginal(id,file);this.commit(transitionOperationalCase(value,{type:'ADD_EVIDENCE',evidence:{id,kind:'original',sha256:id}}));}catch{this.commit(transitionOperationalCase(value,{type:'REQUIRE_RECOVERY',reason:'ORIGINAL_STORAGE_FAILED'}));}});this.querySelector<HTMLButtonElement>('[data-result]')?.addEventListener('click',()=>{const severity=String(value.data.severity??'warning'),verdict=problem?(severity==='blocking'?'BLOCKED':'FOLLOW_UP_REQUIRED'):'READY_CONFIRMED';let next=transitionOperationalCase(value,{type:'SET_DATA',values:{verdict}});next=problem?(severity==='blocking'?transitionOperationalCase(next,{type:'BLOCK'}):transitionOperationalCase(next,{type:'SET_DISPOSITION',disposition:'FOLLOW_UP_REQUIRED'})):transitionOperationalCase(next,{type:'SET_DISPOSITION',disposition:'RESOLVED'});this.commit(next);});this.querySelector<HTMLButtonElement>('[data-follow]')?.addEventListener('click',()=>this.commit(transitionOperationalCase(value,{type:'SET_DISPOSITION',disposition:'FOLLOW_UP_REQUIRED'})));this.querySelector<HTMLButtonElement>('[data-escalate]')?.addEventListener('click',()=>this.commit(transitionOperationalCase(value,{type:'SET_DISPOSITION',disposition:'ESCALATED'})));this.querySelector<HTMLButtonElement>('[data-new]')?.addEventListener('click',()=>{this.cases[this.active]=createOperationalCase(crypto.randomUUID(),this.active,language);this.save();this.render();});this.querySelector<HTMLButtonElement>('[data-slice-a]')?.addEventListener('click',()=>{document.documentElement.classList.add('show-slice-a');document.querySelector('agm-required-document')?.scrollIntoView({behavior:'smooth'});});
 }
}
customElements.define('agm-field-test-batch',FieldBatchElement);
