import { createLocalOperationalContextPorts } from '../premium-operational-context/local-adapters';
import { createOperationalEvent } from '../premium-operational-context/operational-event';
import { createActiveTripContext } from '../premium-operational-context/trip-context.service';
import { createHttpOperationalEventServer, synchronizeOperationalOutbox, type OperationalEventServerPort } from '../premium-operational-context/server-sync';
import type { OperationalCase } from './situation-router.types';
import { transitionOperationalCase } from './operational-case.machine';

const DEVICE_KEY='agm.premium.device-id.v1';let queue:Promise<unknown>=Promise.resolve();type Store=Pick<Storage,'getItem'|'setItem'|'removeItem'>;
export function enqueueFieldBatchTransition(storage:Store,value:OperationalCase,online:boolean){return serialize(async()=>{const ports=createLocalOperationalContextPorts(storage);const deviceId=device(storage);const context=await createActiveTripContext(ports,{now:()=>new Date().toISOString(),createId:()=>crypto.randomUUID(),deviceId});const moduleId=value.situationId==='road-control'||value.situationId==='required-document'||['trip-context','vehicle-safety','load-securing','tachograph-time','adr-compliance','route-compatibility','night-weather','driver-fitness','ready-gate'].includes(value.situationId)?'premium-field-batch-01':'premium-field-batch-02';const batch=moduleId.endsWith('01')?'field-batch-01':'field-batch-02';const operationId=await uuid(`${batch}:${value.id}:revision:${value.revision}`);const events=await ports.eventStore.readTrip(context.tripId);if(events.some(event=>event.eventId===operationId))return {status:'duplicate' as const,operationId};const last=events.at(-1),aggregateVersion=(last?.aggregateVersion??-1)+1;const event={...createOperationalEvent({eventId:operationId,eventType:`premium.${value.situationId}.transition.v1`,occurredAt:value.updatedAt,tripId:context.tripId,aggregateVersion,lifecycleState:context.lifecycleState,operationalFlags:[...new Set([...context.flags,'SYNC_PENDING' as const,...(!online?['OFFLINE' as const]:[])])],moduleId,actor:{type:'user'},deviceId,operationId,correlationId:await uuid(`${batch}:${value.id}`),previousEventId:last?.eventId,deviceSequence:aggregateVersion+1,payload:{caseId:value.id,situationId:value.situationId,caseRevision:value.revision,caseSnapshot:value}}),evidenceRefs:value.evidence.map(item=>item.id)};await ports.eventStore.append(event);await ports.outbox.enqueue(event);return {status:'pending' as const,operationId};});}
export function flushFieldBatch(input:{storage:Store;server?:OperationalEventServerPort}){return serialize(async()=>{const ports=createLocalOperationalContextPorts(input.storage),context=await ports.repository.readActive();if(!context)return {status:'idle' as const,acknowledged:0,conflicts:0,projection:null};return synchronizeOperationalOutbox({tripId:context.tripId,ports,server:input.server??createHttpOperationalEventServer({baseUrl:api(),token:()=>sessionStorage.getItem('agm.auth.accessToken')??localStorage.getItem('agm.auth.accessToken')}),maxAttempts:3});});}
export async function pendingFieldBatch(storage:Store){const ports=createLocalOperationalContextPorts(storage),context=await ports.repository.readActive();return context?(await ports.outbox.pending(context.tripId)).filter(event=>event.moduleId==='premium-field-batch-01'):[];}
export async function pendingAfterFieldBatch(storage:Store){const ports=createLocalOperationalContextPorts(storage),context=await ports.repository.readActive();return context?(await ports.outbox.pending(context.tripId)).filter(event=>event.moduleId==='premium-field-batch-02'):[];}
export function applyFieldBatchSync(value:OperationalCase,result:{status:string}){if(result.status==='conflict'){const next=transitionOperationalCase(value,{type:'REQUIRE_RECOVERY',reason:'SYNC_CONFLICT'});return {...next,data:{...next.data,syncStatus:'RECOVERY_REQUIRED'}};}return {...value,data:{...value.data,syncStatus:result.status==='synchronized'||result.status==='idle'?'SYNCED':'SYNC_PENDING'}};}
function serialize<T>(fn:()=>Promise<T>){const next=queue.then(fn,fn);queue=next.then(()=>undefined,()=>undefined);return next;}function device(storage:Pick<Storage,'getItem'|'setItem'>){let value=storage.getItem(DEVICE_KEY);if(!value){value=crypto.randomUUID();storage.setItem(DEVICE_KEY,value);}return value;}function api(){return(import.meta.env.VITE_AGM_API_BASE_URL?.trim()||'/api/v1').replace(/\/$/,'');}async function uuid(value:string){const b=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))).slice(0,16);b[6]=(b[6]&15)|80;b[8]=(b[8]&63)|128;const h=[...b].map(x=>x.toString(16).padStart(2,'0')).join('');return`${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;}
