import type { BasicLanguageCode } from '../language-registry';

export type RoadControlCopy = {
  title:string; safetyQuestion:string; unsafe:string; yes:string; no:string;
  safeStop:string; confirmStop:string; request:string; document:string; information:string; other:string;
  evidence:string; camera:string; import:string; ocrText:string; operator:string; confirmText:string;
  translation:string; communication:string; email:string; whatsapp:string; prepare:string; humanConfirm:string;
  prepared:string; noSend:string; notes:string; resolve:string; followUp:string; escalate:string;
  status:string; recovery:string; offline:string; reset:string;
};

export const roadControlCopy:Record<BasicLanguageCode,RoadControlCopy>={
 ro:{title:'Control rutier',safetyQuestion:'Poți interacționa în siguranță?',unsafe:'Oprește într-un loc sigur. Fluxul rămâne blocat până la o nouă confirmare.',yes:'Da',no:'Nu',safeStop:'Vehiculul este oprit în siguranță?',confirmStop:'Confirm oprirea sigură',request:'Ce solicită autoritatea?',document:'Document',information:'Informație',other:'Altă solicitare',evidence:'Dovezi contextuale',camera:'Fotografiază',import:'Importă',ocrText:'Text OCR / text extras',operator:'Identificator operator',confirmText:'Confirm că am verificat textul',translation:'Traducere contextuală',communication:'Comunicare contextuală',email:'E-mail',whatsapp:'WhatsApp',prepare:'Pregătește mesajul',humanConfirm:'Confirmă trimiterea',prepared:'Mesaj pregătit; nu a fost trimis.',noSend:'Nimic nu este trimis fără confirmare umană.',notes:'Acțiuni și observații',resolve:'Rezolvat',followUp:'Necesită urmărire',escalate:'Escaladează',status:'Stare caz',recovery:'Recuperare necesară',offline:'Offline · salvat local',reset:'Caz nou'},
 de:{title:'Verkehrskontrolle',safetyQuestion:'Können Sie sicher interagieren?',unsafe:'Halten Sie an einem sicheren Ort. Der Ablauf bleibt bis zur erneuten Bestätigung gesperrt.',yes:'Ja',no:'Nein',safeStop:'Steht das Fahrzeug sicher?',confirmStop:'Sicheren Halt bestätigen',request:'Was verlangt die Behörde?',document:'Dokument',information:'Information',other:'Andere Anfrage',evidence:'Kontextnachweise',camera:'Fotografieren',import:'Importieren',ocrText:'OCR-Text / extrahierter Text',operator:'Bedienerkennung',confirmText:'Ich bestätige die Textprüfung',translation:'Kontextübersetzung',communication:'Kontextkommunikation',email:'E-Mail',whatsapp:'WhatsApp',prepare:'Nachricht vorbereiten',humanConfirm:'Senden bestätigen',prepared:'Nachricht vorbereitet; nicht gesendet.',noSend:'Ohne menschliche Bestätigung wird nichts gesendet.',notes:'Aktionen und Notizen',resolve:'Erledigt',followUp:'Nachverfolgung nötig',escalate:'Eskalieren',status:'Fallstatus',recovery:'Wiederherstellung erforderlich',offline:'Offline · lokal gespeichert',reset:'Neuer Fall'},
 en:{title:'Road control',safetyQuestion:'Can you interact safely?',unsafe:'Stop in a safe place. The flow remains locked until you confirm again.',yes:'Yes',no:'No',safeStop:'Is the vehicle safely stopped?',confirmStop:'Confirm safe stop',request:'What does the authority request?',document:'Document',information:'Information',other:'Other request',evidence:'Contextual evidence',camera:'Take photo',import:'Import',ocrText:'OCR text / extracted text',operator:'Operator identifier',confirmText:'I confirm that I reviewed the text',translation:'Contextual translation',communication:'Contextual communication',email:'Email',whatsapp:'WhatsApp',prepare:'Prepare message',humanConfirm:'Confirm sending',prepared:'Message prepared; it has not been sent.',noSend:'Nothing is sent without human confirmation.',notes:'Actions and notes',resolve:'Resolved',followUp:'Follow-up required',escalate:'Escalate',status:'Case status',recovery:'Recovery required',offline:'Offline · saved locally',reset:'New case'},
 fr:{title:'Contrôle routier',safetyQuestion:'Pouvez-vous interagir en sécurité ?',unsafe:'Arrêtez-vous dans un lieu sûr. Le flux reste bloqué jusqu’à une nouvelle confirmation.',yes:'Oui',no:'Non',safeStop:'Le véhicule est-il arrêté en sécurité ?',confirmStop:'Confirmer l’arrêt sûr',request:'Que demande l’autorité ?',document:'Document',information:'Information',other:'Autre demande',evidence:'Preuves contextuelles',camera:'Photographier',import:'Importer',ocrText:'Texte OCR / texte extrait',operator:'Identifiant opérateur',confirmText:'Je confirme avoir vérifié le texte',translation:'Traduction contextuelle',communication:'Communication contextuelle',email:'E-mail',whatsapp:'WhatsApp',prepare:'Préparer le message',humanConfirm:'Confirmer l’envoi',prepared:'Message préparé ; non envoyé.',noSend:'Rien n’est envoyé sans confirmation humaine.',notes:'Actions et notes',resolve:'Résolu',followUp:'Suivi requis',escalate:'Escalader',status:'État du dossier',recovery:'Récupération requise',offline:'Hors ligne · enregistré localement',reset:'Nouveau dossier'},
 nl:{title:'Wegcontrole',safetyQuestion:'Kunt u veilig handelen?',unsafe:'Stop op een veilige plaats. De workflow blijft geblokkeerd tot een nieuwe bevestiging.',yes:'Ja',no:'Nee',safeStop:'Staat het voertuig veilig stil?',confirmStop:'Veilige stop bevestigen',request:'Wat vraagt de autoriteit?',document:'Document',information:'Informatie',other:'Andere vraag',evidence:'Contextueel bewijs',camera:'Foto maken',import:'Importeren',ocrText:'OCR-tekst / uitgelezen tekst',operator:'Operator-ID',confirmText:'Ik bevestig dat ik de tekst heb gecontroleerd',translation:'Contextuele vertaling',communication:'Contextuele communicatie',email:'E-mail',whatsapp:'WhatsApp',prepare:'Bericht voorbereiden',humanConfirm:'Verzenden bevestigen',prepared:'Bericht voorbereid; niet verzonden.',noSend:'Niets wordt verzonden zonder menselijke bevestiging.',notes:'Acties en notities',resolve:'Opgelost',followUp:'Opvolging vereist',escalate:'Escaleren',status:'Dossierstatus',recovery:'Herstel vereist',offline:'Offline · lokaal opgeslagen',reset:'Nieuwe zaak'},
 ru:{title:'Дорожный контроль',safetyQuestion:'Вы можете безопасно взаимодействовать?',unsafe:'Остановитесь в безопасном месте. Процесс заблокирован до нового подтверждения.',yes:'Да',no:'Нет',safeStop:'Автомобиль безопасно остановлен?',confirmStop:'Подтвердить безопасную остановку',request:'Что запрашивает орган власти?',document:'Документ',information:'Информация',other:'Другой запрос',evidence:'Контекстные доказательства',camera:'Сфотографировать',import:'Импортировать',ocrText:'Текст OCR / извлечённый текст',operator:'Идентификатор оператора',confirmText:'Подтверждаю проверку текста',translation:'Контекстный перевод',communication:'Контекстная связь',email:'Эл. почта',whatsapp:'WhatsApp',prepare:'Подготовить сообщение',humanConfirm:'Подтвердить отправку',prepared:'Сообщение подготовлено, но не отправлено.',noSend:'Без подтверждения пользователя ничего не отправляется.',notes:'Действия и заметки',resolve:'Решено',followUp:'Требуется контроль',escalate:'Эскалировать',status:'Статус дела',recovery:'Требуется восстановление',offline:'Офлайн · сохранено локально',reset:'Новое дело'},
 pl:{title:'Kontrola drogowa',safetyQuestion:'Czy możesz bezpiecznie korzystać z aplikacji?',unsafe:'Zatrzymaj się w bezpiecznym miejscu. Proces pozostaje zablokowany do ponownego potwierdzenia.',yes:'Tak',no:'Nie',safeStop:'Czy pojazd jest bezpiecznie zatrzymany?',confirmStop:'Potwierdź bezpieczne zatrzymanie',request:'Czego żąda organ?',document:'Dokument',information:'Informacja',other:'Inne żądanie',evidence:'Dowody kontekstowe',camera:'Zrób zdjęcie',import:'Importuj',ocrText:'Tekst OCR / tekst odczytany',operator:'Identyfikator operatora',confirmText:'Potwierdzam sprawdzenie tekstu',translation:'Tłumaczenie kontekstowe',communication:'Komunikacja kontekstowa',email:'E-mail',whatsapp:'WhatsApp',prepare:'Przygotuj wiadomość',humanConfirm:'Potwierdź wysłanie',prepared:'Wiadomość przygotowana; nie wysłana.',noSend:'Nic nie zostanie wysłane bez potwierdzenia użytkownika.',notes:'Działania i notatki',resolve:'Rozwiązano',followUp:'Wymaga dalszych działań',escalate:'Eskaluj',status:'Stan sprawy',recovery:'Wymagane odzyskiwanie',offline:'Offline · zapisano lokalnie',reset:'Nowa sprawa'},
 tr:{title:'Yol kontrolü',safetyQuestion:'Güvenli şekilde etkileşim kurabilir misiniz?',unsafe:'Güvenli bir yerde durun. Yeniden onaylayana kadar akış kilitli kalır.',yes:'Evet',no:'Hayır',safeStop:'Araç güvenli biçimde durdu mu?',confirmStop:'Güvenli duruşu onayla',request:'Yetkili ne talep ediyor?',document:'Belge',information:'Bilgi',other:'Diğer talep',evidence:'Bağlamsal kanıt',camera:'Fotoğraf çek',import:'İçe aktar',ocrText:'OCR metni / çıkarılan metin',operator:'Operatör kimliği',confirmText:'Metni kontrol ettiğimi onaylıyorum',translation:'Bağlamsal çeviri',communication:'Bağlamsal iletişim',email:'E-posta',whatsapp:'WhatsApp',prepare:'Mesajı hazırla',humanConfirm:'Göndermeyi onayla',prepared:'Mesaj hazırlandı; gönderilmedi.',noSend:'İnsan onayı olmadan hiçbir şey gönderilmez.',notes:'Eylemler ve notlar',resolve:'Çözüldü',followUp:'Takip gerekli',escalate:'Yönlendir',status:'Vaka durumu',recovery:'Kurtarma gerekli',offline:'Çevrimdışı · yerel kaydedildi',reset:'Yeni vaka'},
 sq:{title:'Kontroll rrugor',safetyQuestion:'A mund të ndërveproni në mënyrë të sigurt?',unsafe:'Ndaloni në një vend të sigurt. Rrjedha mbetet e bllokuar deri në një konfirmim të ri.',yes:'Po',no:'Jo',safeStop:'A është automjeti i ndalur në mënyrë të sigurt?',confirmStop:'Konfirmo ndalimin e sigurt',request:'Çfarë kërkon autoriteti?',document:'Dokument',information:'Informacion',other:'Kërkesë tjetër',evidence:'Prova kontekstuale',camera:'Fotografo',import:'Importo',ocrText:'Teksti OCR / teksti i nxjerrë',operator:'Identifikuesi i operatorit',confirmText:'Konfirmoj se e kontrollova tekstin',translation:'Përkthim kontekstual',communication:'Komunikim kontekstual',email:'E-mail',whatsapp:'WhatsApp',prepare:'Përgatit mesazhin',humanConfirm:'Konfirmo dërgimin',prepared:'Mesazhi u përgatit; nuk u dërgua.',noSend:'Asgjë nuk dërgohet pa konfirmim njerëzor.',notes:'Veprime dhe shënime',resolve:'U zgjidh',followUp:'Kërkon ndjekje',escalate:'Përshkallëzo',status:'Gjendja e rastit',recovery:'Kërkohet rikuperim',offline:'Jashtë linje · ruajtur lokalisht',reset:'Rast i ri'}
};
