SELECT 'AuditEvent' AS table_name, count(*) AS row_count FROM "AuditEvent"
UNION ALL SELECT 'BusinessValidationReport', count(*) FROM "BusinessValidationReport"
UNION ALL SELECT 'Company', count(*) FROM "Company"
UNION ALL SELECT 'EvidenceMetadata', count(*) FROM "EvidenceMetadata"
UNION ALL SELECT 'FinancialLedger', count(*) FROM "FinancialLedger"
UNION ALL SELECT 'IncidentReport', count(*) FROM "IncidentReport"
UNION ALL SELECT 'LifecycleState', count(*) FROM "LifecycleState"
UNION ALL SELECT 'Role', count(*) FROM "Role"
UNION ALL SELECT 'TransportJob', count(*) FROM "TransportJob"
UNION ALL SELECT 'TransportJobStateHistory', count(*) FROM "TransportJobStateHistory"
UNION ALL SELECT 'TurnAdminCredential', count(*) FROM "TurnAdminCredential"
UNION ALL SELECT 'User', count(*) FROM "User"
UNION ALL SELECT 'UserRole', count(*) FROM "UserRole"
UNION ALL SELECT '_prisma_migrations', count(*) FROM "_prisma_migrations"
ORDER BY table_name;
