import type { KnowledgeItem, KnowledgePackage } from './knowledge.contract';
const date = '2026-08-02'; const due = '2026-11-02';
const jurisdiction = 'Directiva 2014/47/UE: controale tehnice în trafic pentru vehiculele comerciale din sfera art. 2; Germania numai unde este indicat; ADR, dreptul național și standardele aplicabile se verifică separat';
const ref = (sourceId: string, locator: string) => ({ sourceId, locator });
const make = (id: string, topic: string, legalRule: string, practicalExplanation: string, example: string, mistake: string, sourceReferences: KnowledgeItem['sourceReferences']): KnowledgeItem => ({ id, topic, legalRule, practicalExplanation, examples: [example], commonMistakes: [mistake], sourceReferences, jurisdiction, verifiedAt: date, reviewDueAt: due });
export const cargoSecuringKnowledgePackage: KnowledgePackage = {
  id: 'KB-LEGAL-CARGO-SECURING-001', domain: 'legislation.cargo-securing', title: 'Ancorarea mărfii', jurisdiction,
  verifiedAt: date, reviewDueAt: due, version: '0.1.1', status: 'published',
  sources: [
    { id: 'EU-CARGO-001', title: 'Directiva 2014/47/UE — versiune consolidată 27.09.2022', url: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02014L0047-20220927', official: true, reachable: true, checkedAt: date, reviewDueAt: due },
    { id: 'UNECE-CTU-001', title: 'IMO/ILO/UNECE CTU Code', url: 'https://unece.org/transport/intermodal-transport/imoilounece-code-practice-packing-cargo-transport-units-ctu-code', official: true, reachable: true, checkedAt: date, reviewDueAt: due },
    { id: 'DE-STVO-022', title: 'StVO §22 — Ladung', url: 'https://www.gesetze-im-internet.de/stvo_2013/__22.html', official: true, reachable: true, checkedAt: date, reviewDueAt: due },
    { id: 'UNECE-ADR-2025', title: 'UNECE — ADR 2025', url: 'https://unece.org/transport/dangerous-goods/adr-2025-files', official: true, reachable: true, checkedAt: date, reviewDueAt: due },
  ],
  items: [
    make('LOAD-000', 'Domeniu și obiectivul controlului', 'Art. 13 reglementează verificarea securizării la controlul tehnic în trafic pentru vehiculele comerciale din art. 2, nu un cod exhaustiv al tuturor obligațiilor. În urgențe și la pornirea în rampă, poziția încărcăturii trebuie să se schimbe numai minim și încărcătura nu trebuie să iasă din spațiul ori suprafața de încărcare.', 'Verifică și dreptul național, ADR, planul și instrucțiunile aplicabile.', 'O piesă mică liberă poate ieși din spațiul de încărcare.', 'Directiva este prezentată ca regulă universală pentru orice vehicul.', [ref('EU-CARGO-001', 'art. 2; art. 13(1)')]),
    make('LOAD-001', 'Forțe de proiectare', 'Ca reper al controlului potrivit art. 13(2), anexa III indică 0,8 din greutate înainte, 0,5 lateral și 0,5 înapoi și prevenirea răsturnării, fără prejudicierea ADR și a dreptului național.', 'Folosește calculul/metoda aplicabilă; valorile nu dau automat numărul de chingi.', 'Aceeași masă cere soluții diferite după geometrie și frecare.', 'Coeficienții sunt transformați direct în număr de chingi.', [ref('EU-CARGO-001', 'art. 13(2); annex III I.1')]),
    make('LOAD-002', 'Distribuție și axe', 'Anexa III cere considerarea masei, sarcinilor maxime și minime pe axe în limitele autorizate.', 'Urmează planul și verifică centrul de greutate și sarcinile pe axe.', 'Un palet greu în spate poate descărca axa directoare.', 'Se verifică numai masa totală.', [ref('EU-CARGO-001', 'art. 13(2); annex III I.2')]),
    make('LOAD-003', 'Vehicul și puncte', 'Cerințele aplicabile privind rezistența pereților, stâlpilor și punctelor se iau în calcul când acestea sunt folosite la securizare.', 'Verifică documentația, marcajele și certificatele atunci când sunt aplicabile.', 'Prelata nu este presupusă perete portant.', 'Se folosește un punct deteriorat ori cu capacitate necunoscută.', [ref('EU-CARGO-001', 'art. 13(2); annex III I.3')]),
    make('LOAD-004', 'Metode de fixare', 'Anexa III enumeră blocarea, fixarea locală/generală, ancorarea directă și peste încărcătură, separat sau combinat.', 'Alege metoda prin planul/calculul aplicabil.', 'Blocarea și ancorarea directă sunt combinate după plan.', 'Orice chingă peste marfă este considerată suficientă.', [ref('EU-CARGO-001', 'art. 13(2); annex III I.4')]),
    make('LOAD-005', 'Echipament, LC și STF', 'Standardele aplicabile sunt referențiate în anexa III fără ca textul lor protejat să fie reprodus. LC este capacitatea relevantă pentru ancorare, în special directă; STF este forța standard de pretensionare relevantă în special la ancorarea peste încărcătură. Nu sunt interschimbabile și niciuna singură nu stabilește numărul de chingi.', 'Verifică eticheta, metoda, uzura, tăieturile, nodurile, muchiile și punctele; scoate defectele din uz.', 'LC și STF sunt citite separat și introduse numai după confirmarea etichetei.', 'LC este confundat cu STF sau folosit singur pentru un număr.', [ref('EU-CARGO-001', 'art. 13(2); annex III I.5; II.20')]),
    make('LOAD-006', 'Frecare, goluri și piese libere', 'Golurile, deplasarea și mijloacele de blocare/fixare fac parte din evaluarea anexei III.', 'Folosește frecarea ori materialele antiderapante numai în metoda și calculul validate.', 'Un gol lateral este eliminat printr-o soluție adecvată planului.', 'Covorașul antiderapant înlocuiește calculul.', [ref('EU-CARGO-001', 'art. 13(2); annex III II.20')]),
    make('LOAD-007', 'Reverificare — bună practică CTU', 'CTU Code este un cod global de bune practici neobligatoriu; poate deveni relevant prin lege, contract, instrucțiuni ori reguli modale. Anexa 7 recomandă verificarea securizării la ocazii potrivite pe ruta multimodală.', 'AGM recomandă verificarea înainte de plecare și după evenimente care pot modifica încărcarea, cu oprire sigură.', 'După o frânare puternică se verifică din nou.', 'Buna practică CTU este prezentată ca obligație autonomă a Directivei.', [ref('UNECE-CTU-001', 'CTU Code annex 7, section 4.1.8')]),
    make('LOAD-008', 'Deficiențe și măsuri la control', 'Deficiențele sunt minore, majore sau periculoase. Cele majore/periculoase se remediază înainte de reutilizarea pe drum public; art. 14(2) poate permite deplasarea la cel mai apropiat atelier în condițiile autorității, iar art. 14(3) permite restricționarea/interzicerea utilizării pentru deficiențe periculoase.', 'Urmează instrucțiunile autorității și documentează remedierea.', 'O deficiență periculoasă poate opri utilizarea.', 'Conducătorul decide singur că poate continua.', [ref('EU-CARGO-001', 'art. 14; annex III II')]),
    make('LOAD-009', 'CTU și intermodal', 'CTU Code este un cod global neobligatoriu pentru ambalare și fixare intermodală, nu o obligație juridică autonomă.', 'Consideră toate modurile și manipulările și verifică temeiul aplicabil.', 'Un container rutier-maritim este pregătit și pentru solicitările maritime.', 'Securizarea rutieră este presupusă suficientă pentru orice mod.', [ref('UNECE-CTU-001', 'scope; chapters 4–7')]),
    make('LOAD-010', 'Germania — §22 StVO', 'În Germania, marfa și echipamentele se fixează astfel încât la frânare completă ori evitare bruscă să nu alunece, se răstoarne, ruleze înainte și înapoi, cadă sau producă zgomot evitabil; se respectă regulile tehnice recunoscute.', 'Aplică numai în Germania și verifică restul traseului.', 'Se verifică și echipamentele libere.', 'Regula germană este extrapolată întregii UE.', [ref('DE-STVO-022', '§22(1)')]),
    make('LOAD-011', 'Stop și escaladare AGM', 'Ca recomandare prudentă AGM, o soluție nu se confirmă fără datele metodei aplicabile; aceasta nu este atribuită automat Directivei pentru orice lipsă.', 'Nu porni dacă lipsesc masa, metoda, frecarea, unghiurile, axele, capacitatea punctelor, etichetele ori calculul; cere planul sau specialistul.', 'Eticheta ilizibilă determină escaladarea.', 'Fotografia este tratată ca certificare.', [ref('EU-CARGO-001', 'art. 13; annex III I–II'), ref('UNECE-CTU-001', 'CTU Code annex 7')]),
    make('LOAD-012', 'Mărfuri periculoase — ADR', 'Directiva operează fără prejudicierea ADR. Pentru mărfuri periculoase se verifică ADR 2025, inclusiv 7.5.7 și 7.5.7.1, plus cerințele naționale și ale transportului concret.', 'Nu aplica numai anexa III unei încărcături ADR.', 'Marcajul mărfii periculoase declanșează verificarea ADR.', 'Anexa III este considerată înlocuitor pentru ADR.', [ref('EU-CARGO-001', 'art. 13(2)'), ref('UNECE-ADR-2025', 'part 7, 7.5.7 and 7.5.7.1')]),
  ],
  history: [{ version: '0.1.0', changedAt: date, author: 'Documentation Owner', summary: 'Candidat inițial.' }, { version: '0.1.1', changedAt: date, author: 'Documentation Owner', summary: 'Corecții Domain, Legal și QA; integrarea Premium întărită.' }],
  validation: {
    domainReviewed: true, legalReviewed: true, qaReviewed: true,
    domainValidator: 'Domain Owner Load Safety — Independent Review',
    legalValidator: 'Agent Legal — Independent Review',
    qaValidator: 'QA Editorial Independent',
    domainReviewedAt: date, legalReviewedAt: date, qaReviewedAt: date,
    holdReasons: [], contradictions: [],
  },
};
