import type { DashboardWarningSeverity } from './dashboard-warning-analysis.types';

export const dashboardWarningCatalog: Record<string, { label: string; severity: DashboardWarningSeverity; explanation: string; action: string }> = {
  'WL-001': { label: 'STOP / avertizare critică', severity: 'critical', explanation: 'Mesaj critic specific producătorului, care trebuie interpretat împreună cu mesajul instrumentației și manualul vehiculului.', action: 'Păstrează controlul și oprește când este sigur. Citește mesajul complet și nu continua fără procedura exactă.' },
  'WL-002': { label: 'Defecțiune sistem de frânare', severity: 'critical', explanation: 'Avertizarea poate privi frâna tractorului, remorcii ori presiunea pneumatică.', action: 'Redu controlat și oprește sigur. Dacă avertizarea persistă sau frânarea este anormală, nu continua și cere asistență.' },
  'WL-003': { label: 'ABS limitat sau defect', severity: 'warning', explanation: 'Funcția antiblocare a tractorului sau remorcii poate fi limitată ori indisponibilă.', action: 'Mărește distanța, evită manevrele bruște și urmează mesajul și manualul vehiculului.' },
  'WL-004': { label: 'Presiune ulei motor prea mică', severity: 'critical', explanation: 'Simbolul indică presiunea uleiului; mesajul și manualul stabilesc condiția exactă.', action: 'Oprește imediat când traficul permite, oprește motorul în siguranță și urmează procedura vehiculului.' },
  'WL-005': { label: 'Temperatură lichid de răcire prea mare', severity: 'critical', explanation: 'Simbolul indică o temperatură ridicată a lichidului de răcire.', action: 'Redu sarcina, oprește sigur și răcește conform manualului. Nu deschide sistemul fierbinte sub presiune.' },
  'WL-006': { label: 'Defecțiune alternator / încărcare', severity: 'warning', explanation: 'Sistemul de încărcare poate fi defect sau indisponibil.', action: 'Oprește controlat într-un loc sigur și solicită verificare; nu conta pe funcționare îndelungată.' },
  'WL-007': { label: 'Defecțiune motor', severity: 'warning', explanation: 'Avertizarea indică o problemă legată de motor sau emisii; severitatea exactă depinde de culoare, clipire și mesaj.', action: 'Evită sarcina mare; la clipire, fum, zgomot, pierdere de putere ori roșu, oprește sigur și cere asistență.' },
  'WL-008': { label: 'Nivel redus combustibil', severity: 'information', explanation: 'Nivelul combustibilului a ajuns la pragul stabilit de vehicul.', action: 'Planifică alimentarea sigură cât mai curând.' },
  'WL-009': { label: 'Nivel redus AdBlue / AUS 32', severity: 'warning', explanation: 'Rezerva redusă poate anunța limitări viitoare specifice vehiculului.', action: 'Citește mesajul și completează cu produs conform specificației înainte de epuizare.' },
  'WL-010': { label: 'Filtru de particule / regenerare', severity: 'warning', explanation: 'Filtrul poate solicita regenerare sau poate avea încărcare excesivă.', action: 'Urmează exact manualul și efectuează regenerarea numai în condițiile permise; la avertizare critică oprește sigur.' },
};
