param([int]$BaselineRuns=10,[int]$AbRuns=8,[int]$RequestRounds=15,[int]$Port=3100)
$ErrorActionPreference='Stop';$root=Split-Path -Parent $PSScriptRoot;$stamp=(Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ');$out=Join-Path $root "evidence/governance/copilot-v1.2/p9/controlled-reproduction/$stamp";New-Item -ItemType Directory -Path $out -Force|Out-Null
$serverTelemetry=Join-Path $out 'server-telemetry.jsonl';$env:AGM_DIAGNOSTIC_TELEMETRY_PATH=$serverTelemetry;$env:PORT="$Port";$preload=Join-Path $root 'scripts/basic-diagnostic-preload.cjs';$env:NODE_OPTIONS="--require=$preload";$apiRoot=Join-Path $root 'apps/api';$api=Start-Process pnpm.cmd -ArgumentList @('exec','ts-node','src/main.ts') -WorkingDirectory $apiRoot -RedirectStandardOutput (Join-Path $out 'api.stdout.log') -RedirectStandardError (Join-Path $out 'api.stderr.log') -WindowStyle Hidden -PassThru
$custody=[ordered]@{contract='agm-controlled-reproduction-custody.v1';startedAt=(Get-Date).ToUniversalTime().ToString('o');output=$out;apiWrapperPid=$api.Id;port=$Port;p9Initial='STOPPED';killSwitch='ACTIVE';soakRestarted=$false;officialSloMs=3000;basicModified=$false;productionModified=$false};$custody|ConvertTo-Json|Set-Content (Join-Path $out 'custody.json') -Encoding utf8
function Wait-Api{for($i=0;$i-lt 60;$i++){Start-Sleep -Milliseconds 500;$line=netstat -ano|Select-String ":$Port\s+.*LISTENING"|Select-Object -First 1;if($line){return [int](($line.ToString()-split '\s+')[-1])}}throw'DIAGNOSTIC_API_START_TIMEOUT'}
function Start-HostSampler($processId,$path,$stopSignal){$script=Join-Path $root 'scripts/Sample-ControlledReproductionHost.ps1';Start-Process powershell.exe -ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-File',$script,'-ApiPid',$processId,'-Output',$path,'-StopSignal',$stopSignal,'-ParentPid',$PID,'-SampleIntervalSeconds',5,'-MaxRuntimeMinutes',120,'-ProcessSnapshotEverySamples',30) -RedirectStandardOutput (Join-Path $out 'host-sampler.stdout.log') -RedirectStandardError (Join-Path $out 'host-sampler.stderr.log') -WindowStyle Hidden -PassThru}
function Run-Probe($mode,$run){$file=Join-Path $out "$($mode.ToLower())-$run.json";&node scripts/controlled-basic-probe.mjs $mode $run $RequestRounds "http://127.0.0.1:$Port/api/v1" $file;if($LASTEXITCODE-ne0){throw"PROBE_FAILED_$mode`_$run"}}
$apiPid=0;$sampler=$null;$p9=$null;$samplerStopSignal=Join-Path $out 'host-sampler.stop'
try{$apiPid=Wait-Api;$custody.apiPid=$apiPid;$custody.hostSampler=[ordered]@{intervalSeconds=5;processSnapshotEverySamples=30;processSnapshotIntervalSeconds=150;maxRuntimeMinutes=120;stopSignal='host-sampler.stop';priority='Normal';warmupRequired=$true};$custody|ConvertTo-Json -Depth 5|Set-Content (Join-Path $out 'custody.json') -Encoding utf8;$hostTelemetryPath=Join-Path $out 'host-telemetry.jsonl';$sampler=Start-HostSampler $apiPid $hostTelemetryPath $samplerStopSignal;for($warmup=0;$warmup-lt90;$warmup++){Start-Sleep -Seconds 1;if((Test-Path $hostTelemetryPath)-and(Get-Item $hostTelemetryPath).Length-gt0){break}};if(-not(Test-Path $hostTelemetryPath)-or(Get-Item $hostTelemetryPath).Length-eq0){throw'HOST_SAMPLER_WARMUP_TIMEOUT'};Start-Sleep -Seconds 2
  for($i=1;$i-le$BaselineRuns;$i++){Run-Probe 'BASELINE_P9_OFF' $i}
  for($i=1;$i-le$AbRuns;$i++){Run-Probe 'P9_OFF' $i}
  $p9State=Join-Path $out 'p9-controlled-active.json';$p9=Start-Process pnpm.cmd -ArgumentList @('exec','tsx','scripts/p9-controlled-active-runtime.ts',$p9State) -WorkingDirectory $root -RedirectStandardOutput (Join-Path $out 'p9-load.stdout.log') -RedirectStandardError (Join-Path $out 'p9-load.stderr.log') -WindowStyle Hidden -PassThru
  for($wait=0;$wait-lt120;$wait++){Start-Sleep -Milliseconds 250;if(Test-Path $p9State){$active=Get-Content -Raw $p9State|ConvertFrom-Json;if($active.state-eq'ACTIVE'-and$active.workers-eq4){break}}};if(-not(Test-Path $p9State)){throw 'P9_CONTROLLED_ACTIVE_START_TIMEOUT'}
  for($i=1;$i-le$AbRuns;$i++){Run-Probe 'P9_ON_CONTROLLED' $i}
}finally{if($p9-and-not$p9.HasExited){&taskkill.exe /PID $p9.Id /T /F 2>$null|Out-Null};if($sampler-and-not$sampler.HasExited){Set-Content -LiteralPath $samplerStopSignal -Value 'STOP_AFTER_CURRENT_SAMPLE' -Encoding ascii;if(-not$sampler.WaitForExit(15000)){Stop-Process -Id $sampler.Id -Force -ErrorAction SilentlyContinue}};if($apiPid){Stop-Process -Id $apiPid -Force -ErrorAction SilentlyContinue};if($api-and-not$api.HasExited){Stop-Process -Id $api.Id -Force -ErrorAction SilentlyContinue}}
&pnpm.cmd exec tsx scripts/test-copilot-v1-2-p9-pilot.ts|Out-Null;if($LASTEXITCODE-ne0){throw'P9_FINAL_KILL_SWITCH_CERTIFICATION_FAILED'}
&node scripts/analyze-controlled-reproduction.mjs $out;if($LASTEXITCODE-ne0){exit $LASTEXITCODE};Write-Output "CONTROLLED REPRODUCTION COMPLETE - $out"
