$ErrorActionPreference='Stop';$root=Split-Path -Parent $PSScriptRoot;$temp=Join-Path $root 'tmp/p9-daily-monitor-test';if(Test-Path $temp){Remove-Item -LiteralPath $temp -Recurse -Force};New-Item -ItemType Directory -Path $temp -Force|Out-Null
$killPass=Join-Path $temp 'kill-pass.json';'{"killSwitch":"PASS","orphans":0}'|Set-Content $killPass -Encoding utf8;$killFail=Join-Path $temp 'kill-fail.json';'{"killSwitch":"FAIL","orphans":1}'|Set-Content $killFail -Encoding utf8;$runner=Join-Path $PSScriptRoot 'Invoke-P9-DailyMonitor.ps1'
function Invoke-Case($name,$kill,$health,$now){$out=Join-Path $temp $name;&$runner -Mode READINESS -EvidenceRoot $out -KillSwitchPath $kill -TestHealth $health -NowUtc $now -SuppressExit|Out-Null;$record=Get-Content -Raw (Join-Path $out 'latest.json')|ConvertFrom-Json;[pscustomobject]@{name=$name;record=$record}}
$pass=Invoke-Case 'pass' $killPass 'PASS' ([datetime]'2026-08-13T06:00:00Z');if($pass.record.status-ne'PASS'-or$pass.record.turn.p9-ne'STOPPED'-or$pass.record.turn.killSwitch-ne'ACTIVE'){throw'PASS_CASE_FAILED'}
$degraded=Invoke-Case 'degraded' $killPass 'FAIL' ([datetime]'2026-08-13T06:00:00Z');if($degraded.record.status-ne'DEGRADED'-or-not$degraded.record.alert){throw'DEGRADED_CASE_FAILED'}
$failed=Invoke-Case 'failed' $killFail 'PASS' ([datetime]'2026-08-13T06:00:00Z');if($failed.record.status-ne'FAIL'-or-not$failed.record.alert){throw'FAIL_CASE_FAILED'}
$staleRoot=Join-Path $temp 'stale';&$runner -Mode READINESS -EvidenceRoot $staleRoot -KillSwitchPath $killPass -TestHealth PASS -NowUtc ([datetime]'2026-08-11T06:00:00Z') -SuppressExit|Out-Null;&$runner -Mode READINESS -EvidenceRoot $staleRoot -KillSwitchPath $killPass -TestHealth PASS -NowUtc ([datetime]'2026-08-13T06:00:01Z') -SuppressExit|Out-Null;$stale=Get-Content -Raw (Join-Path $staleRoot 'latest.json')|ConvertFrom-Json;if($stale.status-ne'STALE'-or-not$stale.alert){throw'STALE_CASE_FAILED'}
$report=[ordered]@{contract='agm-p9-daily-monitor-test.v1';testedAt=(Get-Date).ToUniversalTime().ToString('o');cases=@('PASS','DEGRADED_ALERT','FAIL_ALERT','STALE_ALERT','TURN_STOPPED','KILL_SWITCH_ACTIVE','LOCAL_EVIDENCE_ONLY');passed=7;failed=0;externalWrites=0;secretAccess=0;basicModified=$false;productionModified=$false;soakRestarted=$false;verdict='PASS'};$evidence=Join-Path $root 'evidence/governance/copilot-v1.2/p9/daily-monitor';New-Item -ItemType Directory -Path $evidence -Force|Out-Null;$report|ConvertTo-Json -Depth 6|Set-Content -LiteralPath (Join-Path $evidence 'monitor-test-report.json') -Encoding utf8
Write-Output 'DAILY SOAK MONITOR - TESTED / PASS'
