import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import type { DossierRevision } from '../packages/copilot-control-plane/src/p4-knowledge';
import type { FinalInspection } from '../packages/copilot-control-plane/src/p5-assurance';
import { ArchivistAuthority, KnowledgeLibrary, PublicationVerifierAuthority, createP6Signers, projectPublicationTurn } from '../packages/copilot-control-plane/src/p6-publication';

const out = 'evidence/governance/copilot-v1.2/p6/runtime';
const cases: { id: string; result: 'PASS' | 'FAIL'; detail: string }[] = [];
async function test(id: string, fn: () => void | Promise<void>) { try { await fn(); cases.push({ id, result: 'PASS', detail: 'validated' }); } catch (error) { cases.push({ id, result: 'FAIL', detail: error instanceof Error ? error.message : 'UNKNOWN' }); } }
const dossier = { dossierId: 'dossier-p6', tenantId: 'tenant-agm', revision: 7, revisionHash: 'rev-p5-exact', evidenceHash: 'evidence-p5-exact', contentHash: 'content-p5-exact', proposerId: 'proposer-p4', status: 'KNOWLEDGE_GATE_READY', policy: { snapshotHash: 'policy-p5-exact' } } as DossierRevision;
const inspection = { inspectionId: 'inspection-p5', dossierId: dossier.dossierId, revision: dossier.revision, revisionHash: dossier.revisionHash, evidenceHash: dossier.evidenceHash, policySnapshotHash: dossier.policy.snapshotHash, inspectorPrincipalId: 'inspector-p5', inspectorWorkloadId: 'inspector-workload-p5', result: 'APPROVED_FOR_ARCHIVE', signature: 'opaque-p5-signature' } as FinalInspection;
const inspectorVerifier = { verify: (value: FinalInspection) => value === inspection };
const signers = createP6Signers(Buffer.from('p6-archivist-dummy-key-material-00000001'), Buffer.from('p6-verifier-dummy-key-material-000000001'));
const archivist = new ArchivistAuthority(signers.archivist, inspectorVerifier, 900_000);
const verifier = new PublicationVerifierAuthority(signers.verifier, archivist);
const library = new KnowledgeLibrary(archivist, verifier);
const archivistIdentity = { principalId: 'archivist-p6', workloadId: 'archivist-workload-p6', role: 'ARCHIVIST' as const, controlDomain: 'archive' };
const verifierIdentity = { principalId: 'verifier-p6', workloadId: 'verifier-workload-p6', role: 'PUBLICATION_VERIFIER' as const, controlDomain: 'publication-verification' };
const artifact = JSON.stringify({ answer: 'validated knowledge' }); const index = JSON.stringify({ terms: ['validated'] }); const readPath = '/knowledge/dossier-p6/v7';
const makeManifest = (id: string, artifactId: string, nonce: string, now: string, content = artifact) => archivist.createManifest({ identity: archivistIdentity, dossier, inspection, manifestId: id, artifactId, artifact: content, index, readPath, semanticMetadata: { locale: 'ro', risk: 'LOW' }, visibility: 'TENANT', nonce, now });

async function main() {
  let manifest!: ReturnType<typeof makeManifest>; let receipt!: ReturnType<typeof verifier.verifyAndAttest>;
  await test('exact-approved-manifest-pass', () => { manifest = makeManifest('manifest-p6-1', 'artifact-p6-v1', 'nonce-p6-1', '2026-08-13T21:00:00.000Z'); assert.equal(archivist.verify(manifest), true); library.approved(manifest, '2026-08-13T21:00:01.000Z'); });
  await test('archivist-cannot-activate', () => assert.throws(() => archivist.activate(), /ARCHIVIST_CANNOT_ACTIVATE/));
  await test('invalid-final-inspection-denied', () => assert.throws(() => archivist.createManifest({ identity: archivistIdentity, dossier, inspection: { ...inspection }, manifestId: 'bad', artifactId: 'bad', artifact, index, readPath, semanticMetadata: {}, visibility: 'TENANT', nonce: 'bad', now: '2026-08-13T21:00:00.000Z' }), /EXACT_FINAL_INSPECTION_REQUIRED/));
  await test('archivist-separation-of-duties', () => assert.throws(() => archivist.createManifest({ identity: { ...archivistIdentity, principalId: inspection.inspectorPrincipalId }, dossier, inspection, manifestId: 'sod', artifactId: 'sod', artifact, index, readPath, semanticMetadata: {}, visibility: 'TENANT', nonce: 'sod', now: '2026-08-13T21:00:00.000Z' }), /ARCHIVIST_SOD_VIOLATION/));
  await test('atomic-archive-commit', () => { library.commit(manifest, artifact, index, readPath, '2026-08-13T21:00:02.000Z'); assert.equal(library.archived(manifest.artifactId)?.status, 'ARCHIVE_COMMITTED'); });
  await test('partial-write-and-index-failure-denied', () => { const m = makeManifest('manifest-fault', 'artifact-fault', 'nonce-fault', '2026-08-13T21:00:03.000Z'); assert.throws(() => library.commit(m, artifact, index, readPath, '2026-08-13T21:00:04.000Z', 'PARTIAL_WRITE'), /PARTIAL_WRITE/); assert.equal(library.archived(m.artifactId), undefined); });
  await test('artifact-index-readpath-hash-mismatch-denied', () => { assert.throws(() => verifier.verifyAndAttest({ identity: verifierIdentity, manifest, artifact: `${artifact}x`, index, readPath, receiptId: 'bad-hash', nonce: 'bad-hash', now: '2026-08-13T21:00:05.000Z' }), /ARTIFACT_HASH_MISMATCH/); });
  await test('independent-verifier-receipt-pass', () => { library.beginVerification(manifest, '2026-08-13T21:00:06.000Z'); receipt = verifier.verifyAndAttest({ identity: verifierIdentity, manifest, artifact, index, readPath, receiptId: 'receipt-p6-1', nonce: 'receipt-p6-1', now: '2026-08-13T21:00:07.000Z' }); assert.equal(verifier.verify(receipt), true); });
  await test('verifier-unavailable-never-active', () => { const m = makeManifest('manifest-pending', 'artifact-pending', 'nonce-pending', '2026-08-13T21:01:00.000Z'); library.approved(m, '2026-08-13T21:01:01.000Z'); library.commit(m, artifact, index, readPath, '2026-08-13T21:01:02.000Z'); assert.equal(library.archived(m.artifactId)?.status, 'ARCHIVE_COMMITTED'); });
  await test('single-verifier-activation-pass', () => { library.activate(receipt, '2026-08-13T21:00:08.000Z'); assert.equal(library.active(dossier.tenantId)?.status, 'ACTIVE_KNOWLEDGE'); });
  await test('replayed-publication-denied', () => assert.throws(() => verifier.verifyAndAttest({ identity: verifierIdentity, manifest, artifact, index, readPath, receiptId: 'receipt-p6-1', nonce: 'other', now: '2026-08-13T21:00:09.000Z' }), /PUBLICATION_REPLAY/));
  await test('semantic-metadata-tampering-denied', () => { const tampered = { ...manifest, semanticMetadataHash: 'tampered' }; assert.throws(() => library.commit(tampered, artifact, index, readPath, '2026-08-13T21:00:10.000Z'), /INVALID_MANIFEST/); });
  await test('supersession-and-atomic-alias', () => { const artifact2 = JSON.stringify({ answer: 'validated knowledge v2' }); const m2 = makeManifest('manifest-p6-2', 'artifact-p6-v2', 'nonce-p6-2', '2026-08-13T21:02:00.000Z', artifact2); library.approved(m2, '2026-08-13T21:02:01.000Z'); library.commit(m2, artifact2, index, readPath, '2026-08-13T21:02:02.000Z'); const r2 = verifier.verifyAndAttest({ identity: verifierIdentity, manifest: m2, artifact: artifact2, index, readPath, receiptId: 'receipt-p6-2', nonce: 'receipt-p6-2', now: '2026-08-13T21:02:03.000Z' }); library.activate(r2, '2026-08-13T21:02:04.000Z'); assert.equal(library.active(dossier.tenantId)?.manifest.artifactId, 'artifact-p6-v2'); assert.equal(library.archived('artifact-p6-v1')?.status, 'SUPERSEDED'); });
  await test('rollback-active-alias-pass', () => { library.rollbackAlias(dossier.tenantId, '2026-08-13T21:03:00.000Z'); assert.equal(library.active(dossier.tenantId)?.manifest.artifactId, 'artifact-p6-v1'); });
  await test('retraction-and-expiry-pass', () => { library.retract('artifact-p6-v1', '2026-08-13T21:04:00.000Z'); assert.equal(library.active(dossier.tenantId), undefined); const m = makeManifest('manifest-expire', 'artifact-expire', 'nonce-expire', '2026-08-13T21:04:01.000Z'); library.commit(m, artifact, index, readPath, '2026-08-13T21:04:02.000Z'); library.expire(m.artifactId, '2026-08-13T21:04:03.000Z'); assert.equal(library.archived(m.artifactId)?.status, 'EXPIRED'); });
  await test('restart-reconstruction-parity', () => { const snapshot = library.snapshot(); const restored = new KnowledgeLibrary(archivist, verifier); restored.restore(snapshot); assert.deepEqual(restored.snapshot(), snapshot); });
  await test('turn-reflects-publication-without-content', () => { const turn = projectPublicationTurn(library.events()); assert.ok(turn.some((view) => view.status === 'ACTIVE_KNOWLEDGE')); assert.equal(JSON.stringify(turn).includes('validated knowledge'), false); });
  await test('turn-is-derived-and-canonical-unchanged', () => { const before = library.snapshot(); const projected = projectPublicationTurn(library.events()); projected[0]!.status = 'RETRACTED'; assert.deepEqual(library.snapshot(), before); });
  await mkdir(out, { recursive: true }); const failed = cases.filter((item) => item.result === 'FAIL'); const report = { contract: 'agm-copilot-v1.2-p6-publication-evidence.v1', generatedAt: new Date().toISOString(), cases, totals: { cases: cases.length, passed: cases.length - failed.length, failed: failed.length }, archiveEvents: library.events().length, turnViews: projectPublicationTurn(library.events()).length, activeAlias: library.active(dossier.tenantId)?.manifest.artifactId ?? null, p7Opened: false, secretMode: 'DUMMY_ONLY_NO_REAL_SECRET', verdict: failed.length ? 'FAIL' : 'PASS' };
  await writeFile(`${out}/publication-report.json`, `${JSON.stringify(report, null, 2)}\n`); await writeFile(`${out}/publish-manifest.json`, `${JSON.stringify(manifest, null, 2)}\n`); await writeFile(`${out}/publication-receipt.json`, `${JSON.stringify(receipt, null, 2)}\n`); await writeFile(`${out}/library-snapshot.json`, `${JSON.stringify(library.snapshot(), null, 2)}\n`);
  console.log(`P6 ARCHIVIST / VERIFIER / LIBRARY — ${report.verdict} (${report.totals.passed}/${report.totals.cases})`); if (failed.length) { console.error(failed); process.exitCode = 1; }
}
void main();
