import assert from 'node:assert/strict';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { KnowledgeDossierStore, RiskRouter, type EvidenceReference, type VerdictRecord } from '../packages/copilot-control-plane/src/p4-knowledge';
import { AtlasCompletenessAuthority, FinalKnowledgeInspectorAuthority, KnowledgeGateAggregationAuthority, P5AssuranceWorkflow, createP5Signers, type AssuranceIdentity } from '../packages/copilot-control-plane/src/p5-assurance';
import { AuthorityKeyRegistry, DurableSignedJournal, FederatedCanonicalAuthority, FederatedTurnProjection, P2ValidationGate, projectValidated, type AuthorityDefinition } from '../packages/copilot-control-plane/src/p2-federation';

async function main() {
  const policy = JSON.parse(await readFile('config/copilot-v1.2/p4-knowledge-policy.json', 'utf8'));
  const assurancePolicy = JSON.parse(await readFile('config/copilot-v1.2/p5-assurance-policy.json', 'utf8'));
  const router = new RiskRouter(policy); const dossierStore = new KnowledgeDossierStore(router);
  const evidence: EvidenceReference[] = [{ evidenceId: 'p5-official', sourceUri: 'https://official.example.invalid/p5', sourceType: 'OFFICIAL', contentHash: 'official-p5-hash', capturedAt: '2026-08-13T20:00:00.000Z', provenance: 'official-test-fixture' }];
  dossierStore.create({ dossierId: 'dossier-p5', tenantId: 'tenant-agm-p2-isolated', proposerId: 'proposer-p5', title: 'P5 Knowledge', content: 'Validated P5 content', evidence, provenance: 'P5 fixture', riskClass: 'LOW', now: '2026-08-13T20:00:00.000Z' });
  dossierStore.transition('dossier-p5', 1, 'ANALYSIS', '2026-08-13T20:00:01.000Z'); const source = dossierStore.transition('dossier-p5', 1, 'DOMAIN_VALIDATION', '2026-08-13T20:00:02.000Z');
  const submit = (domain: 'FUNCTIONAL' | 'SOURCE_EVIDENCE', reviewerId: string) => dossierStore.submitVerdict({ verdictId: `verdict-${domain}`, dossierId: source.dossierId, revision: source.revision, revisionHash: source.revisionHash, evidenceHash: source.evidenceHash, reviewerId, reviewerWorkloadId: `workload-${reviewerId}`, domain, verdict: 'PASS', reasonCode: 'P5_PASS', occurredAt: '2026-08-13T20:00:03.000Z' });
  submit('FUNCTIONAL', 'validator-functional'); submit('SOURCE_EVIDENCE', 'validator-source'); const verdicts = dossierStore.verdicts(source.dossierId);
  const target = dossierStore.aggregate(source.dossierId, source.revision, '2026-08-13T20:00:04.000Z').dossier;
  const signers = createP5Signers(Buffer.from('p5-aggregation-dummy-key-isolated-only-000000'), Buffer.from('p5-atlas-dummy-key-isolated-only-000000000000'), Buffer.from('p5-inspector-dummy-key-isolated-only-000000000'));
  const aggregation = new KnowledgeGateAggregationAuthority(signers.aggregation); const atlasAuthority = new AtlasCompletenessAuthority(signers.atlas, assurancePolicy.attestationTtlMs, aggregation); const inspectorAuthority = new FinalKnowledgeInspectorAuthority(signers.inspector, atlasAuthority); const workflow = new P5AssuranceWorkflow(atlasAuthority, inspectorAuthority);
  const atlas: AssuranceIdentity = { principalId: 'atlas-principal', workloadId: 'atlas-workload', role: 'ATLAS_APPROVER', controlDomain: 'atlas-domain' }; const inspector: AssuranceIdentity = { principalId: 'inspector-principal', workloadId: 'inspector-workload', role: 'FINAL_INSPECTOR', controlDomain: 'inspection-domain' }; const owner: AssuranceIdentity = { principalId: 'owner-principal', workloadId: 'owner-workload', role: 'OWNER_ADMIN', controlDomain: 'owner-domain' };
  const cases: Array<{ id: string; result: 'PASS' | 'FAIL'; detail: string }> = []; const test = async (id: string, fn: () => void | Promise<void>) => { try { await fn(); cases.push({ id, result: 'PASS', detail: 'validated' }); } catch (error) { cases.push({ id, result: 'FAIL', detail: error instanceof Error ? error.message : 'UNKNOWN' }); } };
  let receipt!: ReturnType<typeof aggregation.issue>; let atlasOk!: ReturnType<typeof atlasAuthority.review>;

  await test('valid-aggregation-receipt-and-new-hash-binding', () => { receipt = aggregation.issue({ receiptId: 'receipt-p5-1', nonce: 'nonce-receipt-1', source, target, verdicts, issuedAt: '2026-08-13T20:00:05.000Z' }); assert.notEqual(receipt.sourceRevisionHash, receipt.targetRevisionHash); assert.equal(receipt.sourceContentHash, receipt.targetContentHash); assert.equal(aggregation.verify(receipt, target, verdicts).valid, true); });
  await test('altered-verdict-denied', () => { const altered = verdicts.map((item, index) => index === 0 ? { ...item, verdict: 'REJECT' as const } : item); assert.deepEqual(aggregation.verify(receipt, target, altered), { valid: false, reason: 'VERDICT_BINDING_MISMATCH' }); });
  await test('stale-source-revision-denied', () => { assert.throws(() => aggregation.issue({ receiptId: 'receipt-stale', nonce: 'nonce-stale', source: { ...source, revision: 0 }, target, verdicts, issuedAt: '2026-08-13T20:00:05.000Z' }), /STALE_SOURCE_REVISION/); });
  await test('mismatched-policy-snapshot-denied', () => { assert.throws(() => aggregation.issue({ receiptId: 'receipt-policy', nonce: 'nonce-policy', source, target: { ...target, policy: { ...target.policy, snapshotHash: 'mismatch' } }, verdicts, issuedAt: '2026-08-13T20:00:05.000Z' }), /AGGREGATION_CONTENT_POLICY_MISMATCH/); });
  await test('forged-validator-identity-denied', () => { const forged = verdicts.map((item, index) => index === 0 ? { ...item, reviewerId: 'forged-reviewer' } : item); const forgedReceipt = { ...receipt, consumedVerdictsHash: receipt.consumedVerdictsHash }; assert.deepEqual(aggregation.verify(forgedReceipt, target, forged), { valid: false, reason: 'VERDICT_BINDING_MISMATCH' }); });
  await test('missing-source-hash-denied', () => { assert.throws(() => aggregation.issue({ receiptId: 'receipt-missing', nonce: 'nonce-missing', source: { ...source, evidenceHash: '' }, target, verdicts, issuedAt: '2026-08-13T20:00:05.000Z' }), /SOURCE_HASH_MISSING/); });
  await test('replayed-aggregation-denied', () => { assert.throws(() => aggregation.issue({ receiptId: 'receipt-p5-1', nonce: 'nonce-receipt-2', source, target, verdicts, issuedAt: '2026-08-13T20:00:06.000Z' }), /AGGREGATION_REPLAY/); assert.throws(() => aggregation.issue({ receiptId: 'receipt-p5-2', nonce: 'nonce-receipt-1', source, target, verdicts, issuedAt: '2026-08-13T20:00:06.000Z' }), /AGGREGATION_REPLAY/); });
  await test('forged-aggregation-signature-denied', () => { assert.deepEqual(aggregation.verify({ ...receipt, signature: '00'.repeat(32) }, target, verdicts), { valid: false, reason: 'FORGED_AGGREGATION_RECEIPT' }); });
  await test('atlas-exact-hash-verification-pass', () => { workflow.start(target, '2026-08-13T20:00:06.000Z'); atlasOk = atlasAuthority.review({ identity: atlas, dossier: target, verdicts, aggregationReceipt: receipt, attestationId: 'atlas-p5-1', nonce: 'atlas-nonce-1', now: '2026-08-13T20:00:07.000Z' }); assert.equal(atlasOk.result, 'ATLAS_OK'); assert.equal(atlasAuthority.verify(atlasOk), true); workflow.acceptAtlas(target, atlasOk, '2026-08-13T20:00:08.000Z'); });
  await test('atlas-unavailable-or-crash-cannot-advance', () => { const isolatedWorkflow = new P5AssuranceWorkflow(atlasAuthority, inspectorAuthority); isolatedWorkflow.start(target, '2026-08-13T20:01:00.000Z'); assert.equal(isolatedWorkflow.state(target.dossierId)?.status, 'ATLAS_REVIEW'); assert.throws(() => isolatedWorkflow.beginInspection(target, '2026-08-13T20:01:01.000Z'), /ATLAS_OK_REQUIRED/); });
  await test('atlas-cannot-self-collide-or-bypass', () => { assert.throws(() => atlasAuthority.review({ identity: { ...atlas, principalId: target.proposerId }, dossier: target, verdicts, aggregationReceipt: receipt, attestationId: 'atlas-collision', nonce: 'atlas-collision', now: '2026-08-13T20:00:07.000Z' }), /SOD_PRINCIPAL_COLLISION/); });
  await test('forged-duplicate-stale-atlas-denied', () => { assert.equal(atlasAuthority.verify({ ...atlasOk, signature: '00'.repeat(32) }), false); assert.throws(() => inspectorAuthority.inspect({ identity: inspector, dossier: target, verdicts, attestation: atlasOk, inspectionId: 'inspection-stale', nonce: 'inspection-stale', now: '2026-08-13T20:10:00.000Z', result: 'APPROVED_FOR_ARCHIVE', reasonCode: 'STALE' }), /STALE_ATLAS_OK/); });
  await test('dossier-modified-after-atlas-ok-denied', () => { assert.throws(() => inspectorAuthority.inspect({ identity: inspector, dossier: { ...target, revisionHash: 'modified-after-atlas' }, verdicts, attestation: atlasOk, inspectionId: 'inspection-modified', nonce: 'inspection-modified', now: '2026-08-13T20:00:09.000Z', result: 'APPROVED_FOR_ARCHIVE', reasonCode: 'MODIFIED' }), /DOSSIER_ATTESTATION_BINDING_MISMATCH/); });
  await test('inspector-independent-and-approved-for-archive', () => { workflow.beginInspection(target, '2026-08-13T20:00:09.000Z'); const result = inspectorAuthority.inspect({ identity: inspector, dossier: target, verdicts, attestation: atlasOk, inspectionId: 'inspection-p5-1', nonce: 'inspection-nonce-1', now: '2026-08-13T20:00:10.000Z', result: 'APPROVED_FOR_ARCHIVE', reasonCode: 'FULL_DOSSIER_VERIFIED' }); assert.equal(inspectorAuthority.verify(result), true); workflow.acceptInspection(target, result, '2026-08-13T20:00:11.000Z'); assert.equal(workflow.state(target.dossierId)?.status, 'APPROVED_FOR_ARCHIVE'); });
  await test('atlas-attestation-replay-denied', () => { assert.throws(() => inspectorAuthority.inspect({ identity: inspector, dossier: target, verdicts, attestation: atlasOk, inspectionId: 'inspection-replay', nonce: 'inspection-replay', now: '2026-08-13T20:00:12.000Z', result: 'APPROVED_FOR_ARCHIVE', reasonCode: 'REPLAY' }), /ATLAS_ATTESTATION_REPLAY/); });
  await test('inspector-unavailable-or-crash-does-not-approve', () => { const signers2 = createP5Signers(Buffer.from('p5-aggregation-dummy-key-isolated-only-000001'), Buffer.from('p5-atlas-dummy-key-isolated-only-000000000001'), Buffer.from('p5-inspector-dummy-key-isolated-only-000000001')); const agg2 = new KnowledgeGateAggregationAuthority(signers2.aggregation); const atlas2 = new AtlasCompletenessAuthority(signers2.atlas, assurancePolicy.attestationTtlMs, agg2); const inspector2 = new FinalKnowledgeInspectorAuthority(signers2.inspector, atlas2); const workflow2 = new P5AssuranceWorkflow(atlas2, inspector2); const receipt2 = agg2.issue({ receiptId: 'receipt2', nonce: 'receipt2', source, target, verdicts, issuedAt: '2026-08-13T20:02:00.000Z' }); const att2 = atlas2.review({ identity: atlas, dossier: target, verdicts, aggregationReceipt: receipt2, attestationId: 'atlas2', nonce: 'atlas2', now: '2026-08-13T20:02:01.000Z' }); workflow2.start(target, '2026-08-13T20:02:02.000Z'); workflow2.acceptAtlas(target, att2, '2026-08-13T20:02:03.000Z'); workflow2.beginInspection(target, '2026-08-13T20:02:04.000Z'); assert.equal(workflow2.state(target.dossierId)?.status, 'FINAL_INSPECTION'); });
  await test('owner-break-glass-produces-owner-review-only', () => { const isolated = new P5AssuranceWorkflow(atlasAuthority, inspectorAuthority); const event = isolated.breakGlass(target, owner, '2026-08-13T20:03:00.000Z'); assert.equal(event.status, 'OWNER_REVIEW'); assert.notEqual(isolated.state(target.dossierId)?.status, 'APPROVED_FOR_ARCHIVE'); });
  await test('active-knowledge-impossible-in-p5', () => { assert.throws(() => workflow.activateKnowledge(), /ACTIVE_KNOWLEDGE_FORBIDDEN_IN_P5/); });
  await test('workflow-snapshot-restart-chain-of-custody', () => { const snapshot = workflow.snapshot(); const restored = new P5AssuranceWorkflow(atlasAuthority, inspectorAuthority); restored.restore(snapshot); assert.deepEqual(restored.state(target.dossierId), workflow.state(target.dossierId)); assert.equal(restored.events().at(-1)?.chainHash, workflow.events().at(-1)?.chainHash); assert.throws(() => restored.restore({ ...snapshot, events: snapshot.events.slice(1) }), /ASSURANCE_SNAPSHOT_INTEGRITY_FAILURE/); });

  const p2Catalog = JSON.parse(await readFile('config/copilot-v1.2/p2-authority-catalog.json', 'utf8')) as { tenant: string; authorities: AuthorityDefinition[] }; const definition = p2Catalog.authorities.find((item) => item.id === 'WORKFLOW_STATE_AUTHORITY')!; const keys = new AuthorityKeyRegistry(); keys.register(definition.id, 'p5-workflow-key', Buffer.from('p5-workflow-dummy-key-isolated-only-0000000000')); const authority = new FederatedCanonicalAuthority(definition, { authorityId: definition.id, workloadId: 'p5-workflow-authority', tenantId: p2Catalog.tenant, keyId: 'p5-workflow-key' }, keys); const gate = new P2ValidationGate(p2Catalog.authorities, keys, p2Catalog.tenant); const journal = new DurableSignedJournal(); const projection = new FederatedTurnProjection();
  await test('aggregation-and-all-p5-states-journaled-validated-reflected', () => { const receiptEvent = authority.transition({ eventId: 'p5-receipt-event', eventType: 'workflow.knowledge_gate_receipt_issued', aggregateId: target.dossierId, status: 'KNOWLEDGE_GATE_READY', committedAt: receipt.issuedAt, correlationId: receipt.receiptId }); assert.deepEqual(projectValidated(receiptEvent.event, gate, journal, projection, '2026-08-13T20:00:05.250Z'), { status: 'REFLECTED', reason: 'VALIDATED' }); workflow.events().forEach((event, index) => { const canonical = authority.transition({ eventId: `p5-assurance-${index + 1}`, eventType: 'workflow.assurance_state_changed', aggregateId: event.dossierId, status: event.status, committedAt: event.occurredAt, correlationId: event.eventId }); assert.deepEqual(projectValidated(canonical.event, gate, journal, projection, new Date(Date.parse(event.occurredAt) + 250).toISOString()), { status: 'REFLECTED', reason: 'VALIDATED' }); }); assert.equal(journal.events().length, workflow.events().length + 1); assert.equal(projection.view(`WORKFLOW_STATE_AUTHORITY:${target.dossierId}`)?.status, 'APPROVED_FOR_ARCHIVE'); });
  await test('turn-rebuild-and-no-secret-authority', () => { const replayGate = new P2ValidationGate(p2Catalog.authorities, keys, p2Catalog.tenant); const replay = new FederatedTurnProjection(); for (const event of journal.events()) { assert.equal(replayGate.validate(event, true).valid, true); replay.apply(event, '2026-08-13T20:20:00.000Z'); } assert.equal(replay.view(`WORKFLOW_STATE_AUTHORITY:${target.dossierId}`)?.stateHash, projection.view(`WORKFLOW_STATE_AUTHORITY:${target.dossierId}`)?.stateHash); assert.equal(/secret|token|credential|password/i.test(JSON.stringify(replay.all())), false); assert.equal('transition' in replay, false); });

  const failures = cases.filter((item) => item.result === 'FAIL'); const report = { contract: 'agm-copilot-v1.2-p5-assurance-evidence.v1', generatedAt: new Date().toISOString(), cases, totals: { cases: cases.length, passed: cases.length - failures.length, failed: failures.length }, custody: { sourceRevisionHash: receipt.sourceRevisionHash, targetRevisionHash: receipt.targetRevisionHash, receiptValid: aggregation.verify(receipt, target, verdicts).valid, atlasValid: atlasAuthority.verify(atlasOk) }, workflow: { events: workflow.events().length, finalStatus: workflow.state(target.dossierId)?.status, activeKnowledgePossible: false }, turn: { journalEvents: journal.events().length, finalStatus: projection.view(`WORKFLOW_STATE_AUTHORITY:${target.dossierId}`)?.status }, p6Opened: false, secretMode: 'DUMMY_ONLY_NO_REAL_SECRET', verdict: failures.length === 0 ? 'PASS' : 'FAIL' };
  await mkdir('evidence/governance/copilot-v1.2/p5/runtime', { recursive: true }); await writeFile('evidence/governance/copilot-v1.2/p5/runtime/assurance-report.json', `${JSON.stringify(report, null, 2)}\n`); await writeFile('evidence/governance/copilot-v1.2/p5/runtime/aggregation-receipt.json', `${JSON.stringify(receipt, null, 2)}\n`); await writeFile('evidence/governance/copilot-v1.2/p5/runtime/assurance-snapshot.json', `${JSON.stringify(workflow.snapshot(), null, 2)}\n`);
  console.log(`P5 CUSTODY / ATLAS / FINAL INSPECTOR — ${report.verdict} (${report.totals.passed}/${report.totals.cases})`); console.log(`final=${report.workflow.finalStatus} turn=${report.turn.finalStatus} active=${report.workflow.activeKnowledgePossible}`); if (failures.length) process.exitCode = 1;
}
main().catch((error) => { console.error(error instanceof Error ? error.message : 'P5_TEST_FAILURE'); process.exitCode = 1; });
