import assert from 'node:assert/strict';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { DeclarativeAgentRegistry, EphemeralDossierRuntime, RuntimeAdmissionController, assertSafeParkingDescriptor, type AgentDeclaration } from '../packages/copilot-control-plane/src/p3-runtime';
import { AuthorityKeyRegistry, DurableSignedJournal, FederatedCanonicalAuthority, FederatedTurnProjection, P2ValidationGate, projectValidated, type AuthorityDefinition } from '../packages/copilot-control-plane/src/p2-federation';

async function main() {
  const registryInput = JSON.parse(await readFile('config/copilot-v1.2/p3-agent-registry.json', 'utf8')) as { version: string; agents: AgentDeclaration[] };
  const p2Catalog = JSON.parse(await readFile('config/copilot-v1.2/p2-authority-catalog.json', 'utf8')) as { tenant: string; authorities: AuthorityDefinition[] };
  const registry = new DeclarativeAgentRegistry(registryInput.version);
  const declaration = registry.register(registryInput.agents[0]);
  const admission = new RuntimeAdmissionController(registry);
  const runtime = new EphemeralDossierRuntime(admission);
  const cases: Array<{ id: string; result: 'PASS' | 'FAIL'; detail: string }> = [];
  const test = async (id: string, fn: () => void | Promise<void>) => { try { await fn(); cases.push({ id, result: 'PASS', detail: 'validated' }); } catch (error) { cases.push({ id, result: 'FAIL', detail: error instanceof Error ? error.message : 'UNKNOWN' }); } };
  const allowed = { agentId: declaration.agentId, tenantId: p2Catalog.tenant, dossierId: 'dossier-p3-001', riskClass: 'LOW', capabilities: ['STATUS_READ'], tools: ['CANONICAL_STATUS_READER'], now: '2026-08-13T16:00:00.000Z', leaseMs: 30_000 };
  let primaryWorker = '';

  await test('declarative-registry-hash-and-version', () => { assert.equal(declaration.registryVersion, 'p3.1.0'); assert.equal(declaration.declarationHash.length, 64); assert.equal(declaration.status, 'REGISTERED'); });
  await test('unsafe-lifecycle-declaration-denied', () => { assert.throws(() => registry.register({ ...registryInput.agents[0], agentId: 'unsafe', dossierScoped: false as true }), /P3_UNSAFE_LIFECYCLE_DECLARATION/); });
  await test('deny-unregistered-agent', () => { assert.equal(admission.evaluate({ ...allowed, agentId: 'unknown' }).reason, 'AGENT_NOT_ACTIVE'); });
  await test('deny-wrong-tenant-risk-capability-tool', () => {
    assert.equal(admission.evaluate({ ...allowed, tenantId: 'other' }).reason, 'TENANT_DENIED');
    assert.equal(admission.evaluate({ ...allowed, riskClass: 'HIGH' }).reason, 'RISK_DENIED');
    assert.equal(admission.evaluate({ ...allowed, capabilities: ['WRITE'] }).reason, 'CAPABILITY_DENIED');
    assert.equal(admission.evaluate({ ...allowed, tools: ['SECRET_STORE'] }).reason, 'TOOL_DENIED');
  });
  await test('ephemeral-dossier-worker-start', () => { const session = runtime.start(allowed); primaryWorker = session.workerId; assert.equal(session.state, 'STARTED'); assert.equal(session.dossierId, allowed.dossierId); assert.match(session.credentialId, /^ephemeral-/); assert.equal(runtime.commit(session.workerId, session.lease.fence, '2026-08-13T16:00:01.000Z').accepted, true); });
  await test('duplicate-activation-fences-old-worker', () => { const old = runtime.session(primaryWorker)!; const replacement = runtime.start({ ...allowed, now: '2026-08-13T16:00:02.000Z' }); assert.ok(replacement.lease.fence > old.lease.fence); assert.throws(() => runtime.commit(primaryWorker, old.lease.fence, '2026-08-13T16:00:03.000Z'), /STALE_LEASE_FENCED/); runtime.stop(replacement.workerId, '2026-08-13T16:00:04.000Z'); });
  await test('parking-descriptor-only-and-cleanup', () => { const session = runtime.start({ ...allowed, dossierId: 'dossier-park', now: '2026-08-13T16:01:00.000Z' }); const parked = runtime.park(session.workerId, '2026-08-13T16:01:01.000Z', registryInput.version); assert.equal(assertSafeParkingDescriptor(parked), true); assert.equal(parked.state, 'PARKED'); const cleanup = runtime.cleanup().find((item) => item.workerId === session.workerId)!; assert.equal(cleanup.credentialsRevoked, true); assert.equal(cleanup.scratchErased, true); assert.equal(cleanup.memoryRetained, false); assert.equal(cleanup.secretRetained, false); });
  await test('parking-recovery-creates-new-session-and-lease', () => { const parkedSession = runtime.start({ ...allowed, dossierId: 'dossier-recover', now: '2026-08-13T16:02:00.000Z' }); const descriptor = runtime.park(parkedSession.workerId, '2026-08-13T16:02:01.000Z', registryInput.version); const recovered = runtime.recover(descriptor, { tenantId: p2Catalog.tenant, riskClass: 'LOW', capabilities: ['STATUS_READ'], tools: ['CANONICAL_STATUS_READER'], now: '2026-08-13T16:02:02.000Z', leaseMs: 30_000 }); assert.notEqual(recovered.sessionId, parkedSession.sessionId); assert.notEqual(recovered.lease.leaseId, parkedSession.lease.leaseId); assert.notEqual(recovered.credentialId, parkedSession.credentialId); runtime.stop(recovered.workerId, '2026-08-13T16:02:03.000Z'); });
  await test('worker-crash-cleanup-attestation', () => { const session = runtime.start({ ...allowed, dossierId: 'dossier-fail', now: '2026-08-13T16:03:00.000Z' }); runtime.fail(session.workerId, '2026-08-13T16:03:01.000Z'); assert.equal(runtime.session(session.workerId)?.state, 'FAILED'); assert.ok(runtime.cleanup().some((item) => item.workerId === session.workerId && item.reason === 'FAIL')); });
  await test('orphan-sweeper-expires-worker', () => { const session = runtime.start({ ...allowed, dossierId: 'dossier-orphan', now: '2026-08-13T16:04:00.000Z', leaseMs: 1000 }); const expired = runtime.sweepOrphans('2026-08-13T16:04:02.000Z'); assert.ok(expired.includes(session.workerId)); assert.equal(runtime.session(session.workerId)?.state, 'EXPIRED'); });
  await test('registry-revocation-blocks-new-admission', () => { const snapshot = registry.snapshot(); assert.equal(registry.revoke(declaration.agentId), true); assert.equal(admission.evaluate({ ...allowed, dossierId: 'after-revoke' }).reason, 'AGENT_NOT_ACTIVE'); registry.restore(snapshot); assert.equal(admission.evaluate({ ...allowed, dossierId: 'after-restore' }).allowed, true); });

  const keyRegistry = new AuthorityKeyRegistry(); const runtimeDefinition = p2Catalog.authorities.find((item) => item.id === 'RUNTIME_PLACEMENT_AUTHORITY')!; const runtimeKey = Buffer.from('p3-runtime-dummy-key-isolated-only-0000000000'); keyRegistry.register(runtimeDefinition.id, 'p3-runtime-key', runtimeKey);
  const runtimeAuthority = new FederatedCanonicalAuthority(runtimeDefinition, { authorityId: runtimeDefinition.id, workloadId: 'p3-runtime-authority', tenantId: p2Catalog.tenant, keyId: 'p3-runtime-key' }, keyRegistry);
  const gate = new P2ValidationGate(p2Catalog.authorities, keyRegistry, p2Catalog.tenant); const journal = new DurableSignedJournal(); const projection = new FederatedTurnProjection();
  await test('all-runtime-lifecycle-events-reflect-through-p2-to-turn', () => { runtime.events().forEach((event, index) => { const canonical = runtimeAuthority.transition({ eventId: `p3-canonical-${index + 1}`, eventType: event.eventType, aggregateId: event.aggregateId, status: event.status, committedAt: event.occurredAt, correlationId: `p3-${event.eventId}` }); assert.deepEqual(projectValidated(canonical.event, gate, journal, projection, new Date(Date.parse(event.occurredAt) + 250).toISOString()), { status: 'REFLECTED', reason: 'VALIDATED' }); }); const uniqueWorkers = new Set(runtime.events().map((event) => event.aggregateId)); assert.equal(projection.all().length, uniqueWorkers.size); assert.equal(journal.events().length, runtime.events().length); assert.ok(projection.all().every((view) => view.lagMs === 250)); });
  await test('turn-reflection-has-no-session-credential-or-secret', () => { const serialized = JSON.stringify(projection.all()); for (const forbidden of ['credentialId', 'sessionId', 'scratchId', 'secret', 'token', 'conversation', 'prompt']) assert.equal(serialized.includes(forbidden), false); });
  await test('runtime-authority-outage-does-not-change-sessions', () => { const before = runtime.session(primaryWorker); const snapshot = journal.snapshot(); assert.ok(snapshot.events.length > 0); assert.deepEqual(runtime.session(primaryWorker), before); });
  await test('turn-reconstruction-and-registry-rollback', () => { const registrySnapshot = registry.snapshot(); const cleanRegistry = new DeclarativeAgentRegistry(registryInput.version); cleanRegistry.restore(registrySnapshot); assert.deepEqual(cleanRegistry.snapshot(), registrySnapshot); const replayGate = new P2ValidationGate(p2Catalog.authorities, keyRegistry, p2Catalog.tenant); const replayProjection = new FederatedTurnProjection(); for (const event of journal.events()) { assert.equal(replayGate.validate(event, true).valid, true); assert.equal(replayProjection.apply(event, '2026-08-13T16:10:00.000Z').applied, true); } assert.equal(replayProjection.all().length, new Set(journal.events().map((event) => event.aggregateId)).size); assert.equal(journal.events().length, runtime.events().length); });

  const failures = cases.filter((item) => item.result === 'FAIL');
  const report = { contract: 'agm-copilot-v1.2-p3-runtime-evidence.v1', generatedAt: new Date().toISOString(), cases, totals: { cases: cases.length, passed: cases.length - failures.length, failed: failures.length }, registry: { version: registryInput.version, entries: registry.snapshot().length }, runtime: { lifecycleEvents: runtime.events().length, cleanupAttestations: runtime.cleanup().length, parked: runtime.events().filter((event) => event.status === 'PARKED').length, failed: runtime.events().filter((event) => event.status === 'FAILED').length, expired: runtime.events().filter((event) => event.status === 'EXPIRED').length }, turn: { reflections: projection.all().length, journalEvents: journal.events().length }, secretMode: 'DUMMY_ONLY_NO_REAL_SECRET', verdict: failures.length === 0 ? 'PASS' : 'FAIL' };
  await mkdir('evidence/governance/copilot-v1.2/p3/runtime', { recursive: true }); await writeFile('evidence/governance/copilot-v1.2/p3/runtime/agent-runtime-report.json', `${JSON.stringify(report, null, 2)}\n`);
  console.log(`P3 AGENT REGISTRY / EPHEMERAL RUNTIME — ${report.verdict} (${report.totals.passed}/${report.totals.cases})`); console.log(`lifecycle=${report.runtime.lifecycleEvents} turn=${report.turn.reflections} cleanup=${report.runtime.cleanupAttestations}`); if (failures.length) process.exitCode = 1;
}
main().catch((error) => { console.error(error instanceof Error ? error.message : 'P3_TEST_FAILURE'); process.exitCode = 1; });
