import assert from 'node:assert/strict';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { KnowledgeDossierStore, RiskRouter, type EvidenceReference, type ReviewDomain, type RiskClass } from '../packages/copilot-control-plane/src/p4-knowledge';
import { AuthorityKeyRegistry, DurableSignedJournal, FederatedCanonicalAuthority, FederatedTurnProjection, P2ValidationGate, projectValidated, type AuthorityDefinition } from '../packages/copilot-control-plane/src/p2-federation';

async function main() {
  const policy = JSON.parse(await readFile('config/copilot-v1.2/p4-knowledge-policy.json', 'utf8'));
  const router = new RiskRouter(policy);
  const store = new KnowledgeDossierStore(router);
  const cases: Array<{ id: string; result: 'PASS' | 'FAIL'; detail: string }> = [];
  const test = async (id: string, fn: () => void | Promise<void>) => { try { await fn(); cases.push({ id, result: 'PASS', detail: 'validated' }); } catch (error) { cases.push({ id, result: 'FAIL', detail: error instanceof Error ? error.message : 'UNKNOWN' }); } };
  const evidence = (id: string): EvidenceReference => ({ evidenceId: id, sourceUri: `https://official.example.invalid/${id}`, sourceType: 'OFFICIAL', contentHash: `hash-${id}`, capturedAt: '2026-08-13T18:00:00.000Z', provenance: 'official-test-fixture' });
  const create = (riskClass: RiskClass, id: string, proposerId = `proposer-${id}`) => store.create({ dossierId: id, tenantId: 'tenant-agm-p2-isolated', proposerId, title: `Knowledge ${id}`, content: `Canonical content ${id}`, evidence: [evidence(`ev-${id}`)], provenance: 'P4 isolated fixture', riskClass, now: '2026-08-13T18:00:00.000Z' });
  const advance = (id: string) => { const revision = store.current(id)!.revision; store.transition(id, revision, 'ANALYSIS', '2026-08-13T18:00:01.000Z'); return store.transition(id, revision, 'DOMAIN_VALIDATION', '2026-08-13T18:00:02.000Z'); };
  const verdict = (id: string, domain: ReviewDomain, value: 'PASS' | 'REWORK' | 'REJECT', reviewer = `reviewer-${domain}`) => { const current = store.current(id)!; return store.submitVerdict({ verdictId: `${id}-${domain}-${reviewer}-${value}`, dossierId: id, revision: current.revision, revisionHash: current.revisionHash, evidenceHash: current.evidenceHash, reviewerId: reviewer, reviewerWorkloadId: `workload-${reviewer}`, domain, verdict: value, reasonCode: `P4_${value}`, occurredAt: '2026-08-13T18:00:03.000Z' }); };
  let regulatedId = '';

  await test('risk-classification-and-routing-4-of-4', () => {
    assert.equal(router.classify({}), 'LOW'); assert.equal(router.classify({ personalData: true }), 'MEDIUM'); assert.equal(router.classify({ security: true }), 'HIGH'); assert.equal(router.classify({ regulated: true }), 'REGULATED');
    assert.deepEqual(router.snapshot('LOW', '2026-08-13T18:00:00.000Z').requiredReviews, ['FUNCTIONAL', 'SOURCE_EVIDENCE']);
    assert.equal(router.snapshot('REGULATED', '2026-08-13T18:00:00.000Z').requiredReviews.length, 5);
  });
  await test('unique-dossier-id-version-hash-policy-provenance-evidence', () => { const value = create('LOW', 'dossier-unique'); assert.equal(value.revision, 1); assert.equal(value.contentHash.length, 64); assert.equal(value.evidenceHash.length, 64); assert.equal(value.revisionHash.length, 64); assert.equal(value.policy.snapshotHash.length, 64); assert.equal(value.provenance, 'P4 isolated fixture'); assert.throws(() => create('LOW', 'dossier-unique'), /DOSSIER_ID_CONFLICT/); });
  await test('immutable-history-defensive-copy', () => { const history = store.history('dossier-unique'); history[0].content = 'tampered'; history[0].evidence[0].provenance = 'tampered'; assert.equal(store.history('dossier-unique')[0].content, 'Canonical content dossier-unique'); assert.equal(store.history('dossier-unique')[0].evidence[0].provenance, 'official-test-fixture'); });
  await test('optimistic-concurrency-locking', () => { const value = store.current('dossier-unique')!; store.revise({ dossierId: value.dossierId, expectedRevision: value.revision, proposerId: value.proposerId, content: 'Revision two', evidence: value.evidence, provenance: value.provenance, riskClass: value.riskClass, now: '2026-08-13T18:01:00.000Z' }); assert.throws(() => store.revise({ dossierId: value.dossierId, expectedRevision: value.revision, proposerId: value.proposerId, content: 'Lost update', evidence: value.evidence, provenance: value.provenance, riskClass: value.riskClass, now: '2026-08-13T18:01:01.000Z' }), /REVISION_CONFLICT/); });
  await test('proposer-cannot-validate-own-dossier', () => { create('LOW', 'dossier-sod', 'same-person'); advance('dossier-sod'); assert.throws(() => verdict('dossier-sod', 'FUNCTIONAL', 'PASS', 'same-person'), /SOD_PROPOSER_VALIDATOR_DENIED/); });
  await test('unrouted-domain-validation-denied', () => { assert.throws(() => verdict('dossier-sod', 'LEGAL_COMPLIANCE', 'PASS'), /UNROUTED_REVIEW_DOMAIN/); });
  await test('duplicate-verdict-replay-denied', () => { verdict('dossier-sod', 'FUNCTIONAL', 'PASS'); const current = store.current('dossier-sod')!; const input = { verdictId: 'replay-verdict', dossierId: 'dossier-sod', revision: current.revision, revisionHash: current.revisionHash, evidenceHash: current.evidenceHash, reviewerId: 'reviewer-replay', reviewerWorkloadId: 'workload-replay', domain: 'SOURCE_EVIDENCE' as const, verdict: 'PASS' as const, reasonCode: 'P4_PASS', occurredAt: '2026-08-13T18:00:03.000Z' }; store.submitVerdict(input); assert.throws(() => store.submitVerdict(input), /DUPLICATE_VERDICT/); });
  await test('all-risk-routes-ready-for-knowledge-gate', () => { for (const risk of ['LOW', 'MEDIUM', 'HIGH', 'REGULATED'] as RiskClass[]) { const id = `dossier-route-${risk}`; create(risk, id); advance(id); for (const domain of store.current(id)!.policy.requiredReviews) verdict(id, domain, 'PASS'); const result = store.aggregate(id, 1, '2026-08-13T18:00:04.000Z'); assert.equal(result.status, 'KNOWLEDGE_GATE_READY'); assert.equal(store.current(id)?.status, 'KNOWLEDGE_GATE_READY'); if (risk === 'REGULATED') regulatedId = id; } });
  await test('missing-review-produces-rework', () => { create('MEDIUM', 'dossier-missing'); advance('dossier-missing'); verdict('dossier-missing', 'FUNCTIONAL', 'PASS'); const result = store.aggregate('dossier-missing', 1, '2026-08-13T18:00:04.000Z'); assert.equal(result.status, 'REWORK'); assert.equal(result.reason, 'REQUIRED_REVIEW_MISSING'); });
  await test('domain-reject-produces-rejected', () => { create('LOW', 'dossier-reject'); advance('dossier-reject'); verdict('dossier-reject', 'FUNCTIONAL', 'PASS'); verdict('dossier-reject', 'SOURCE_EVIDENCE', 'REJECT'); assert.equal(store.aggregate('dossier-reject', 1, '2026-08-13T18:00:04.000Z').status, 'REJECTED'); });
  await test('domain-rework-produces-rework', () => { create('LOW', 'dossier-rework'); advance('dossier-rework'); verdict('dossier-rework', 'FUNCTIONAL', 'PASS'); verdict('dossier-rework', 'SOURCE_EVIDENCE', 'REWORK'); assert.equal(store.aggregate('dossier-rework', 1, '2026-08-13T18:00:04.000Z').status, 'REWORK'); });
  await test('conflicting-verdicts-produce-rework', () => { create('LOW', 'dossier-conflict'); advance('dossier-conflict'); verdict('dossier-conflict', 'FUNCTIONAL', 'PASS', 'functional-a'); verdict('dossier-conflict', 'FUNCTIONAL', 'REJECT', 'functional-b'); verdict('dossier-conflict', 'SOURCE_EVIDENCE', 'PASS'); const result = store.aggregate('dossier-conflict', 1, '2026-08-13T18:00:04.000Z'); assert.equal(result.status, 'REWORK'); assert.equal(result.reason, 'CONFLICTING_VERDICTS'); });
  await test('stale-verdict-after-revision-denied', () => { create('LOW', 'dossier-stale'); const old = advance('dossier-stale'); const revised = store.revise({ dossierId: old.dossierId, expectedRevision: old.revision, proposerId: old.proposerId, content: 'Changed content', evidence: old.evidence, provenance: old.provenance, riskClass: old.riskClass, now: '2026-08-13T18:02:00.000Z' }); assert.throws(() => store.submitVerdict({ verdictId: 'stale-v', dossierId: old.dossierId, revision: old.revision, revisionHash: old.revisionHash, evidenceHash: old.evidenceHash, reviewerId: 'stale-reviewer', reviewerWorkloadId: 'stale-workload', domain: 'FUNCTIONAL', verdict: 'PASS', reasonCode: 'STALE', occurredAt: '2026-08-13T18:02:01.000Z' }), /STALE_VERDICT/); assert.equal(revised.revision, 2); });
  await test('archive-and-active-states-impossible-in-p4', () => { const current = store.current(regulatedId)!; assert.throws(() => store.transition(regulatedId, current.revision, 'APPROVED_FOR_ARCHIVE' as never, '2026-08-13T18:05:00.000Z'), /P4_TERMINAL_STATE_FORBIDDEN/); assert.throws(() => store.transition(regulatedId, current.revision, 'ACTIVE_KNOWLEDGE' as never, '2026-08-13T18:05:00.000Z'), /P4_TERMINAL_STATE_FORBIDDEN/); });
  await test('snapshot-restart-reconstruction-and-corruption-denial', () => { const snapshot = store.snapshot(); const restored = new KnowledgeDossierStore(router); restored.restore(snapshot); assert.deepEqual(restored.current(regulatedId), store.current(regulatedId)); const corrupted = { ...snapshot, events: snapshot.events.slice(1) }; assert.throws(() => restored.restore(corrupted), /DOSSIER_SNAPSHOT_INTEGRITY_FAILURE/); });

  const p2Catalog = JSON.parse(await readFile('config/copilot-v1.2/p2-authority-catalog.json', 'utf8')) as { tenant: string; authorities: AuthorityDefinition[] };
  const definition = p2Catalog.authorities.find((item) => item.id === 'WORKFLOW_STATE_AUTHORITY')!; const keys = new AuthorityKeyRegistry(); keys.register(definition.id, 'p4-workflow-key', Buffer.from('p4-workflow-dummy-key-isolated-only-000000000'));
  const authority = new FederatedCanonicalAuthority(definition, { authorityId: definition.id, workloadId: 'p4-workflow-authority', tenantId: p2Catalog.tenant, keyId: 'p4-workflow-key' }, keys); const gate = new P2ValidationGate(p2Catalog.authorities, keys, p2Catalog.tenant); const journal = new DurableSignedJournal(); const projection = new FederatedTurnProjection();
  await test('all-dossier-state-events-reflected-to-turn', () => { store.events().forEach((event, index) => { const canonical = authority.transition({ eventId: `p4-workflow-${index + 1}`, eventType: 'workflow.dossier_state_changed', aggregateId: event.dossierId, status: event.status, committedAt: event.occurredAt, correlationId: event.eventId }); assert.deepEqual(projectValidated(canonical.event, gate, journal, projection, new Date(Date.parse(event.occurredAt) + 250).toISOString()), { status: 'REFLECTED', reason: 'VALIDATED' }); }); assert.equal(journal.events().length, store.events().length); assert.equal(projection.all().length, new Set(store.events().map((event) => event.dossierId)).size); });
  await test('turn-reflection-secret-free-and-no-canonical-mutation', () => { const serialized = JSON.stringify(projection.all()); assert.equal(/secret|token|credential|password/i.test(serialized), false); assert.equal('transition' in projection, false); });
  await test('turn-rebuild-exact-latest-state-parity', () => { const replayGate = new P2ValidationGate(p2Catalog.authorities, keys, p2Catalog.tenant); const replay = new FederatedTurnProjection(); for (const event of journal.events()) { assert.equal(replayGate.validate(event, true).valid, true); replay.apply(event, '2026-08-13T18:10:00.000Z'); } assert.equal(replay.all().length, projection.all().length); for (const view of projection.all()) assert.equal(replay.view(view.projectionKey)?.stateHash, view.stateHash); });

  const failures = cases.filter((item) => item.result === 'FAIL'); const report = { contract: 'agm-copilot-v1.2-p4-knowledge-evidence.v1', generatedAt: new Date().toISOString(), cases, totals: { cases: cases.length, passed: cases.length - failures.length, failed: failures.length }, dossier: { count: new Set(store.events().map((event) => event.dossierId)).size, events: store.events().length, verdicts: ['LOW','MEDIUM','HIGH','REGULATED'].reduce((total, risk) => total + store.verdicts(`dossier-route-${risk}`).length, 0), terminalForbidden: policy.terminalForbidden }, turn: { journalEvents: journal.events().length, views: projection.all().length }, secretMode: 'DUMMY_ONLY_NO_REAL_SECRET', p5RolesOpened: false, verdict: failures.length === 0 ? 'PASS' : 'FAIL' };
  await mkdir('evidence/governance/copilot-v1.2/p4/runtime', { recursive: true }); await writeFile('evidence/governance/copilot-v1.2/p4/runtime/knowledge-dossier-report.json', `${JSON.stringify(report, null, 2)}\n`); await writeFile('evidence/governance/copilot-v1.2/p4/runtime/dossier-snapshot.json', `${JSON.stringify(store.snapshot(), null, 2)}\n`);
  console.log(`P4 KNOWLEDGE DOSSIER / VALIDATION — ${report.verdict} (${report.totals.passed}/${report.totals.cases})`); console.log(`dossiers=${report.dossier.count} events=${report.dossier.events} turn=${report.turn.views}`); if (failures.length) process.exitCode = 1;
}
main().catch((error) => { console.error(error instanceof Error ? error.message : 'P4_TEST_FAILURE'); process.exitCode = 1; });
