import assert from 'node:assert/strict';import{mkdir,writeFile}from'node:fs/promises';
import{AuthorityKeyRegistry,FederatedCanonicalAuthority,type P2Event}from'../packages/copilot-control-plane/src/p2-federation';
import{HardenedTurnProjection,TurnStateCustodianOperational,architectureGovernanceFirstView}from'../packages/copilot-control-plane/src/p7-turn-hardening';
const out='evidence/governance/copilot-v1.2/p7/runtime',cases:{id:string;result:'PASS'|'FAIL';detail:string}[]=[];async function test(id:string,fn:()=>void|Promise<void>){try{await fn();cases.push({id,result:'PASS',detail:'validated'});}catch(e){cases.push({id,result:'FAIL',detail:e instanceof Error?e.message:'UNKNOWN'});}}
const policy={sloMs:{CRITICAL:5000,LIFECYCLE:15000,INFORMATIONAL:30000},hardStaleMs:{CRITICAL:15000,LIFECYCLE:60000,INFORMATIONAL:120000}};const keys=new AuthorityKeyRegistry();keys.register('turn-test','turn-key',Buffer.from('p7-turn-authority-dummy-key-material-000001'));const authority=new FederatedCanonicalAuthority({id:'turn-test',eventPrefix:'GOV.',turnClass:'INFORMATIONAL'},{authorityId:'turn-test',workloadId:'authority-workload',tenantId:'tenant-agm',keyId:'turn-key'},keys);
const ev=(id:string,status:string,at:string)=>authority.transition({eventId:id,eventType:'GOV.STATUS',aggregateId:'Turn',status,committedAt:at,correlationId:id}).event;const projection=new HardenedTurnProjection(),custodian=new TurnStateCustodianOperational(projection,policy);const journal:P2Event[]=[];
async function main(){
 const e1=ev('p7-e1','HEALTHY','2026-08-13T22:00:00.000Z');journal.push(e1);
 await test('status-taxonomy-and-5s-slo',()=>{const r=projection.apply(e1,'2026-08-13T22:00:04.000Z','CRITICAL',policy);assert.equal(r.applied,true);assert.equal(projection.all()[0]?.status,'HEALTHY');});
 const e2=ev('p7-e2','ACTIVE','2026-08-13T22:00:05.000Z'),e3=ev('p7-e3','REVIEW','2026-08-13T22:00:06.000Z');journal.push(e2,e3);
 await test('out-of-order-buffer-and-gap-recovery',()=>{assert.equal(projection.apply(e3,'2026-08-13T22:00:07.000Z','INFORMATIONAL',policy).reason,'SEQUENCE_GAP');assert.equal(projection.pending(),1);projection.apply(e2,'2026-08-13T22:00:07.000Z','INFORMATIONAL',policy);assert.equal(projection.pending(),0);assert.equal(projection.all()[0]?.revision,3);});
 await test('duplicate-idempotent',()=>assert.equal(projection.apply(e3,'2026-08-13T22:00:08.000Z','INFORMATIONAL',policy).reason,'DUPLICATE_OR_OLD'));
 await test('delayed-event-degraded-at-15s',()=>{const p=new HardenedTurnProjection();p.apply(e1,'2026-08-13T22:00:16.000Z','LIFECYCLE',policy);assert.equal(p.all()[0]?.status,'DEGRADED');});
 await test('hard-stale-detection',()=>{const result=custodian.inspect(journal,'2026-08-13T22:02:07.000Z');assert.ok(result.defects.some(x=>x.startsWith('STALE:')));});
 await test('missing-event-detection',()=>{const p=new HardenedTurnProjection(),c=new TurnStateCustodianOperational(p,policy);assert.ok(c.inspect(journal,'2026-08-13T22:00:08.000Z').defects.some(x=>x.startsWith('MISSING:')));});
 await test('corruption-detected-and-reconciled',()=>{const key=projection.all()[0]!.key;projection.corrupt(key);assert.ok(custodian.inspect(journal,'2026-08-13T22:00:08.000Z').defects.some(x=>x.startsWith('DRIFT:')));assert.equal(custodian.reconcile(journal,'2026-08-13T22:00:08.000Z').rebuilt.parity,true);});
 await test('partial-projection-rebuild',()=>{projection.clear();projection.apply(e1,'2026-08-13T22:00:08.000Z','INFORMATIONAL',policy);assert.equal(custodian.rebuild(journal,'2026-08-13T22:00:08.000Z').parity,true);});
 await test('turn-restart-snapshot',()=>{const s=projection.snapshot();projection.clear();projection.restore(s);assert.deepEqual(projection.snapshot(),s);});
 await test('corrupt-checkpoint-denied',()=>{const s=projection.snapshot();assert.throws(()=>projection.restore({...s,snapshotHash:'bad'}),/TURN_SNAPSHOT_CORRUPT/);});
 await test('custodian-crash-unavailable',()=>{custodian.crash();assert.equal(custodian.inspect(journal,'2026-08-13T22:00:08.000Z').status,'UNAVAILABLE');assert.throws(()=>custodian.rebuild(journal,'2026-08-13T22:00:08.000Z'),/CUSTODIAN_UNAVAILABLE/);custodian.recover();});
 await test('turn-completely-unavailable-fail-honest',()=>{projection.markUnavailable();const e4=ev('p7-e4','FAILED','2026-08-13T22:00:09.000Z');journal.push(e4);assert.equal(projection.apply(e4,'2026-08-13T22:00:10.000Z','CRITICAL',policy).reason,'TURN_UNAVAILABLE');projection.markAvailable();assert.equal(custodian.rebuild(journal,'2026-08-13T22:00:10.000Z').parity,true);});
 await test('reconciliation-conflict-canonical-wins',()=>{const before=JSON.stringify(journal);projection.corrupt(projection.all()[0]!.key);custodian.reconcile(journal,'2026-08-13T22:00:11.000Z');assert.equal(JSON.stringify(journal),before);});
 await test('custodian-canonical-mutation-denied',()=>assert.throws(()=>custodian.mutateCanonical(),/DENIED/));
 await test('custodian-secret-and-publication-denied',()=>{assert.throws(()=>custodian.accessSecret(),/DENIED/);assert.throws(()=>custodian.publishKnowledge(),/DENIED/);});
 await test('tenant-isolated-projection-keys',()=>assert.ok(projection.all().every(v=>v.key.startsWith('tenant-agm:'))));
 await test('architecture-governance-first-view',()=>{const view=architectureGovernanceFirstView(projection.all());assert.equal(view.position,'IMMEDIATELY_AFTER_INCIDENTS');assert.equal(view.nodes.length,12);assert.ok(view.nodes.some(n=>n.name==='AGM BASIC — SEALED'));});
 await test('audit-and-turn-secret-free',()=>{assert.ok(custodian.audits().length>0);const serialized=JSON.stringify({views:projection.all(),audits:custodian.audits()});assert.equal(/token|credential|password|secretValue/i.test(serialized),false);});
 const failed=cases.filter(c=>c.result==='FAIL');const report={contract:'agm-copilot-v1.2-p7-turn-hardening-evidence.v1',generatedAt:new Date().toISOString(),cases,totals:{cases:cases.length,passed:cases.length-failed.length,failed:failed.length},canonicalEvents:journal.length,turnViews:projection.all().length,custodianAudits:custodian.audits().length,sloMs:policy.sloMs,hardStaleMs:policy.hardStaleMs,p8Opened:false,secretExposure:'ZERO',verdict:failed.length?'FAIL':'PASS'};await mkdir(out,{recursive:true});await writeFile(`${out}/turn-hardening-report.json`,JSON.stringify(report,null,2)+'\n');await writeFile(`${out}/turn-snapshot.json`,JSON.stringify(projection.snapshot(),null,2)+'\n');await writeFile(`${out}/custodian-audit.json`,JSON.stringify(custodian.audits(),null,2)+'\n');await writeFile(`${out}/architecture-governance-first-view.json`,JSON.stringify(architectureGovernanceFirstView(projection.all()),null,2)+'\n');console.log(`P7 TURN HARDENING / CUSTODIAN — ${report.verdict} (${report.totals.passed}/${report.totals.cases})`);if(failed.length){console.error(failed);process.exitCode=1;}}
void main();
