import assert from'node:assert/strict';import{createHash}from'node:crypto';import{readFileSync}from'node:fs';import{mkdir,writeFile}from'node:fs/promises';import{ArchitectureChainValidator,MigrationAuthority,createP8Signer,migrationTurn,type MigrationRecord,type PhaseEvidence}from'../packages/copilot-control-plane/src/p8-migration';
const out='evidence/governance/copilot-v1.2/p8/runtime',cases:{id:string;result:'PASS'|'FAIL';detail:string}[]=[];async function test(id:string,fn:()=>void|Promise<void>){try{await fn();cases.push({id,result:'PASS',detail:'validated'});}catch(e){cases.push({id,result:'FAIL',detail:e instanceof Error?e.message:'UNKNOWN'});}}
const signer=createP8Signer(Buffer.from('p8-migration-dummy-key-material-000000001')),migration=new MigrationAuthority(signer),writer={id:'migration-writer',epoch:'epoch-p8-001',fence:7};const legacy:MigrationRecord[]=[1,2,3].map(n=>({legacyId:`legacy-${n}`,canonicalId:`canonical-${n}`,tenantId:'tenant-agm',capability:'KNOWLEDGE_GOVERNANCE',risk:'LOW',revision:n,state:n===3?'ACTIVE_KNOWLEDGE':'SUPERSEDED',payloadHash:sha(`payload-${n}`),provenanceHash:sha(`source-${n}`),schemaVersion:'v1.2'}));
function phaseEvidence():PhaseEvidence[]{return[1,2,3,4,5,6,7].map(n=>{const path=`evidence/governance/copilot-v1.2/p${n}/EVIDENCE_MANIFEST.json`;const raw=readFileSync(path,'utf8');const parsed=JSON.parse(raw);return{phase:`P${n}`,contract:parsed.contract,verdict:parsed.verdict??'PASS',artifactHash:sha(raw)};});}
async function main(){
 await test('single-fenced-writer-acquired',()=>assert.deepEqual(migration.acquireWriter(writer.id,writer.epoch,writer.fence),writer));
 await test('stale-writer-fenced',()=>assert.throws(()=>migration.acquireWriter('other','epoch-old',6),/STALE_WRITER_FENCE/));
 await test('deterministic-provenance-preserving-import',()=>{for(const[r,i]of legacy.map((r,i)=>[r,i]as const))assert.equal(migration.import(r,{writerId:writer.id,epoch:writer.epoch,fence:writer.fence,eventId:`migration-${i+1}`,occurredAt:`2026-08-13T23:00:0${i}.000Z`}).status,'IMPORTED');});
 await test('duplicate-event-idempotent',()=>assert.equal(migration.import(legacy[0]!,{writerId:writer.id,epoch:writer.epoch,fence:writer.fence,eventId:'migration-1',occurredAt:'2026-08-13T23:00:10.000Z'}).status,'DUPLICATE'));
 await test('schema-mismatch-quarantined',()=>assert.equal(migration.import({...legacy[0]!,legacyId:'bad-schema',schemaVersion:'old'},{writerId:writer.id,epoch:writer.epoch,fence:writer.fence,eventId:'bad-schema',occurredAt:'2026-08-13T23:00:11.000Z'}).status,'QUARANTINED'));
 await test('unknown-record-quarantined',()=>assert.equal(migration.import({...legacy[0]!,legacyId:'',canonicalId:'unknown'},{writerId:writer.id,epoch:writer.epoch,fence:writer.fence,eventId:'unknown',occurredAt:'2026-08-13T23:00:12.000Z'}).status,'QUARANTINED'));
 await test('wrong-epoch-writer-denied',()=>assert.throws(()=>migration.import(legacy[0]!,{writerId:writer.id,epoch:'wrong',fence:writer.fence,eventId:'wrong',occurredAt:'2026-08-13T23:00:13.000Z'}),/WRITER_FENCED/));
 const cohort={tenantId:'tenant-agm',capability:'KNOWLEDGE_GOVERNANCE',risk:'LOW' as const};let parity!:ReturnType<typeof migration.shadowParity>;
 await test('shadow-count-hash-state-parity',()=>{parity=migration.shadowParity(legacy,cohort);assert.equal(parity.parity,true);assert.equal(parity.sourceHash,parity.targetHash);});
 await test('non-parity-blocks-cutover',()=>{const bad=migration.shadowParity([...legacy,{...legacy[0]!,legacyId:'extra',canonicalId:'extra'}],cohort);assert.throws(()=>migration.cutover(bad,writer),/CUTOVER_PARITY_REQUIRED/);});
 await test('bounded-cohort-cutover',()=>assert.equal(migration.cutover(parity,writer),'V1_2'));
 await test('split-brain-old-writer-denied',()=>assert.throws(()=>migration.import(legacy[0]!,{writerId:'legacy-writer',epoch:writer.epoch,fence:writer.fence,eventId:'split',occurredAt:'2026-08-13T23:00:14.000Z'}),/WRITER_FENCED/));
 await test('rollback-restores-prior-route',()=>{assert.equal(migration.rollback(writer),'LEGACY');assert.equal(migration.cutover(parity,writer),'V1_2');});
 await test('restart-replay-parity',()=>{const snapshot=migration.snapshot();const restored=new MigrationAuthority(signer);restored.restore(snapshot);assert.deepEqual(restored.snapshot(),snapshot);assert.equal(restored.shadowParity(legacy,cohort).parity,true);});
 await test('corrupt-snapshot-denied',()=>{const s=migration.snapshot();assert.throws(()=>migration.restore({...s,snapshotHash:'corrupt'}),/MIGRATION_SNAPSHOT_CORRUPT/);});
 let chain!:ReturnType<ArchitectureChainValidator['validate']>;
 await test('full-p1-p7-evidence-chain-valid',()=>{chain=new ArchitectureChainValidator().validate(phaseEvidence());assert.equal(chain.valid,true);});
 await test('missing-phase-chain-denied',()=>assert.equal(new ArchitectureChainValidator().validate(phaseEvidence().slice(0,-1)).valid,false));
 await test('turn-reflects-selected-epoch-secret-free',()=>{const turn=migrationTurn(migration.events(),migration.route());assert.equal(turn.status,'ACTIVE');assert.equal(turn.secretFree,true);assert.equal(turn.productionChanged,false);});
 await test('canonical-event-chain-integrity',()=>{const events=migration.events();assert.ok(events.every((e,i)=>i===0?e.previousHash===null:e.previousHash===events[i-1]!.eventHash));assert.equal(migration.quarantine().length,2);});
 const failed=cases.filter(c=>c.result==='FAIL'),report={contract:'agm-copilot-v1.2-p8-system-validation.v1',generatedAt:new Date().toISOString(),cases,totals:{cases:cases.length,passed:cases.length-failed.length,failed:failed.length},migration:{epoch:writer.epoch,events:migration.events().length,quarantined:migration.quarantine().length,route:migration.route(),parity},architectureChain:chain,turn:migrationTurn(migration.events(),migration.route()),productionChanged:false,basicChanged:false,realSecretUsed:false,verdict:failed.length?'FAIL':'PASS'};await mkdir(out,{recursive:true});await writeFile(`${out}/p8-system-report.json`,JSON.stringify(report,null,2)+'\n');await writeFile(`${out}/migration-snapshot.json`,JSON.stringify(migration.snapshot(),null,2)+'\n');await writeFile(`${out}/architecture-chain-evidence.json`,JSON.stringify(phaseEvidence(),null,2)+'\n');console.log(`P8 MIGRATION / SYSTEM COHERENCE — ${report.verdict} (${report.totals.passed}/${report.totals.cases})`);if(failed.length){console.error(failed);process.exitCode=1;}}
function sha(v:string){return createHash('sha256').update(v).digest('hex');}void main();
