import { CapabilityBroker } from '../premium-capabilities/capability.broker';
import type { ActionPreview, CapabilityId, HandoffReceipt } from '../premium-capabilities/capability.types';

export type VerifiedPublicContact=Readonly<{contactId:string;entity:string;phone?:string;address?:string;sourceUrl:string;navigationReceiptId:string;verified:boolean;ambiguous?:boolean}>;
export type ContactActionResult=Readonly<{status:'COPIED'|'PREVIEW'|'HANDOFF'|'DENIED'|'CANCELLED';reason:string;preview?:ActionPreview;receipt?:HandoffReceipt;sourceUrl?:string;navigationReceiptId?:string;copiedValue?:string;messageDraft?:string}>;
export class PublicContactControlledAction{
 private readonly broker=new CapabilityBroker();private readonly consumed=new Set<string>();
 copy(contact:VerifiedPublicContact):ContactActionResult{const d=this.guard(contact,'PHONE');if(d)return d;return{status:'COPIED',reason:'LOCAL_COPY_ONLY',copiedValue:contact.phone,sourceUrl:contact.sourceUrl,navigationReceiptId:contact.navigationReceiptId};}
 async propose(contact:VerifiedPublicContact,kind:'CALL'|'MAP'|'MESSAGE',message?:string):Promise<ContactActionResult>{const d=this.guard(contact,kind==='MAP'?'ADDRESS':'PHONE');if(d)return d;if(kind==='MESSAGE')return message?.trim()?{status:'PREVIEW',reason:'MESSAGE_DRAFT_READY_NO_SEND',messageDraft:message.trim(),sourceUrl:contact.sourceUrl,navigationReceiptId:contact.navigationReceiptId}:{status:'DENIED',reason:'MESSAGE_BODY_REQUIRED'};
 const capabilityId:CapabilityId=kind==='CALL'?'OPEN_DIALER':'OPEN_MAPS';const requestId=crypto.randomUUID();const decision=await this.broker.prepare({productId:'agm-cockpit',moduleId:'copilot.public-contact',tenantId:'tenant:agm',subjectId:'owner',premiumEntitled:true,requestId,conversationId:contact.contactId,capabilityId,parameters:kind==='CALL'?{phoneNumber:contact.phone,displayName:contact.entity}:{destination:contact.address,grounded:true},requestedAt:new Date().toISOString()});return decision.status==='PREVIEW_READY'?{status:'PREVIEW',reason:'ACTION_PREVIEW_READY',preview:decision.preview,sourceUrl:contact.sourceUrl,navigationReceiptId:contact.navigationReceiptId}:{status:'DENIED',reason:'reason'in decision?decision.reason:'CONTACT_INPUT_REQUIRED'};}
 handoff(contact:VerifiedPublicContact,preview:ActionPreview,confirmed:boolean):ContactActionResult{const d=this.guard(contact,preview.capabilityId==='OPEN_MAPS'?'ADDRESS':'PHONE');if(d)return d;if(!confirmed)return{status:'DENIED',reason:'EXPLICIT_CONFIRMATION_REQUIRED'};if(this.consumed.has(preview.confirmationId))return{status:'DENIED',reason:'DUPLICATE_OR_REPLAY_DENIED'};this.consumed.add(preview.confirmationId);return{status:'HANDOFF',reason:'SYSTEM_HANDOFF_ONLY',receipt:{receiptId:crypto.randomUUID(),confirmationId:preview.confirmationId,capabilityId:preview.capabilityId,handedOffAt:new Date().toISOString(),status:'OPENED',targetPackage:'DUMMY_SYSTEM_HANDLER'},sourceUrl:contact.sourceUrl,navigationReceiptId:contact.navigationReceiptId};}
 cancel(contact:VerifiedPublicContact):ContactActionResult{return{status:'CANCELLED',reason:'USER_CANCELLED_RETURN_TO_CONVERSATION',sourceUrl:contact.sourceUrl,navigationReceiptId:contact.navigationReceiptId};}
 private guard(contact:VerifiedPublicContact,required:'PHONE'|'ADDRESS'){if(contact.ambiguous)return{status:'DENIED',reason:'AMBIGUOUS_CONTACT_CLARIFICATION_REQUIRED'}as const;if(!contact.verified||!contact.sourceUrl||!contact.navigationReceiptId)return{status:'DENIED',reason:'VERIFIED_SOURCE_AND_RECEIPT_REQUIRED'}as const;if(required==='PHONE'&&!contact.phone)return{status:'DENIED',reason:'PHONE_REQUIRED'}as const;if(required==='ADDRESS'&&!contact.address)return{status:'DENIED',reason:'ADDRESS_REQUIRED'}as const;}
}
