import { PrismaClient } from '@prisma/client';import { readFile,readdir,rm,stat,writeFile } from 'node:fs/promises';import { join,resolve } from 'node:path';import { compactLedger,ledgerKey } from '../src/data-rights/suppression-ledger';import { executionAuthorized,retentionPlan,validateRetentionPolicy,type RetentionPolicy } from '../src/data-lifecycle/retention-engine';
const prisma=new PrismaClient();
type Impact={category:string;eligible:number;protectedByHold:number;affected:number;mode:'DRY_RUN'|'EXECUTE';details?:any};
async function main(){
  const policyPath=resolve(process.env.RETENTION_POLICY_PATH??join(process.cwd(),'..','..','config','retention-policy.owner-approved.json'));const policy=validateRetentionPolicy(JSON.parse(await readFile(policyPath,'utf8')) as RetentionPolicy);const now=new Date(process.env.RETENTION_NOW??Date.now());if(Number.isNaN(now.getTime()))throw new Error('RETENTION_NOW_INVALID');const plan=retentionPlan(policy,process.env,now);const execute=executionAuthorized(policy,process.env);const impacts:Impact[]=[];
  for(const decision of plan){if(!decision.enabled){impacts.push({category:decision.category,eligible:0,protectedByHold:0,affected:0,mode:'DRY_RUN',details:{reason:decision.reason}});continue;}
    if(decision.category==='expiredAuthSessions'){const where={expiresAt:{lte:decision.cutoff!},revokedAt:null};const eligible=await prisma.authSession.count({where});const affected=execute?(await prisma.authSession.deleteMany({where})).count:0;impacts.push(row(decision.category,eligible,0,affected,execute));}
    if(decision.category==='revokedAuthSessions'){const where={revokedAt:{lte:decision.cutoff!}};const eligible=await prisma.authSession.count({where});const affected=execute?(await prisma.authSession.deleteMany({where})).count:0;impacts.push(row(decision.category,eligible,0,affected,execute));}
    if(decision.category==='completedDsarRecords'){const candidates=await prisma.dataSubjectRequest.findMany({where:{completedAt:{lt:decision.cutoff!}},select:{id:true,metadata:true}});const held=candidates.filter(item=>(item.metadata as any)?.legalHold===true);const ids=candidates.filter(item=>(item.metadata as any)?.legalHold!==true).map(item=>item.id);const affected=execute&&ids.length?(await prisma.dataSubjectRequest.deleteMany({where:{id:{in:ids}}})).count:0;impacts.push(row(decision.category,ids.length,held.length,affected,execute,{exclusiveCutoff:decision.cutoff!.toISOString()}));}
    if(decision.category==='identifierAuditLogs'){const result=await auditLogs(decision.cutoff!,execute);impacts.push(row(decision.category,result.eligible,result.held,result.affected,execute));}
    if(decision.category==='generatedDsarExports'){const result=await expiringFiles(required('DSAR_EXPORT_DIR'),decision.cutoff!,execute,'export');impacts.push(row(decision.category,result.eligible,result.held,result.affected,execute,{trigger:decision.trigger}));}
    if(decision.category==='postgresBackups'){const result=await backupFiles(required('POSTGRES_BACKUP_DIR'),decision.maxGenerations!,execute);impacts.push(row(decision.category,result.eligible,0,result.affected,execute,{maxGenerations:decision.maxGenerations}));}
    if(decision.category==='suppressionLedgerEntries'){const result=await compactLedger(required('DSAR_SUPPRESSION_LEDGER_PATH'),ledgerKey(process.env.DSAR_SUPPRESSION_LEDGER_KEY),decision.cutoff!,!execute);impacts.push(row(decision.category,result.affectedSubjects,0,execute?result.affectedSubjects:0,execute,{removedRecords:result.removedRecords,cutoff:decision.cutoff!.toISOString()}));}
    if(execute&&process.env.RETENTION_SYNTHETIC_FAIL_AFTER_CATEGORY===decision.category)throw new Error(`SYNTHETIC_RETENTION_FAILURE_AFTER:${decision.category}`);
  }
  const report={contract:'agm-retention-engine.v3',policyVersion:policy.policyVersion,now:now.toISOString(),timezone:'UTC',productionActivationAuthorized:false,mode:execute?'EXECUTE_NON_PRODUCTION':'DRY_RUN',impacts,totalEligible:impacts.reduce((sum,item)=>sum+item.eligible,0),totalAffected:impacts.reduce((sum,item)=>sum+item.affected,0)};if(process.env.RETENTION_REPORT_PATH)await writeFile(process.env.RETENTION_REPORT_PATH,JSON.stringify(report,null,2),{mode:0o600});process.stdout.write(JSON.stringify(report)+'\n');
}
function row(category:string,eligible:number,protectedByHold:number,affected:number,execute:boolean,details?:any):Impact{return{category,eligible,protectedByHold,affected,mode:execute?'EXECUTE':'DRY_RUN',details};}function required(name:string){const value=process.env[name];if(!value)throw new Error(`${name}_REQUIRED_FAIL_CLOSED`);return resolve(value);}
async function auditLogs(cutoff:Date,execute:boolean){const rows=await prisma.$queryRawUnsafe<Array<{id:string;held:boolean}>>('SELECT a.id::text, (u."legalRetentionReason" IS NOT NULL OR (u."retentionUntil" IS NOT NULL AND u."retentionUntil">CURRENT_TIMESTAMP) OR COALESCE((a.metadata->>\'legalHold\')::boolean,false)) AS held FROM "AuditEvent" a LEFT JOIN "User" u ON u.id=a."actorUserId" WHERE a."occurredAt" <= $1',cutoff);const ids=rows.filter(item=>!item.held).map(item=>item.id);const affected=execute&&ids.length?(await prisma.auditEvent.deleteMany({where:{id:{in:ids}}})).count:0;return{eligible:ids.length,held:rows.length-ids.length,affected};}
async function expiringFiles(dir:string,cutoff:Date,execute:boolean,kind:string){const manifests=(await readdir(dir)).filter(name=>name.endsWith('.retention.json'));let eligible=0,held=0,affected=0;for(const name of manifests){const path=join(dir,name),value=JSON.parse(await readFile(path,'utf8'));if(value.legalHold===true){held++;continue;}const trigger=[value.deliveryConfirmedAt,value.firstTokenExpiresAt].filter(Boolean).map((item:string)=>new Date(item)).sort((a:Date,b:Date)=>a.getTime()-b.getTime())[0];if(!trigger||trigger>cutoff)continue;eligible++;if(execute){const artifact=resolve(dir,value.artifactFile);if(!artifact.startsWith(dir))throw new Error(`${kind.toUpperCase()}_PATH_OUTSIDE_ROOT`);await rm(artifact,{force:true});await rm(path,{force:true});affected++;}}return{eligible,held,affected};}
async function backupFiles(dir:string,max:number,execute:boolean){const files=[];for(const name of await readdir(dir)){if(!/^agm-postgres-.*\.dump$/.test(name))continue;const path=join(dir,name),info=await stat(path);files.push({path,mtime:info.mtimeMs});}files.sort((a,b)=>b.mtime-a.mtime);const expired=files.slice(max);if(execute)for(const item of expired){await rm(item.path,{force:true});await rm(item.path.replace(/\.dump$/,'.sha256'),{force:true});}return{eligible:expired.length,affected:execute?expired.length:0};}
main().catch(error=>{process.stderr.write(`RETENTION_ENGINE_FAIL reason=${error instanceof Error?error.message:'UNKNOWN'}\n`);process.exitCode=1;}).finally(()=>prisma.$disconnect());
