import { Prisma, PrismaClient } from '@prisma/client';
import { randomUUID } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { AuditService } from '../src/audit/audit.service';
import { AuthorityControlPlaneService } from '../src/authority-control-plane/authority-control-plane.service';
import { CarMoverService } from '../src/car-mover/car-mover.service';
import type { RequestContext } from '../src/common/request-context';
import { FRESHNESS_MS, LiveProviderError, type AdapterCategory, type NormalizedLiveContract } from '../src/live-adapters/live-adapter.contracts';
import { LiveAdapterService } from '../src/live-adapters/live-adapter.service';
import { OpportunityIntelligenceService } from '../src/opportunity-intelligence/opportunity-intelligence.service';
import { aggregateChain, assessCost, assessRoute, hash, judgeChain, normalizeOpportunity } from '../src/opportunity-intelligence/opportunity-intelligence.engine';

async function main(){
 const prisma=new PrismaClient(),company=await prisma.company.findFirst({orderBy:{createdAt:'asc'}});if(!company)throw Error('No Company');const user=await prisma.user.findFirst({where:{companyId:company.id},orderBy:{createdAt:'asc'}});if(!user)throw Error('No User');const runId=`live-adapters-${Date.now()}`;const ctx:RequestContext={companyId:company.id,userId:user.id,roles:['OWNER','PREMIUM_ACCESS'],requestId:randomUUID(),correlationId:randomUUID()};const telemetryBefore=await prisma.liveAdapterTelemetry.findMany({where:{companyId:company.id}});
 const audit=new AuditService(prisma as never),authority=new AuthorityControlPlaneService(prisma as never),carMover=new CarMoverService(prisma as never,audit),oi=new OpportunityIntelligenceService(prisma as never,authority,carMover,audit);
 let geoPrimary:'DOWN'|'LIVE'='DOWN',routePrimary:'DOWN'|'LIVE'='DOWN',routeSecondary:'DOWN'|'LIVE'='DOWN',trafficState:'DOWN'|'LIVE'|'TIMEOUT'|'RATE_LIMITED'='DOWN',routeCalls=0,tollCalls=0;
 const geo1=stub('GEOCODING','tomtom',10,()=>geoPrimary==='DOWN'?fail():geo()),geo2=stub('GEOCODING','here',20,()=>geo('here'));
 const road1=stub('ROUTE','tomtom',10,()=>{routeCalls++;return routePrimary==='DOWN'?fail():route();}),road2=stub('ROUTE','here',20,()=>routeSecondary==='DOWN'?fail():route('here'));
 const traffic=stub('TRAFFIC','tomtom',10,()=>{if(trafficState==='TIMEOUT')throw new LiveProviderError('TIMEOUT');if(trafficState==='RATE_LIMITED')throw new LiveProviderError('RATE_LIMITED');return trafficState==='DOWN'?fail():trafficResult();}),toll=stub('TOLL','tollguru',10,()=>{tollCalls++;return tollResult();}),transit=stub('TRANSIT','here',10,()=>transitResult());
 const service=new LiveAdapterService(prisma as never,oi,geo1 as never,geo2 as never,road1 as never,road2 as never,traffic as never,toll as never,transit as never);
 try{
  await authority.dashboard(ctx);
  const secondary=await service.resolve('GEOCODING',{query:`Berlin ${runId}`},ctx,true);assert(secondary.mode==='LIVE'&&secondary.provider==='here'&&secondary.status==='DEGRADED','LIVE-12 primary down selects secondary and reports degraded');
  routePrimary='DOWN';routeSecondary='DOWN';const manual=await service.resolve('ROUTE',{origin,destination:{latitude:53.55,longitude:9.99}},ctx,true);assert(manual.mode==='MANUAL'&&manual.status==='DEGRADED','LIVE-13 secondary down reaches explicit manual fallback');
  trafficState='RATE_LIMITED';const rateLimited=await service.resolve('TRAFFIC',{origin,destination:{latitude:51.01,longitude:9.01}},ctx,true);assert(rateLimited.mode==='MANUAL'&&(await service.telemetrySnapshot(ctx)).some((item)=>item.adapterId==='live.traffic.tomtom'&&item.status==='RATE_LIMITED'&&item.lastErrorCode==='RATE_LIMITED'),'LIVE-14 rate limit is classified in runtime telemetry');
  trafficState='TIMEOUT';const timedOut=await service.resolve('TRAFFIC',{origin,destination:{latitude:51.02,longitude:9.02}},ctx,true);assert(timedOut.mode==='MANUAL'&&(await service.telemetrySnapshot(ctx)).some((item)=>item.adapterId==='live.traffic.tomtom'&&item.lastErrorCode==='TIMEOUT'),'LIVE-15 timeout is classified in runtime telemetry');
  const staleInput={origin,destination:{latitude:52.51,longitude:13.39}},staleKey=hash({category:'TRAFFIC',input:staleInput}),stalePayload={...trafficResult(),freshness:'LIVE'};await prisma.liveAdapterCache.upsert({where:{companyId_category_cacheKey:{companyId:company.id,category:'TRAFFIC',cacheKey:staleKey}},create:{companyId:company.id,category:'TRAFFIC',providerId:'tomtom',cacheKey:staleKey,inputHash:hash(staleInput),payloadHash:hash(stalePayload),payload:stalePayload as Prisma.InputJsonValue,sourceReference:'controlled:traffic',fetchedAt:new Date(Date.now()-600_000),validUntil:new Date(Date.now()-300_000)},update:{payload:stalePayload as Prisma.InputJsonValue,fetchedAt:new Date(Date.now()-600_000),validUntil:new Date(Date.now()-300_000)}});const stale=await service.resolve('TRAFFIC',staleInput,ctx,true);assert(stale.mode==='STALE_CACHE'&&stale.warning==='STALE_CACHE_EXPLICIT_WARNING'&&stale.data?.freshness==='STALE','LIVE-07/16 expired traffic cache is never silent');
  const foreignCompany=randomUUID(),foreignInput={origin,destination:{latitude:48.13,longitude:11.58}},foreignKey=hash({category:'ROUTE',input:foreignInput});await prisma.liveAdapterCache.create({data:{companyId:foreignCompany,category:'ROUTE',providerId:'foreign',cacheKey:foreignKey,inputHash:hash(foreignInput),payloadHash:hash(route()),payload:route() as Prisma.InputJsonValue,sourceReference:'foreign:route',fetchedAt:new Date(),validUntil:new Date(Date.now()+600_000)}});const isolated=await service.resolve('ROUTE',foreignInput,ctx,false);assert(isolated.mode==='MANUAL','LIVE-18 cache is tenant isolated');
  routePrimary='LIVE';const recalcInput={origin,destination:{latitude:50.11,longitude:8.68}};const first=await service.resolve('ROUTE',recalcInput,ctx,true),cached=await service.resolve('ROUTE',recalcInput,ctx,false);assert(first.snapshotId&&cached.mode==='CACHE','fresh identical route uses cache');const recalcKey=hash({category:'ROUTE',input:recalcInput});await prisma.liveAdapterCache.update({where:{companyId_category_cacheKey:{companyId:company.id,category:'ROUTE',cacheKey:recalcKey}},data:{validUntil:new Date(Date.now()-1)}});const recalculated=await service.resolve('ROUTE',recalcInput,ctx,false);assert(recalculated.mode==='LIVE'&&recalculated.snapshotId!==first.snapshotId&&routeCalls>=2,'LIVE-21 route recalculates after expiry');
  const routeSnapshot=await snapshot(prisma,company.id,'ROUTE',route()),transitSnapshot=await snapshot(prisma,company.id,'TRANSIT',transitResult()),tollSnapshot=await snapshot(prisma,company.id,'TOLL',tollResult());const multimodal=await service.opportunityInput({routeSnapshotId:routeSnapshot,transitSnapshotIds:[transitSnapshot],tollSnapshotId:tollSnapshot},ctx);assert(multimodal.route.mobilityModes.includes('TRAIN')&&multimodal.cost.train===39&&multimodal.cost.tolls===18.5,'LIVE-11 normalized multimodal reposition feeds Route/Cost inputs');
  const timestamp=new Date().toISOString(),fields={pickupLocation:'Berlin',deliveryLocation:'Hamburg',pickupWindowStart:timestamp,priceAmount:500,currencyCode:'EUR',vehicleType:'Car'};const email=await oi.intake({idempotencyKey:`${runId}-email`,channel:'email',provider:'gmail',platform:'Official Platform',sourceOpportunityId:'EMAIL-X',pickupLocation:'Berlin',deliveryLocation:'Hamburg',pickupWindowStart:timestamp,priceAmount:500,currencyCode:'EUR',vehicleType:'Car',sourceTimestamp:timestamp},ctx);const fingerprint=hash({platform:'Official Platform',id:'PLATFORM-X',fields});const feed=await service.ingestPlatformFeed({sourcePlatform:'Official Platform',sourceOpportunityId:'PLATFORM-X',rawReference:`${runId}-feed`,normalizedFields:fields,sourceTimestamp:timestamp,confidence:95,dedupFingerprint:fingerprint},ctx);assert(feed.normalizedOpportunityId===email.normalizedOpportunityId&&feed.deduplicated,'LIVE-20 official platform feed correlates with Gmail opportunity');
  const priceA=normalizeOpportunity({pickupLocation:'A',deliveryLocation:'B',priceAmount:100,currencyCode:'EUR',sourceTimestamp:timestamp}),priceB=normalizeOpportunity({pickupLocation:'A',deliveryLocation:'B',priceAmount:180,currencyCode:'EUR',sourceTimestamp:timestamp});const r=assessRoute({distanceKm:100,durationMinutes:90,distanceToPickupKm:10,sources:['test'],confidence:90});const v1=judgeChain(aggregateChain([{opportunityId:'x',route:r,cost:assessCost(priceA,r,{fuel:30})}]),'FRESH'),v2=judgeChain(aggregateChain([{opportunityId:'x',route:r,cost:assessCost(priceB,r,{fuel:30})}]),'FRESH');assert(v1.inputHash!==v2.inputHash,'LIVE-22 source price change invalidates chain/verdict input hash');
  const tollCallsBefore=tollCalls,skippedToll=await service.resolve('TOLL',{origin,destination:{latitude:49,longitude:9},routeReference:`${runId}-not-required`,tollRequired:false},ctx,true),tollProviderCallAvoided=skippedToll.mode==='SKIPPED'&&tollCalls===tollCallsBefore;assert(tollProviderCallAvoided,'LIVE-25 TollGuru is not called without deterministic tollRequired');
  const financialBefore=await prisma.carMoverFinancialEntry.count({where:{companyId:company.id}}),invoiceBefore=await prisma.carMoverInvoice.count({where:{companyId:company.id}});await service.resolve('TOLL',{origin,destination:{latitude:49,longitude:9},routeReference:runId,tollRequired:true,tollReason:'COST_RISK_EXPLICIT'},ctx,true);assert(await prisma.carMoverFinancialEntry.count({where:{companyId:company.id}})===financialBefore&&await prisma.carMoverInvoice.count({where:{companyId:company.id}})===invoiceBefore,'LIVE-23 estimated live data remains outside accounting');
  const manualJob=await carMover.create({vehicle:{vehicleClass:'OTHER_DRIVABLE_VEHICLE',vehicleType:'Live adapter fallback test'},pickup:{label:'Manual A'},destination:{label:'Manual B'},sourceReference:`${runId}-manual`},ctx);assert((await carMover.getJobFile(manualJob.jobId,ctx)).job.id===manualJob.jobId,'LIVE-24 manual Car Mover remains operational');
  const serialized=JSON.stringify(await prisma.liveAdapterCache.findMany({where:{companyId:company.id}}))+JSON.stringify(await service.telemetrySnapshot(ctx));assert(!serialized.includes('guardian-reference')&&!serialized.includes('API_KEY'),'LIVE-19 secrets absent from cache and telemetry');
  const report={verdict:'PASS',runId,scenarios:{'7':'PASS stale traffic explicit','11':'PASS multimodal','12':'PASS primary to secondary','13':'PASS degraded/manual','14':'PASS controlled rate-limit classification','15':'PASS controlled timeout classification','16':'PASS stale cache warning','18':'PASS tenant isolation','19':'PASS secret isolation','20':'PASS cross-channel dedup','21':'PASS route recalc','22':'PASS price-change invalidation','23':'PASS accounting isolation','24':'PASS manual fallback','25':'PASS conditional TollGuru boundary'},evidence:{secondaryProvider:secondary.provider,recalculatedSnapshotId:recalculated.snapshotId,platformSnapshotId:feed.snapshotId,manualJobId:manualJob.jobId,tollProviderCallAvoided,telemetry:await service.telemetrySnapshot(ctx)}};const dir=path.resolve(__dirname,'../../../evidence/live-mobility/runtime',runId);await mkdir(dir,{recursive:true});await writeFile(path.join(dir,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({...report,reportPath:path.join(dir,'report.json')},null,2));
 }finally{for(const item of telemetryBefore){await prisma.liveAdapterTelemetry.update({where:{id:item.id},data:{category:item.category,providerId:item.providerId,status:item.status,lastAttemptAt:item.lastAttemptAt,lastSuccessAt:item.lastSuccessAt,latencyMs:item.latencyMs,requestCount:item.requestCount,errorCount:item.errorCount,errorRateBps:item.errorRateBps,rateLimitState:item.rateLimitState,fallbackActivation:item.fallbackActivation,cacheAgeSeconds:item.cacheAgeSeconds,lastErrorCode:item.lastErrorCode,requestCostMicros:item.requestCostMicros,contractVersion:item.contractVersion}});}await prisma.$disconnect();}
}
const origin={latitude:52.52,longitude:13.405};
function stub(category:AdapterCategory,providerId:string,priority:number,fn:()=>NormalizedLiveContract|never){return{adapterId:`live.${category.toLowerCase()}.${providerId}`,providerId,category,priority,configured:()=>true,fetch:async()=>fn()};}
function fail():never{throw new LiveProviderError('UNAVAILABLE');}
function meta(provider='tomtom'){const now=new Date();return{provider,timestamp:now.toISOString(),validUntil:new Date(now.getTime()+FRESHNESS_MS.ROUTE).toISOString(),freshness:'LIVE' as const,confidence:90,sourceReference:`controlled:${provider}`,warnings:[]};}
function loc(label='Berlin'){return{label,coordinates:origin};}function geo(provider='tomtom'){return{contractType:'GeocodingResult' as const,normalizedLocation:loc(),ambiguous:false,alternatives:[],...meta(provider)};}function route(provider='tomtom'){return{contractType:'RouteResult' as const,origin:loc('Berlin'),destination:{label:'Hamburg',coordinates:{latitude:53.55,longitude:9.99}},distanceKm:290,estimatedDurationMinutes:210,alternatives:[],tollsAvailable:true,restrictions:[],...meta(provider)};}function trafficResult(){return{contractType:'TrafficSnapshot' as const,affectedSegment:{origin,destination:{latitude:52.51,longitude:13.39}},delayMinutes:12,congestionLevel:'HEAVY' as const,...meta()};}function tollResult(){return{contractType:'TollEstimate' as const,routeReference:'route',estimatedToll:18.5,currencyCode:'EUR',assumptions:['ESTIMATE'],...meta('tollguru')};}function transitResult(){const departure=new Date(Date.now()+3600_000),arrival=new Date(Date.now()+7200_000);return{contractType:'TransitOption' as const,origin:loc(),destination:{label:'Hamburg',coordinates:{latitude:53.55,longitude:9.99}},departure:departure.toISOString(),arrival:arrival.toISOString(),transfers:1,durationMinutes:60,estimatedPrice:39,currencyCode:'EUR',operator:'DB',modes:['TRAIN','WALK'],...meta('here')};}
async function snapshot(prisma:PrismaClient,companyId:string,category:string,payload:NormalizedLiveContract){const row=await prisma.liveMobilitySnapshot.create({data:{companyId,category,contractType:payload.contractType,contractVersion:'agm-live-adapters.v1',providerId:payload.provider,sourceReference:payload.sourceReference,inputHash:hash(payload),payloadHash:hash(payload),payload:payload as Prisma.InputJsonValue,fetchedAt:new Date(payload.timestamp),validUntil:new Date(payload.validUntil),confidence:payload.confidence}});return row.id;}
function assert(value:unknown,message:string):asserts value{if(!value)throw Error(`Live adapter runtime failed: ${message}`);}void main();
