import { ConfigService } from '@nestjs/config';
import { LiveProviderError } from '../src/live-adapters/live-adapter.contracts';
import { HereRouteAdapter, HereTransitAdapter, TollGuruAdapter, TomTomGeocodingAdapter, TomTomRouteAdapter, TomTomTrafficAdapter } from '../src/live-adapters/provider-adapters';

const config = new ConfigService({ TOMTOM_API_KEY:'guardian-reference-test-key', HERE_API_KEY:'guardian-reference-here-key', TOLLGURU_API_KEY:'guardian-reference-toll-key' });
const origin={latitude:52.52,longitude:13.405},destination={latitude:53.55,longitude:9.99};
const response=(body:unknown,status=200)=>Promise.resolve({ok:status>=200&&status<300,status,json:async()=>body} as Response);

describe('Live mobility provider adapters',()=>{
  afterEach(()=>jest.restoreAllMocks());
  it('LIVE-01 normalizes valid geocoding',async()=>{jest.spyOn(global,'fetch').mockImplementation(()=>response({results:[{score:.91,position:{lat:52.52,lon:13.405},address:{freeformAddress:'Berlin, Germany',countryCodeISO3:'DEU'}}]}));const result=await new TomTomGeocodingAdapter(config).fetch({query:'Berlin'});expect(result.normalizedLocation.label).toContain('Berlin');expect(result.confidence).toBe(91);});
  it('LIVE-02 marks ambiguous geocoding and alternatives',async()=>{jest.spyOn(global,'fetch').mockImplementation(()=>response({results:[{position:{lat:52.52,lon:13.405},address:{freeformAddress:'Berlin'}},{position:{lat:52.5,lon:13.3},address:{freeformAddress:'Berlin Alt'}}]}));const result=await new TomTomGeocodingAdapter(config).fetch({query:'Berlin'});expect(result.ambiguous).toBe(true);expect(result.alternatives).toHaveLength(1);});
  it('LIVE-03 rejects an unknown address',async()=>{jest.spyOn(global,'fetch').mockImplementation(()=>response({results:[]}));await expect(new TomTomGeocodingAdapter(config).fetch({query:'not-found'})).rejects.toMatchObject({code:'UNAVAILABLE'});});
  it('LIVE-04 normalizes a valid traffic-aware route',async()=>{jest.spyOn(global,'fetch').mockImplementation(()=>response({routes:[{summary:{lengthInMeters:290000,travelTimeInSeconds:12600,trafficDelayInSeconds:600,tollRoadLengthInMeters:12000}}]}));const result=await new TomTomRouteAdapter(config).fetch({origin,destination});expect(result).toMatchObject({distanceKm:290,estimatedDurationMinutes:210,trafficDelayMinutes:10,tollsAvailable:true});});
  it('LIVE-05 returns unavailable when no route exists',async()=>{jest.spyOn(global,'fetch').mockImplementation(()=>response({routes:[]}));await expect(new TomTomRouteAdapter(config).fetch({origin,destination})).rejects.toMatchObject({code:'UNAVAILABLE'});});
  it('LIVE-06 normalizes live traffic',async()=>{jest.spyOn(global,'fetch').mockImplementation(()=>response({flowSegmentData:{currentSpeed:30,freeFlowSpeed:100,currentTravelTime:900,freeFlowTravelTime:300}}));const result=await new TomTomTrafficAdapter(config).fetch({origin,destination});expect(result.congestionLevel).toBe('HEAVY');expect(result.delayMinutes).toBe(10);});
  it('LIVE-07 HERE fallback routing avoids implicit toll-cost transactions',async()=>{let requested='';jest.spyOn(global,'fetch').mockImplementation((url)=>{requested=String(url);return response({routes:[{sections:[{summary:{length:290000,duration:12600}}]}]});});const result=await new HereRouteAdapter(config).fetch({origin,destination,vehicle:{commercial:true}});expect(result).toMatchObject({distanceKm:290,estimatedDurationMinutes:210});const parsed=new URL(requested);expect(parsed.searchParams.get('return')).toBe('summary,travelSummary');expect(parsed.searchParams.get('return')).not.toContain('tolls');expect(parsed.searchParams.get('return')).not.toContain('notices');});
  it('LIVE-08 normalizes a toll estimate',async()=>{jest.spyOn(global,'fetch').mockImplementation(()=>response({routes:[{costs:{tag:24.5,currency:'EUR'}}]}));const result=await new TollGuruAdapter(config).fetch({origin,destination,routeReference:'route-1',tollRequired:true,tollReason:'COST_RISK_EXPLICIT'});expect(result).toMatchObject({estimatedToll:24.5,currencyCode:'EUR'});expect(JSON.stringify(result)).not.toContain('guardian-reference');});
  it('LIVE-09 normalizes a train reposition option',async()=>{const departure=new Date(Date.now()+3600_000).toISOString(),arrival=new Date(Date.now()+7200_000).toISOString();jest.spyOn(global,'fetch').mockImplementation(()=>response({routes:[{sections:[{type:'pedestrian',departure:{time:departure},arrival:{time:new Date(Date.now()+3900_000).toISOString()}},{type:'transit',transport:{mode:'TRAIN',name:'ICE'},departure:{time:new Date(Date.now()+3900_000).toISOString()},arrival:{time:arrival},fares:[{price:{value:39.9,currency:'EUR'}}]}]}]}));const result=await new HereTransitAdapter(config).fetch({origin,destination,departureTime:departure});expect(result.modes).toContain('transit');expect(result.operator).toBe('ICE');expect(result.estimatedPrice).toBe(39.9);});
  it('LIVE-10 exposes an expired train option through validUntil',async()=>{const departure=new Date(Date.now()-7200_000).toISOString(),arrival=new Date(Date.now()-3600_000).toISOString();jest.spyOn(global,'fetch').mockImplementation(()=>response({routes:[{sections:[{type:'transit',transport:{mode:'TRAIN',name:'RE'},departure:{time:departure},arrival:{time:arrival}}]}]}));const result=await new HereTransitAdapter(config).fetch({origin,destination,departureTime:departure});expect(new Date(result.validUntil).getTime()).toBeLessThan(Date.now());});
  it('LIVE-14 classifies provider rate limiting',async()=>{jest.spyOn(global,'fetch').mockImplementation(()=>response({},429));await expect(new TomTomRouteAdapter(config).fetch({origin,destination})).rejects.toMatchObject({code:'RATE_LIMITED'});});
  it('LIVE-15 classifies provider timeout',async()=>{jest.useFakeTimers();jest.spyOn(global,'fetch').mockImplementation((_url,init)=>new Promise((_resolve,reject)=>init?.signal?.addEventListener('abort',()=>reject(Object.assign(new Error('aborted'),{name:'AbortError'})))));const pending=new TomTomRouteAdapter(config).fetch({origin,destination});const expectation=expect(pending).rejects.toMatchObject({code:'TIMEOUT'});await jest.advanceTimersByTimeAsync(8001);await expectation;jest.useRealTimers();});
  it('LIVE-17 rejects malformed provider responses',async()=>{jest.spyOn(global,'fetch').mockImplementation(()=>response({flowSegmentData:{currentSpeed:'bad'}}));await expect(new TomTomTrafficAdapter(config).fetch({origin,destination})).rejects.toBeInstanceOf(LiveProviderError);});
});
