import { executionAuthorized,retentionPlan,validateRetentionPolicy,type RetentionPolicy } from '../src/data-lifecycle/retention-engine';
const policy:RetentionPolicy={schemaVersion:1,policyVersion:'owner-approved-2026-08-16',timezone:'UTC',productionActivationAuthorized:false,categories:{expiredAuthSessions:{enabled:true,latencyHours:24},revokedAuthSessions:{enabled:true,retentionDays:30},completedDsarRecords:{enabled:true,calendarYearsAfterCompletion:3},generatedDsarExports:{enabled:true,retentionDays:7},postgresBackups:{enabled:true,maxSuccessfulDailyGenerations:7},suppressionLedgerEntries:{enabled:true,backupHorizonDays:7,verificationMarginDays:30},identifierAuditLogs:{enabled:true,retentionDays:90}} as any,excluded:['accounting','invoices','legally-required-commercial-documents']};
describe('Owner-approved retention policy',()=>{
  const now=new Date('2026-08-16T12:00:00.000Z');
  it('validates the exact approved configuration',()=>expect(validateRetentionPolicy(policy)).toBe(policy));
  it('rejects drift from an approved duration',()=>expect(()=>validateRetentionPolicy({...policy,categories:{...policy.categories,revokedAuthSessions:{enabled:true,retentionDays:31}}})).toThrow('RETENTION_APPROVAL_MISMATCH'));
  it('remains globally disabled by default',()=>expect(retentionPlan(policy,{},now).every(item=>!item.enabled&&item.reason==='ENGINE_DISABLED_FAIL_CLOSED')).toBe(true));
  it('computes exact UTC boundaries',()=>{const plan=retentionPlan(policy,{RETENTION_ENGINE_ENABLED:'true'},now);expect(plan.find(item=>item.category==='expiredAuthSessions')?.cutoff?.toISOString()).toBe('2026-08-15T12:00:00.000Z');expect(plan.find(item=>item.category==='revokedAuthSessions')?.cutoff?.toISOString()).toBe('2026-07-17T12:00:00.000Z');expect(plan.find(item=>item.category==='generatedDsarExports')?.cutoff?.toISOString()).toBe('2026-08-09T12:00:00.000Z');expect(plan.find(item=>item.category==='suppressionLedgerEntries')?.cutoff?.toISOString()).toBe('2026-07-10T12:00:00.000Z');expect(plan.find(item=>item.category==='identifierAuditLogs')?.cutoff?.toISOString()).toBe('2026-05-18T12:00:00.000Z');});
  it('uses the start of the year three years earlier as an exclusive DSAR cutoff',()=>{const item=retentionPlan(policy,{RETENTION_ENGINE_ENABLED:'true'},new Date('2027-01-01T00:00:00+14:00')).find(item=>item.category==='completedDsarRecords');expect(item?.cutoff?.toISOString()).toBe('2023-01-01T00:00:00.000Z');expect(item?.exclusiveCutoff).toBe(true);});
  it('requires three independent non-production execution gates',()=>{expect(executionAuthorized(policy,{RETENTION_ENGINE_ENABLED:'true',RETENTION_EXECUTE:'true'})).toBe(false);expect(executionAuthorized(policy,{RETENTION_ENGINE_ENABLED:'true',RETENTION_EXECUTE:'true',RETENTION_NON_PRODUCTION_CONFIRMATION:'true'})).toBe(true);});
});
