import { mkdtemp,readFile,writeFile } from 'node:fs/promises';import { tmpdir } from 'node:os';import { join } from 'node:path';import { appendLedgerRecord,compactLedger,effectiveActions,ledgerKey,readVerifiedLedger,subjectPseudonym } from '../src/data-rights/suppression-ledger';
const key=Buffer.alloc(32,7).toString('base64');
describe('durable suppression ledger',()=>{
  test('minimized pseudonymized chained records verify',async()=>{const dir=await mkdtemp(join(tmpdir(),'agm-ledger-'));const path=join(dir,'ledger.jsonl');const parsed=ledgerKey(key);await appendLedgerRecord(path,parsed,{subjectPseudonym:subjectPseudonym('company','subject',parsed),action:'RESTRICT',effectiveAt:'2026-08-16T00:00:00.000Z',categories:['ACCOUNT'],status:'APPLIED',applicationEvidence:'proof-1'});const rows=await readVerifiedLedger(path,parsed);expect(rows).toHaveLength(1);expect(JSON.stringify(rows)).not.toContain('subject"');expect(JSON.stringify(rows)).not.toContain('company"');});
  test('missing ledger fails closed',async()=>{await expect(readVerifiedLedger(join(tmpdir(),'agm-ledger-absent.jsonl'),ledgerKey(key))).rejects.toThrow('SUPPRESSION_LEDGER_MISSING');});
  test('corruption fails closed',async()=>{const dir=await mkdtemp(join(tmpdir(),'agm-ledger-'));const path=join(dir,'ledger.jsonl');const parsed=ledgerKey(key);await appendLedgerRecord(path,parsed,{subjectPseudonym:'a'.repeat(64),action:'DELETE',effectiveAt:'2026-08-16T00:00:00.000Z',categories:['ACCOUNT'],status:'APPLIED',applicationEvidence:'proof'});const raw=await readFile(path,'utf8');await writeFile(path,raw.replace('DELETE','RESTRICT'));await expect(readVerifiedLedger(path,parsed)).rejects.toThrow('SUPPRESSION_LEDGER_MAC_INVALID');});
  test('strongest action wins across repeated requests',()=>{const base:any={version:1,eventId:'1',subjectPseudonym:'a'.repeat(64),effectiveAt:'2026-08-16T00:00:00.000Z',categories:[],status:'APPLIED',applicationEvidence:'x',previousMac:'GENESIS',mac:'b'.repeat(64)};expect(effectiveActions([{...base,action:'RESTRICT'},{...base,eventId:'2',action:'DELETE'}])[0].action).toBe('DELETE');});
  test('restore wrapper is blocked until a verified proof is atomically published',async()=>{const script=await readFile(join(__dirname,'..','..','..','deploy','operations','restore-with-dsar-gate.sh'),'utf8');expect(script).toContain('RESTORE_SUPPRESSION_NOT_VERIFIED');expect(script.indexOf('"status":"BLOCKED"')).toBeLessThan(script.indexOf('apply-restore-suppressions.ts'));expect(script.indexOf('apply-restore-suppressions.ts')).toBeLessThan(script.indexOf('"status":"PASS"'));expect(script).toContain('suppression_apply_failed');});
  test('compacts only entries strictly older than cutoff and preserves a verifiable chain',async()=>{const dir=await mkdtemp(join(tmpdir(),'agm-ledger-compact-'));const path=join(dir,'ledger.jsonl'),parsed=ledgerKey(key);await appendLedgerRecord(path,parsed,{subjectPseudonym:'1'.repeat(64),action:'DELETE',effectiveAt:'2026-07-10T11:59:59.999Z',categories:['ACCOUNT'],status:'APPLIED',applicationEvidence:'old'});await appendLedgerRecord(path,parsed,{subjectPseudonym:'2'.repeat(64),action:'RESTRICT',effectiveAt:'2026-07-10T12:00:00.000Z',categories:['ACCOUNT'],status:'APPLIED',applicationEvidence:'boundary'});expect(await compactLedger(path,parsed,new Date('2026-07-10T12:00:00.000Z'),true)).toEqual(expect.objectContaining({affectedSubjects:1,dryRun:true}));await compactLedger(path,parsed,new Date('2026-07-10T12:00:00.000Z'),false);expect(effectiveActions(await readVerifiedLedger(path,parsed)).map(item=>item.subjectPseudonym)).toEqual(['2'.repeat(64)]);});
});
